const Lead = require("./Lead/LeadPlatformApplicationClient");

const Theme = require("./Theme/ThemePlatformApplicationClient");

const User = require("./User/UserPlatformApplicationClient");

const Content = require("./Content/ContentPlatformApplicationClient");

const Communication = require("./Communication/CommunicationPlatformApplicationClient");

const Payment = require("./Payment/PaymentPlatformApplicationClient");

const Order = require("./Order/OrderPlatformApplicationClient");

const FileStorage = require("./FileStorage/FileStoragePlatformApplicationClient");

const Share = require("./Share/SharePlatformApplicationClient");

const Configuration = require("./Configuration/ConfigurationPlatformApplicationClient");

const Cart = require("./Cart/CartPlatformApplicationClient");

const Rewards = require("./Rewards/RewardsPlatformApplicationClient");

const Analytics = require("./Analytics/AnalyticsPlatformApplicationClient");

const Partner = require("./Partner/PartnerPlatformApplicationClient");

const { FDKClientValidationError } = require("../common/FDKError");

class PlatformApplicationClient {
  constructor(applicationId, config) {
    this.config = config;
    this.companyId = config.companyId;
    this.applicationId = applicationId;

    this.lead = new Lead(config, applicationId);

    this.theme = new Theme(config, applicationId);

    this.user = new User(config, applicationId);

    this.content = new Content(config, applicationId);

    this.communication = new Communication(config, applicationId);

    this.payment = new Payment(config, applicationId);

    this.order = new Order(config, applicationId);

    this.fileStorage = new FileStorage(config, applicationId);

    this.share = new Share(config, applicationId);

    this.configuration = new Configuration(config, applicationId);

    this.cart = new Cart(config, applicationId);

    this.rewards = new Rewards(config, applicationId);

    this.analytics = new Analytics(config, applicationId);

    this.partner = new Partner(config, applicationId);
  }

  setExtraHeaders(header) {
    if (typeof header === "object") {
      this.config.extraHeaders.push(header);
    } else {
      throw new FDKClientValidationError("Context value should be an object");
    }
  }
}

/** @typedef ApplicationAuth */
/** @typedef ApplicationCors */
/** @typedef ApplicationData */
/** @typedef ApplicationMeta */
/** @typedef ApplicationRedirections */
/** @typedef ApplicationResponse */
/** @typedef ApplicationWebsite */
/** @typedef BadRequest */
/** @typedef Currency */
/** @typedef Domain */
/** @typedef LocationDefaultCurrency */
/** @typedef LocationDefaultLanguage */
/** @typedef LocationDetails */
/** @typedef Locations */
/** @typedef NotFound */
/** @typedef Page */
/** @typedef SecureUrl */

/** @typedef AddTicketPayload */
/** @typedef AgentChangePayload */
/** @typedef CategoryData */
/** @typedef CloseVideoRoomResponse */
/** @typedef CommunicationDetails */
/** @typedef CreateCustomFormPayload */
/** @typedef CreatedOn */
/** @typedef CreateVideoRoomPayload */
/** @typedef CreateVideoRoomResponse */
/** @typedef CustomForm */
/** @typedef CustomFormList */
/** @typedef CustomFormSubmissionPayload */
/** @typedef Debug */
/** @typedef EditCustomFormPayload */
/** @typedef EditTicketPayload */
/** @typedef Email */
/** @typedef FeedbackForm */
/** @typedef FeedbackResponseItem */
/** @typedef Filter */
/** @typedef GetParticipantsInsideVideoRoomResponse */
/** @typedef GetTokenForVideoRoomResponse */
/** @typedef IntegrationConfig */
/** @typedef NotifyUser */
/** @typedef Page */
/** @typedef Participant */
/** @typedef PhoneNumber */
/** @typedef PollForAssignment */
/** @typedef Priority */
/** @typedef Status */
/** @typedef SubmitButton */
/** @typedef SubmitCustomFormResponse */
/** @typedef SupportGeneralConfig */
/** @typedef Ticket */
/** @typedef TicketAsset */
/** @typedef TicketCategory */
/** @typedef TicketContent */
/** @typedef TicketContext */
/** @typedef TicketFeedback */
/** @typedef TicketFeedbackForm */
/** @typedef TicketFeedbackList */
/** @typedef TicketFeedbackPayload */
/** @typedef TicketHistory */
/** @typedef TicketHistoryList */
/** @typedef TicketHistoryPayload */
/** @typedef TicketList */
/** @typedef TicketSubCategory */
/** @typedef UserSchema */

/** @typedef AddThemeRequestSchema */
/** @typedef AllAvailablePageSchema */
/** @typedef AssetsSchema */
/** @typedef AvailablePagePredicate */
/** @typedef AvailablePageRoutePredicate */
/** @typedef AvailablePageSchema */
/** @typedef AvailablePageSchemaSections */
/** @typedef AvailablePageScreenPredicate */
/** @typedef AvailablePageSectionMetaAttributes */
/** @typedef AvailablePageSeo */
/** @typedef AvailablePageUserPredicate */
/** @typedef availableSectionSchema */
/** @typedef BlitzkriegApiErrorSchema */
/** @typedef BlitzkriegInternalServerErrorSchema */
/** @typedef BlitzkriegNotFoundSchema */
/** @typedef Blocks */
/** @typedef BlocksProps */
/** @typedef Bold */
/** @typedef Colors */
/** @typedef CommonJs */
/** @typedef Config */
/** @typedef ConfigPage */
/** @typedef Css */
/** @typedef Custom */
/** @typedef Font */
/** @typedef FontsSchema */
/** @typedef FontsSchemaItems */
/** @typedef FontsSchemaItemsFiles */
/** @typedef GlobalSchema */
/** @typedef GlobalSchemaProps */
/** @typedef Images */
/** @typedef Information */
/** @typedef Light */
/** @typedef ListSchemaItem */
/** @typedef Medium */
/** @typedef PaginationSchema */
/** @typedef Preset */
/** @typedef Regular */
/** @typedef Sections */
/** @typedef SemiBold */
/** @typedef Src */
/** @typedef ThemesListingResponseSchema */
/** @typedef ThemesSchema */
/** @typedef UmdJs */
/** @typedef UpgradableThemeSchema */
/** @typedef Variants */

/** @typedef Accountkit */
/** @typedef ArchiveUserRequestSchema */
/** @typedef ArchiveUserSuccess */
/** @typedef AuthenticationApiErrorSchema */
/** @typedef AuthenticationInternalServerErrorSchema */
/** @typedef AuthSuccess */
/** @typedef AuthSuccessUser */
/** @typedef AuthSuccessUserDebug */
/** @typedef AuthSuccessUserEmails */
/** @typedef BlockUserRequestSchema */
/** @typedef BlockUserSuccess */
/** @typedef CodeRequestBodySchema */
/** @typedef CreateUserGroupSchema */
/** @typedef CreateUserRequestSchema */
/** @typedef CreateUserResponseSchema */
/** @typedef CreateUserSessionRequestSchema */
/** @typedef CreateUserSessionResponseSchema */
/** @typedef CustomerListResponseSchema */
/** @typedef DeleteAccountConsent */
/** @typedef DeleteAccountReasons */
/** @typedef DeleteApplicationUserRequestSchema */
/** @typedef DeleteUserSuccess */
/** @typedef EditEmailRequestSchema */
/** @typedef EditMobileRequestSchema */
/** @typedef EditProfileMobileSchema */
/** @typedef EditProfileRequestSchema */
/** @typedef Email */
/** @typedef EmailOtpSuccess */
/** @typedef Facebook */
/** @typedef FlashCard */
/** @typedef ForgotPasswordRequestSchema */
/** @typedef FormRegisterRequestSchema */
/** @typedef FormRegisterRequestSchemaPhone */
/** @typedef Google */
/** @typedef HasPasswordSuccess */
/** @typedef Login */
/** @typedef LoginSuccess */
/** @typedef LogoutSuccess */
/** @typedef LookAndFeel */
/** @typedef MetaSchema */
/** @typedef NotFoundSchema */
/** @typedef OAuthRequestAppleSchema */
/** @typedef OAuthRequestAppleSchemaOauth */
/** @typedef OAuthRequestAppleSchemaProfile */
/** @typedef OAuthRequestSchema */
/** @typedef OAuthRequestSchemaOauth2 */
/** @typedef OAuthRequestSchemaProfile */
/** @typedef OtpSuccess */
/** @typedef PaginationSchema */
/** @typedef PasswordLoginRequestSchema */
/** @typedef PhoneNumber */
/** @typedef PlatformEmail */
/** @typedef PlatformMobile */
/** @typedef PlatformSchema */
/** @typedef ProfileEditSuccess */
/** @typedef ProfileEditSuccessSchema */
/** @typedef RegisterFormSuccess */
/** @typedef RegisterRequiredFields */
/** @typedef RegisterRequiredFieldsEmail */
/** @typedef RegisterRequiredFieldsMobile */
/** @typedef RequiredFields */
/** @typedef ResetPasswordSuccess */
/** @typedef SendEmailOtpRequestSchema */
/** @typedef SendEmailVerifyLinkSuccess */
/** @typedef SendMobileOtpRequestSchema */
/** @typedef SendMobileVerifyLinkSuccess */
/** @typedef SendOtpRequestSchema */
/** @typedef SendOtpResponse */
/** @typedef SendResetPasswordEmailRequestSchema */
/** @typedef SendResetPasswordMobileRequestSchema */
/** @typedef SendVerificationLinkMobileRequestSchema */
/** @typedef SessionDeleteResponseSchema */
/** @typedef SessionExpiry */
/** @typedef SessionListResponseInfo */
/** @typedef SessionListResponseSchema */
/** @typedef SessionListSuccess */
/** @typedef Social */
/** @typedef SocialTokens */
/** @typedef TokenRequestBodySchema */
/** @typedef UnauthenticatedSchema */
/** @typedef UnauthorizedSchema */
/** @typedef UnDeleteUserRequestSchema */
/** @typedef UnDeleteUserSuccess */
/** @typedef UpdatePasswordRequestSchema */
/** @typedef UpdateUserGroupSchema */
/** @typedef UpdateUserRequestSchema */
/** @typedef UserEmails */
/** @typedef UserGroupListResponseSchema */
/** @typedef UserGroupResponseSchema */
/** @typedef UserObjectSchema */
/** @typedef UserPhoneNumbers */
/** @typedef UserSchema */
/** @typedef UserSearchResponseSchema */
/** @typedef VerifyEmailOtpRequestSchema */
/** @typedef VerifyEmailOTPSuccess */
/** @typedef VerifyEmailSuccess */
/** @typedef VerifyMobileOTPSuccess */
/** @typedef VerifyOtpRequestSchema */
/** @typedef VerifyOtpSuccess */

/** @typedef Action */
/** @typedef ActionPage */
/** @typedef AdminAnnouncementSchema */
/** @typedef AnnouncementAuthorSchema */
/** @typedef AnnouncementPageSchema */
/** @typedef AnnouncementSchema */
/** @typedef AnnouncementsResponseSchema */
/** @typedef ApplicationLegal */
/** @typedef ApplicationLegalFAQ */
/** @typedef Asset */
/** @typedef Author */
/** @typedef BlogGetResponse */
/** @typedef BlogRequest */
/** @typedef BlogSchema */
/** @typedef CategoryRequestSchema */
/** @typedef CategorySchema */
/** @typedef ChildrenSchema */
/** @typedef CommonError */
/** @typedef ConfigurationSchema */
/** @typedef ContactSchema */
/** @typedef ContentAPIError */
/** @typedef ContentSchema */
/** @typedef CreateAnnouncementSchema */
/** @typedef CreatedBySchema */
/** @typedef CreateFaqCategoryRequestSchema */
/** @typedef CreateFaqCategorySchema */
/** @typedef CreateFaqResponseSchema */
/** @typedef CreateFaqSchema */
/** @typedef CreateTagRequestSchema */
/** @typedef CreateTagSchema */
/** @typedef CronSchedule */
/** @typedef CustomMetaTag */
/** @typedef CustomPage */
/** @typedef CustomPageSchema */
/** @typedef DataLoaderResetResponseSchema */
/** @typedef DataLoaderResponseSchema */
/** @typedef DataLoaderSchema */
/** @typedef DataLoaderSourceSchema */
/** @typedef DataLoadersSchema */
/** @typedef DateMeta */
/** @typedef DefaultNavigationResponse */
/** @typedef Detail */
/** @typedef EditorMeta */
/** @typedef EmailProperties */
/** @typedef EmailSchema */
/** @typedef FAQ */
/** @typedef FAQCategorySchema */
/** @typedef FaqResponseSchema */
/** @typedef FaqSchema */
/** @typedef FeatureImage */
/** @typedef GeneratedSEOContent */
/** @typedef GenerateSEOContent */
/** @typedef GetAnnouncementListSchema */
/** @typedef GetFaqCategoriesSchema */
/** @typedef GetFaqCategoryBySlugSchema */
/** @typedef GetFaqSchema */
/** @typedef HandpickedTagSchema */
/** @typedef LandingPage */
/** @typedef LandingPageGetResponse */
/** @typedef LandingPageSchema */
/** @typedef Language */
/** @typedef LocaleLanguage */
/** @typedef Navigation */
/** @typedef NavigationGetResponse */
/** @typedef NavigationReference */
/** @typedef NavigationRequest */
/** @typedef NavigationSchema */
/** @typedef NextSchedule */
/** @typedef Orientation */
/** @typedef Page */
/** @typedef PageContent */
/** @typedef PageGetResponse */
/** @typedef PageMeta */
/** @typedef PageMetaSchema */
/** @typedef PagePublishRequest */
/** @typedef PageRequest */
/** @typedef PageSchema */
/** @typedef PageSpec */
/** @typedef PageSpecItem */
/** @typedef PageSpecParam */
/** @typedef PathMappingSchema */
/** @typedef PathSourceSchema */
/** @typedef PhoneProperties */
/** @typedef PhoneSchema */
/** @typedef RemoveHandpickedSchema */
/** @typedef ResourceContent */
/** @typedef ScheduleSchema */
/** @typedef ScheduleStartSchema */
/** @typedef SEO */
/** @typedef SeoComponent */
/** @typedef SEOImage */
/** @typedef SeoSchema */
/** @typedef Slideshow */
/** @typedef SlideshowGetResponse */
/** @typedef SlideshowMedia */
/** @typedef SlideshowRequest */
/** @typedef SlideshowSchema */
/** @typedef Support */
/** @typedef TagDeleteSuccessResponse */
/** @typedef TagSchema */
/** @typedef TagSourceSchema */
/** @typedef TagsSchema */
/** @typedef UpdateFaqCategoryRequestSchema */
/** @typedef UpdateHandpickedSchema */

/** @typedef BadRequest */
/** @typedef CancelSubscriptionReq */
/** @typedef CancelSubscriptionRes */
/** @typedef ChargeLineItem */
/** @typedef CheckValidityResponse */
/** @typedef CreateOneTimeCharge */
/** @typedef CreateOneTimeChargeResponse */
/** @typedef CreateSubscriptionCharge */
/** @typedef CreateSubscriptionResponse */
/** @typedef CurrentPeriod */
/** @typedef DetailedPlan */
/** @typedef DetailedPlanComponents */
/** @typedef EntityChargePrice */
/** @typedef EntityChargeRecurring */
/** @typedef EntitySubscription */
/** @typedef InternalServerError */
/** @typedef Invoice */
/** @typedef InvoiceDetails */
/** @typedef InvoiceDetailsClient */
/** @typedef InvoiceDetailsPaymentMethods */
/** @typedef InvoiceDetailsPaymentMethodsData */
/** @typedef InvoiceDetailsPaymentMethodsDataChecks */
/** @typedef InvoiceDetailsPaymentMethodsDataNetworks */
/** @typedef InvoiceDetailsPaymentMethodsDataThreeDSecureUsage */
/** @typedef InvoiceDetailsPeriod */
/** @typedef InvoiceDetailsStatusTrail */
/** @typedef InvoiceItems */
/** @typedef InvoiceItemsPeriod */
/** @typedef InvoiceItemsPlan */
/** @typedef InvoiceItemsPlanRecurring */
/** @typedef InvoicePaymentMethod */
/** @typedef Invoices */
/** @typedef InvoicesData */
/** @typedef InvoicesDataClient */
/** @typedef InvoicesDataPaymentMethod */
/** @typedef InvoicesDataPeriod */
/** @typedef OneTimeChargeEntity */
/** @typedef OneTimeChargeItem */
/** @typedef Page */
/** @typedef Phone */
/** @typedef Plan */
/** @typedef PlanRecurring */
/** @typedef ResourceNotFound */
/** @typedef Subscription */
/** @typedef SubscriptionActivateReq */
/** @typedef SubscriptionActivateRes */
/** @typedef SubscriptionBillingAddress */
/** @typedef SubscriptionCharge */
/** @typedef SubscriptionCurrentPeriod */
/** @typedef SubscriptionCustomer */
/** @typedef SubscriptionCustomerCreate */
/** @typedef SubscriptionInvoiceSettings */
/** @typedef SubscriptionLimit */
/** @typedef SubscriptionLimitApplication */
/** @typedef SubscriptionLimitExtensions */
/** @typedef SubscriptionLimitIntegrations */
/** @typedef SubscriptionLimitMarketplace */
/** @typedef SubscriptionLimitOtherPlatform */
/** @typedef SubscriptionLimitProducts */
/** @typedef SubscriptionLimitTeam */
/** @typedef SubscriptionPauseCollection */
/** @typedef SubscriptionStatus */
/** @typedef SubscriptionTrial */
/** @typedef SubscriptionTrialPeriod */
/** @typedef UnauthenticatedApplication */
/** @typedef UnauthenticatedUser */

/** @typedef Audience */
/** @typedef AudienceReq */
/** @typedef Audiences */
/** @typedef BadRequestSchema */
/** @typedef BigqueryHeadersReq */
/** @typedef BigqueryHeadersRes */
/** @typedef BigqueryHeadersResHeaders */
/** @typedef Campaign */
/** @typedef CampaignEmail */
/** @typedef CampaignEmailTemplate */
/** @typedef CampaignReq */
/** @typedef Campaigns */
/** @typedef CampignEmailProvider */
/** @typedef EmailProvider */
/** @typedef EmailProviderReq */
/** @typedef EmailProviderReqFrom */
/** @typedef EmailProviders */
/** @typedef EmailTemplate */
/** @typedef EmailTemplateDeleteFailureRes */
/** @typedef EmailTemplateDeleteSuccessRes */
/** @typedef EmailTemplateHeaders */
/** @typedef EmailTemplateKeys */
/** @typedef EmailTemplateReq */
/** @typedef EmailTemplateRes */
/** @typedef EmailTemplates */
/** @typedef EngineRequest */
/** @typedef EngineResponse */
/** @typedef EventSubscription */
/** @typedef EventSubscriptions */
/** @typedef EventSubscriptionTemplate */
/** @typedef EventSubscriptionTemplateEmail */
/** @typedef EventSubscriptionTemplateSms */
/** @typedef GetNRecordsCsvReq */
/** @typedef GetNRecordsCsvRes */
/** @typedef GetNRecordsCsvResItems */
/** @typedef GetStats */
/** @typedef Job */
/** @typedef JobLog */
/** @typedef JobLogs */
/** @typedef Jobs */
/** @typedef Log */
/** @typedef LogEmail */
/** @typedef LogMeta */
/** @typedef LogPushnotification */
/** @typedef Logs */
/** @typedef MetaStructure */
/** @typedef NotFound */
/** @typedef Notification */
/** @typedef Page */
/** @typedef PayloadEmailProviderStructure */
/** @typedef PayloadEmailStructure */
/** @typedef PayloadEmailTemplateStructure */
/** @typedef PayloadSmsProviderStructure */
/** @typedef PayloadSmsStructure */
/** @typedef PayloadSmsTemplateStructure */
/** @typedef PayloadStructure */
/** @typedef PushtokenReq */
/** @typedef PushtokenRes */
/** @typedef RecipientHeaders */
/** @typedef SendOtpCommsReq */
/** @typedef SendOtpCommsReqData */
/** @typedef SendOtpCommsReqEmail */
/** @typedef SendOtpCommsReqSms */
/** @typedef SendOtpCommsRes */
/** @typedef SendOtpCommsResEmail */
/** @typedef SendOtpCommsResSms */
/** @typedef SendOtpEmailCommsTemplate */
/** @typedef SendOtpSmsCommsProvider */
/** @typedef SendOtpSmsCommsTemplate */
/** @typedef SmsProvider */
/** @typedef SmsProviderReq */
/** @typedef SmsProviders */
/** @typedef SmsTemplate */
/** @typedef SmsTemplateDeleteFailureRes */
/** @typedef SmsTemplateDeleteSuccessRes */
/** @typedef SmsTemplateMessage */
/** @typedef SmsTemplateReq */
/** @typedef SmsTemplateRes */
/** @typedef SmsTemplates */
/** @typedef Stats */
/** @typedef StatsImported */
/** @typedef StatsProcessed */
/** @typedef StatsProcessedEmail */
/** @typedef StatsProcessedSms */
/** @typedef SystemEmailTemplate */
/** @typedef SystemEmailTemplates */
/** @typedef SystemNotification */
/** @typedef SystemNotifications */
/** @typedef SystemNotificationSettings */
/** @typedef SystemNotificationsPage */
/** @typedef SystemNotificationUser */
/** @typedef SystemSmsTemplate */
/** @typedef SystemSmsTemplates */
/** @typedef TemplateAndType */
/** @typedef TriggerJobRequest */
/** @typedef TriggerJobResponse */
/** @typedef VerifyOtpCommsErrorRes */
/** @typedef VerifyOtpCommsReq */
/** @typedef VerifyOtpCommsSuccessRes */

/** @typedef AddBeneficiaryDetailsOTPRequest */
/** @typedef BankDetailsForOTP */
/** @typedef CODdata */
/** @typedef DeletePayoutResponse */
/** @typedef DeleteSubscriptionPaymentMethodResponse */
/** @typedef EdcAddRequest */
/** @typedef EdcAggregatorAndModelListResponse */
/** @typedef EdcDevice */
/** @typedef EdcDeviceAddResponse */
/** @typedef EdcDeviceDetailsResponse */
/** @typedef EdcDeviceListResponse */
/** @typedef EdcDeviceStatsResponse */
/** @typedef EdcDeviceUpdateResponse */
/** @typedef EdcModelData */
/** @typedef EdcUpdateRequest */
/** @typedef ErrorCodeAndDescription */
/** @typedef ErrorCodeDescription */
/** @typedef GetUserCODLimitResponse */
/** @typedef HttpErrorCodeAndResponse */
/** @typedef IfscCodeResponse */
/** @typedef IntentApp */
/** @typedef IntentAppErrorList */
/** @typedef LinkStatus */
/** @typedef MultiTenderPaymentMeta */
/** @typedef MultiTenderPaymentMethod */
/** @typedef NotFoundResourceError */
/** @typedef OrderBeneficiaryDetails */
/** @typedef OrderBeneficiaryResponse */
/** @typedef Page */
/** @typedef PaymentConfirmationRequest */
/** @typedef PaymentConfirmationResponse */
/** @typedef PaymentGatewayConfig */
/** @typedef PaymentGatewayConfigRequest */
/** @typedef PaymentGatewayConfigResponse */
/** @typedef PaymentGatewayToBeReviewed */
/** @typedef PaymentInitializationRequest */
/** @typedef PaymentInitializationResponse */
/** @typedef PaymentModeList */
/** @typedef PaymentModeLogo */
/** @typedef PaymentOptions */
/** @typedef PaymentOptionsResponse */
/** @typedef PaymentStatusUpdateRequest */
/** @typedef PaymentStatusUpdateResponse */
/** @typedef Payout */
/** @typedef PayoutAggregator */
/** @typedef PayoutBankDetails */
/** @typedef PayoutCustomer */
/** @typedef PayoutMoreAttributes */
/** @typedef PayoutRequest */
/** @typedef PayoutResponse */
/** @typedef PayoutsResponse */
/** @typedef PlatformPaymentOptions */
/** @typedef PlatfromPaymentConfig */
/** @typedef RefundAccountResponse */
/** @typedef ResendOrCancelPaymentRequest */
/** @typedef ResendOrCancelPaymentResponse */
/** @typedef RootPaymentMode */
/** @typedef SaveSubscriptionSetupIntentRequest */
/** @typedef SaveSubscriptionSetupIntentResponse */
/** @typedef SetCODForUserRequest */
/** @typedef SetCODOptionResponse */
/** @typedef StatisticsData */
/** @typedef SubscriptionConfigResponse */
/** @typedef SubscriptionPaymentMethodResponse */
/** @typedef UpdatePayoutRequest */
/** @typedef UpdatePayoutResponse */
/** @typedef UpdatePlatformPaymentConfig */

/** @typedef ActionInfo */
/** @typedef AdvanceFilterInfo */
/** @typedef Affiliate */
/** @typedef AffiliateAppConfig */
/** @typedef AffiliateAppConfigMeta */
/** @typedef AffiliateBag */
/** @typedef AffiliateBagDetails */
/** @typedef AffiliateConfig */
/** @typedef AffiliateDetails */
/** @typedef AffiliateInventoryArticleAssignmentConfig */
/** @typedef AffiliateInventoryConfig */
/** @typedef AffiliateInventoryLogisticsConfig */
/** @typedef AffiliateInventoryOrderConfig */
/** @typedef AffiliateInventoryPaymentConfig */
/** @typedef AffiliateInventoryStoreConfig */
/** @typedef AffiliateMeta */
/** @typedef AffiliateStoreIdMapping */
/** @typedef AnnouncementResponse */
/** @typedef AnnouncementsResponse */
/** @typedef AppliedPromos */
/** @typedef Article */
/** @typedef ArticleDetails */
/** @typedef ArticleDetails1 */
/** @typedef Attributes */
/** @typedef B2BPODetails */
/** @typedef BagConfigs */
/** @typedef BagDetailsPlatformResponse */
/** @typedef BagGST */
/** @typedef BagGSTDetails */
/** @typedef BagMeta */
/** @typedef BagReturnableCancelableStatus */
/** @typedef Bags */
/** @typedef BagsPage */
/** @typedef BagStateMapper */
/** @typedef BagStatusHistory */
/** @typedef BagUnit */
/** @typedef BaseResponse */
/** @typedef BillingInfo */
/** @typedef BillingStaffDetails */
/** @typedef Brand */
/** @typedef BulkActionDetailsDataField */
/** @typedef BulkActionDetailsResponse */
/** @typedef BulkActionPayload */
/** @typedef BulkActionResponse */
/** @typedef BulkInvoiceLabelResponse */
/** @typedef BulkInvoicingResponse */
/** @typedef bulkListingData */
/** @typedef BulkListingPage */
/** @typedef BulkListingResponse */
/** @typedef BuyerDetails */
/** @typedef BuyRules */
/** @typedef Charge */
/** @typedef CheckResponse */
/** @typedef Click2CallResponse */
/** @typedef CompanyDetails */
/** @typedef ContactDetails */
/** @typedef CreateChannelConfig */
/** @typedef CreateChannelConfigData */
/** @typedef CreateChannelConfigResponse */
/** @typedef CreateChannelConifgErrorResponse */
/** @typedef CreateChannelPaymentInfo */
/** @typedef CreateOrderAPI */
/** @typedef CreateOrderErrorReponse */
/** @typedef CreateOrderPayload */
/** @typedef CreateOrderResponse */
/** @typedef CurrentStatus */
/** @typedef DataUpdates */
/** @typedef Dates */
/** @typedef DebugInfo */
/** @typedef Dimensions */
/** @typedef DiscountRules */
/** @typedef DispatchManifest */
/** @typedef Document */
/** @typedef DpConfiguration */
/** @typedef DPDetailsData */
/** @typedef EinvoiceInfo */
/** @typedef EInvoicePortalDetails */
/** @typedef Entities */
/** @typedef EntitiesDataUpdates */
/** @typedef EntitiesReasons */
/** @typedef EntityReasonData */
/** @typedef Error */
/** @typedef ErrorDetail */
/** @typedef ErrorResponse */
/** @typedef ErrorResponse1 */
/** @typedef FileResponse */
/** @typedef FileUploadResponse */
/** @typedef FilterInfoOption */
/** @typedef FiltersInfo */
/** @typedef FiltersResponse */
/** @typedef FinancialBreakup */
/** @typedef Formatted */
/** @typedef FulfillingStore */
/** @typedef FyndOrderIdList */
/** @typedef GetActionsResponse */
/** @typedef GetBagsPlatformResponse */
/** @typedef GSTDetailsData */
/** @typedef HistoryDict */
/** @typedef Identifier */
/** @typedef InvalidateShipmentCacheNestedResponse */
/** @typedef InvalidateShipmentCachePayload */
/** @typedef InvalidateShipmentCacheResponse */
/** @typedef InvoiceInfo */
/** @typedef Item */
/** @typedef ItemCriterias */
/** @typedef JioCodeUpsertDataSet */
/** @typedef JioCodeUpsertPayload */
/** @typedef JioCodeUpsertResponse */
/** @typedef LaneConfigResponse */
/** @typedef LineItem */
/** @typedef LocationDetails */
/** @typedef LockData */
/** @typedef ManualAssignDPToShipment */
/** @typedef ManualAssignDPToShipmentResponse */
/** @typedef MarketPlacePdf */
/** @typedef Meta */
/** @typedef Meta1 */
/** @typedef MetricCountResponse */
/** @typedef MetricsCount */
/** @typedef NestedErrorSchemaDataSet */
/** @typedef OmsReports */
/** @typedef Options */
/** @typedef OrderBagArticle */
/** @typedef OrderBags */
/** @typedef OrderBrandName */
/** @typedef OrderConfig */
/** @typedef OrderDetails */
/** @typedef OrderDetailsData */
/** @typedef OrderDict */
/** @typedef OrderInfo */
/** @typedef OrderingStoreDetails */
/** @typedef OrderListingResponse */
/** @typedef OrderMeta */
/** @typedef OrderPriority */
/** @typedef OrderStatus */
/** @typedef OrderStatusData */
/** @typedef OrderStatusResult */
/** @typedef OrderUser */
/** @typedef OriginalFilter */
/** @typedef Page */
/** @typedef PaymentInfo */
/** @typedef PaymentMethod */
/** @typedef PaymentMethods */
/** @typedef PaymentModeInfo */
/** @typedef PDFLinks */
/** @typedef PhoneDetails */
/** @typedef PlatformBreakupValues */
/** @typedef PlatformChannel */
/** @typedef PlatformDeliveryAddress */
/** @typedef PlatformItem */
/** @typedef PlatformOrderItems */
/** @typedef PlatformOrderUpdate */
/** @typedef PlatformShipment */
/** @typedef PlatformShipmentReasonsResponse */
/** @typedef PlatformShipmentTrack */
/** @typedef PlatformTrack */
/** @typedef PlatformUserDetails */
/** @typedef PostActivityHistory */
/** @typedef PostHistoryData */
/** @typedef PostHistoryDict */
/** @typedef PostHistoryFilters */
/** @typedef PostShipmentHistory */
/** @typedef Prices */
/** @typedef ProcessingDates */
/** @typedef Products */
/** @typedef ProductsDataUpdates */
/** @typedef ProductsDataUpdatesFilters */
/** @typedef ProductsReasons */
/** @typedef ProductsReasonsData */
/** @typedef ProductsReasonsFilters */
/** @typedef QuestionSet */
/** @typedef Reason */
/** @typedef ReasonsData */
/** @typedef ResponseDetail */
/** @typedef ReturnConfig */
/** @typedef SendSmsPayload */
/** @typedef Shipment */
/** @typedef ShipmentConfig */
/** @typedef ShipmentData */
/** @typedef ShipmentDetail */
/** @typedef ShipmentDetails */
/** @typedef ShipmentDetailsResponse */
/** @typedef ShipmentHistoryResponse */
/** @typedef ShipmentInfoResponse */
/** @typedef ShipmentInternalPlatformViewResponse */
/** @typedef ShipmentItem */
/** @typedef ShipmentItemFulFillingStore */
/** @typedef ShipmentMeta */
/** @typedef ShipmentPayments */
/** @typedef ShipmentsRequest */
/** @typedef ShipmentsResponse */
/** @typedef ShipmentStatus */
/** @typedef ShipmentStatusData */
/** @typedef ShipmentTimeStamp */
/** @typedef ShippingInfo */
/** @typedef SmsDataPayload */
/** @typedef StatuesRequest */
/** @typedef StatuesResponse */
/** @typedef Store */
/** @typedef StoreAddress */
/** @typedef StoreDocuments */
/** @typedef StoreEinvoice */
/** @typedef StoreEwaybill */
/** @typedef StoreGstCredentials */
/** @typedef StoreMeta */
/** @typedef StoreReassign */
/** @typedef StoreReassignResponse */
/** @typedef SubLane */
/** @typedef Success */
/** @typedef SuccessResponse */
/** @typedef SuperLane */
/** @typedef Tax */
/** @typedef TaxDetails */
/** @typedef TaxInfo */
/** @typedef TrackingList */
/** @typedef TransactionData */
/** @typedef UpdateShipmentLockPayload */
/** @typedef UpdateShipmentLockResponse */
/** @typedef UpdateShipmentStatusRequest */
/** @typedef UpdateShipmentStatusResponseBody */
/** @typedef UploadConsent */
/** @typedef URL */
/** @typedef UserData */
/** @typedef UserDataInfo */
/** @typedef UserDetailsData */
/** @typedef Weight */

/** @typedef BrowseResponse */
/** @typedef BulkRequest */
/** @typedef BulkUploadResponse */
/** @typedef CDN */
/** @typedef CompleteResponse */
/** @typedef CopyFileTask */
/** @typedef DbRecord */
/** @typedef Destination */
/** @typedef FailedResponse */
/** @typedef Opts */
/** @typedef Page */
/** @typedef ReqConfiguration */
/** @typedef SignUrlRequest */
/** @typedef SignUrlResponse */
/** @typedef StartRequest */
/** @typedef StartResponse */
/** @typedef Upload */
/** @typedef Urls */

/** @typedef Attribution */
/** @typedef CampaignShortLink */
/** @typedef ErrorRes */
/** @typedef Page */
/** @typedef RedirectDevice */
/** @typedef Redirects */
/** @typedef ShortLinkList */
/** @typedef ShortLinkReq */
/** @typedef ShortLinkRes */
/** @typedef SocialMediaTags */
/** @typedef UrlInfo */
/** @typedef WebRedirect */

/** @typedef ArchiveConfig */
/** @typedef Audit */
/** @typedef AWSS3config */
/** @typedef CatalogMasterConfig */
/** @typedef CompanyConfig */
/** @typedef DataTresholdDTO */
/** @typedef DBConfig */
/** @typedef DBConnectionProfile */
/** @typedef DBParamConfig */
/** @typedef DefaultHeadersDTO */
/** @typedef DocMappingConfig */
/** @typedef EmailConfig */
/** @typedef FileConfig */
/** @typedef FTPConfig */
/** @typedef GCompany */
/** @typedef GenericDTO */
/** @typedef GoogleSpreadSheetConfig */
/** @typedef GStore */
/** @typedef HttpConfig */
/** @typedef JobConfig */
/** @typedef JobConfigDTO */
/** @typedef JobConfigListDTO */
/** @typedef JobConfigRawDTO */
/** @typedef JobHistoryDto */
/** @typedef JobMetricsDto */
/** @typedef JobStepsDTO */
/** @typedef JsonDocConfig */
/** @typedef KafkaMetaModel */
/** @typedef KafkaResponse */
/** @typedef LocalFileConfig */
/** @typedef Metum */
/** @typedef MongoDocConfig */
/** @typedef OAuthConfig */
/** @typedef Page */
/** @typedef ProcessConfig */
/** @typedef PropBeanConfig */
/** @typedef PropBeanDTO */
/** @typedef ResponseEnvelopeJobConfigDTO */
/** @typedef ResponseEnvelopeJobMetricsDto */
/** @typedef ResponseEnvelopeKafkaResponse */
/** @typedef ResponseEnvelopeListJobConfigDTO */
/** @typedef ResponseEnvelopeListJobConfigListDTO */
/** @typedef ResponseEnvelopeListJobConfigRawDTO */
/** @typedef ResponseEnvelopeListJobStepsDTO */
/** @typedef ResponseEnvelopeListSlingshotConfigurationDetail */
/** @typedef ResponseEnvelopeString */
/** @typedef Send */
/** @typedef SFTPConfig */
/** @typedef SlingshotConfigurationDetail */
/** @typedef SlingshotIntegration */
/** @typedef StoreConfig */
/** @typedef StoreData */
/** @typedef StoreFilter */
/** @typedef SuppressStoreModel */
/** @typedef SuppressStorePayload */
/** @typedef TaskConfig */
/** @typedef TaskDTO */
/** @typedef TaskParam */
/** @typedef TaskStepConfig */

/** @typedef Android */
/** @typedef App */
/** @typedef AppCartConfig */
/** @typedef AppCurrencyResponse */
/** @typedef AppDomain */
/** @typedef AppFeature */
/** @typedef AppFeatureRequest */
/** @typedef AppFeatureResponse */
/** @typedef AppInventory */
/** @typedef AppInventoryCompanies */
/** @typedef AppInventoryConfig */
/** @typedef AppInventoryPartialUpdate */
/** @typedef AppInventoryStores */
/** @typedef Application */
/** @typedef ApplicationAuth */
/** @typedef ApplicationCors */
/** @typedef ApplicationDetail */
/** @typedef ApplicationInformation */
/** @typedef ApplicationInventory */
/** @typedef ApplicationMeta */
/** @typedef ApplicationRedirections */
/** @typedef ApplicationsResponse */
/** @typedef ApplicationWebsite */
/** @typedef AppLogisticsConfig */
/** @typedef AppOrderConfig */
/** @typedef AppPaymentConfig */
/** @typedef AppStoreRules */
/** @typedef AppSupportedCurrency */
/** @typedef ArticleAssignmentConfig */
/** @typedef ArticleAssignmentRule */
/** @typedef ArticleAssignmentRules */
/** @typedef AuthenticationConfig */
/** @typedef BlogLink */
/** @typedef BrandCompanyInfo */
/** @typedef BrandsByCompanyResponse */
/** @typedef BrandStoreInfo */
/** @typedef BuildVersion */
/** @typedef BuildVersionHistory */
/** @typedef BusinessHighlights */
/** @typedef CallbackUrl */
/** @typedef CartFeature */
/** @typedef Charges */
/** @typedef CommonFeature */
/** @typedef CommsConfig */
/** @typedef CommunicationConfig */
/** @typedef CommunicationOptinDialogFeature */
/** @typedef CompaniesResponse */
/** @typedef CompanyAboutAddress */
/** @typedef CompanyBrandInfo */
/** @typedef CompanyByBrandsRequest */
/** @typedef CompanyByBrandsResponse */
/** @typedef CompanyValidator */
/** @typedef CompareProductsFeature */
/** @typedef CreateApplicationRequest */
/** @typedef CreateAppResponse */
/** @typedef Credentials */
/** @typedef Credit */
/** @typedef CurrenciesResponse */
/** @typedef Currency */
/** @typedef CurrencyConfig */
/** @typedef CurrencyFeature */
/** @typedef Debit */
/** @typedef DefaultCurrency */
/** @typedef DeliveryCharges */
/** @typedef DeploymentMeta */
/** @typedef DeploymentStoreSelectionFeature */
/** @typedef Domain */
/** @typedef DomainAdd */
/** @typedef DomainAddRequest */
/** @typedef DomainsResponse */
/** @typedef DomainStatus */
/** @typedef DomainStatusRequest */
/** @typedef DomainStatusResponse */
/** @typedef DomainSuggestion */
/** @typedef DomainSuggestionsRequest */
/** @typedef DomainSuggestionsResponse */
/** @typedef FacebookLink */
/** @typedef FeedbackFeature */
/** @typedef FilterOrderingStoreRequest */
/** @typedef Firebase */
/** @typedef Freshchat */
/** @typedef FreshchatCredentials */
/** @typedef FyndRewards */
/** @typedef FyndRewardsCredentials */
/** @typedef GetIntegrationsOptInsResponse */
/** @typedef GoogleMap */
/** @typedef GoogleMapCredentials */
/** @typedef GooglePlusLink */
/** @typedef Gtm */
/** @typedef GtmCredentials */
/** @typedef HomePageFeature */
/** @typedef InformationAddress */
/** @typedef InformationPhone */
/** @typedef InformationSupport */
/** @typedef InstagramLink */
/** @typedef Integration */
/** @typedef IntegrationConfigResponse */
/** @typedef IntegrationLevel */
/** @typedef IntegrationMeta */
/** @typedef IntegrationOptIn */
/** @typedef InvalidPayloadRequest */
/** @typedef InventoryArticleAssignment */
/** @typedef InventoryBrand */
/** @typedef InventoryBrandRule */
/** @typedef InventoryCategory */
/** @typedef InventoryDiscount */
/** @typedef InventoryPaymentConfig */
/** @typedef InventoryPrice */
/** @typedef InventoryStore */
/** @typedef InventoryStoreRule */
/** @typedef InventoryValidator */
/** @typedef Ios */
/** @typedef JsonSchema */
/** @typedef LandingImage */
/** @typedef LandingPageFeature */
/** @typedef LastPatch */
/** @typedef LaunchPage */
/** @typedef LinkedInLink */
/** @typedef Links */
/** @typedef ListingPriceFeature */
/** @typedef LoyaltyPointsConfig */
/** @typedef Methods */
/** @typedef MobileAppConfigRequest */
/** @typedef MobileAppConfiguration */
/** @typedef Moengage */
/** @typedef MoengageCredentials */
/** @typedef NotFound */
/** @typedef OptedApplicationResponse */
/** @typedef OptedCompany */
/** @typedef OptedInventory */
/** @typedef OptedStore */
/** @typedef OptedStoreAddress */
/** @typedef OptedStoreIntegration */
/** @typedef OptOutInventory */
/** @typedef OptType */
/** @typedef OrderFeature */
/** @typedef OrderingStore */
/** @typedef OrderingStoreConfig */
/** @typedef OrderingStores */
/** @typedef OrderingStoresResponse */
/** @typedef OrderValidator */
/** @typedef OtherEntity */
/** @typedef OtherEntityData */
/** @typedef OtherSellerApplication */
/** @typedef OtherSellerApplications */
/** @typedef OtherSellerCompany */
/** @typedef Page */
/** @typedef PanCardConfig */
/** @typedef PaymentModeConfig */
/** @typedef PaymentSelectionLock */
/** @typedef PcrFeature */
/** @typedef PinterestLink */
/** @typedef ProductDetailFeature */
/** @typedef QrFeature */
/** @typedef RegistrationPageFeature */
/** @typedef RevenueEngineFeature */
/** @typedef RewardPointsConfig */
/** @typedef Safetynet */
/** @typedef SafetynetCredentials */
/** @typedef SecureUrl */
/** @typedef Segment */
/** @typedef SegmentCredentials */
/** @typedef SocialLinks */
/** @typedef SplashImage */
/** @typedef StoreByBrandsRequest */
/** @typedef StoreByBrandsResponse */
/** @typedef StoreCriteriaRule */
/** @typedef StoreLatLong */
/** @typedef StorePriority */
/** @typedef StorePriorityRule */
/** @typedef StoresResponse */
/** @typedef StoreValidator */
/** @typedef SuccessMessageResponse */
/** @typedef TokenResponse */
/** @typedef Tokens */
/** @typedef TwitterLink */
/** @typedef UnhandledError */
/** @typedef UpdateDomain */
/** @typedef UpdateDomainTypeRequest */
/** @typedef UpdateIntegrationLevelRequest */
/** @typedef UserEmail */
/** @typedef UserPhoneNumber */
/** @typedef Validators */
/** @typedef VimeoLink */
/** @typedef YoutubeLink */

/** @typedef AbandonedCart */
/** @typedef AbandonedCartResponse */
/** @typedef ActionQuery */
/** @typedef ActivePromosResponse */
/** @typedef AddCartDetailResponse */
/** @typedef AddCartRequest */
/** @typedef AddProductCart */
/** @typedef AppliedFreeArticles */
/** @typedef AppliedPromotion */
/** @typedef ApplyCouponRequest */
/** @typedef ArticlePriceInfo */
/** @typedef BaseInfo */
/** @typedef BasePrice */
/** @typedef BulkBundleRestriction */
/** @typedef BuyRules */
/** @typedef CartBreakup */
/** @typedef CartCheckoutResponse */
/** @typedef CartCurrency */
/** @typedef CartDeliveryModesResponse */
/** @typedef CartDetailResponse */
/** @typedef CartItem */
/** @typedef CartItemCountResponse */
/** @typedef CartItemMeta */
/** @typedef CartList */
/** @typedef CartMetaMissingResponse */
/** @typedef CartMetaResponse */
/** @typedef CartProduct */
/** @typedef CartProductIdentifer */
/** @typedef CartProductInfo */
/** @typedef CartShipmentsResponse */
/** @typedef CategoryInfo */
/** @typedef CheckCart */
/** @typedef CompareObject */
/** @typedef Coupon */
/** @typedef CouponAction */
/** @typedef CouponAdd */
/** @typedef CouponAuthor */
/** @typedef CouponBreakup */
/** @typedef CouponDateMeta */
/** @typedef CouponPartialUpdate */
/** @typedef CouponSchedule */
/** @typedef CouponsResponse */
/** @typedef CouponUpdate */
/** @typedef CouponValidity */
/** @typedef DeleteAddressResponse */
/** @typedef DeleteCartDetailResponse */
/** @typedef DeleteCartRequest */
/** @typedef DiscountOffer */
/** @typedef DiscountRule */
/** @typedef DiscountRulesApp */
/** @typedef DisplayBreakup */
/** @typedef DisplayMeta */
/** @typedef DisplayMeta1 */
/** @typedef DisplayMetaDict */
/** @typedef Files */
/** @typedef FreeGiftItem */
/** @typedef GeoLocation */
/** @typedef GetCouponResponse */
/** @typedef GetShareCartLinkRequest */
/** @typedef GetShareCartLinkResponse */
/** @typedef Identifier */
/** @typedef ItemCriteria */
/** @typedef LoyaltyPoints */
/** @typedef MultiCartResponse */
/** @typedef MultiTenderPaymentMeta */
/** @typedef MultiTenderPaymentMethod */
/** @typedef NetQuantity */
/** @typedef OpenapiCartDetailsRequest */
/** @typedef OpenapiCartDetailsResponse */
/** @typedef OpenApiCartServiceabilityRequest */
/** @typedef OpenApiCartServiceabilityResponse */
/** @typedef OpenApiCheckoutResponse */
/** @typedef OpenApiErrorResponse */
/** @typedef OpenApiFiles */
/** @typedef OpenApiOrderItem */
/** @typedef OpenApiPlatformCheckoutReq */
/** @typedef OperationErrorResponse */
/** @typedef Ownership */
/** @typedef Ownership1 */
/** @typedef Ownership2 */
/** @typedef Page */
/** @typedef PageCoupon */
/** @typedef PaymentAllowValue */
/** @typedef PaymentAllowValue1 */
/** @typedef PaymentCouponValidate */
/** @typedef PaymentModes */
/** @typedef PaymentSelectionLock */
/** @typedef PickupStoreDetail */
/** @typedef PlatformAddress */
/** @typedef PlatformCartCheckoutDetailRequest */
/** @typedef PlatformCartMetaRequest */
/** @typedef PlatformGetAddressesResponse */
/** @typedef PlatformSelectCartAddressRequest */
/** @typedef PostOrder */
/** @typedef PostOrder1 */
/** @typedef PriceRange */
/** @typedef ProductAction */
/** @typedef ProductArticle */
/** @typedef ProductAvailability */
/** @typedef ProductAvailabilitySize */
/** @typedef ProductImage */
/** @typedef ProductPrice */
/** @typedef ProductPriceInfo */
/** @typedef PromiseFormatted */
/** @typedef PromiseTimestamp */
/** @typedef PromoMeta */
/** @typedef PromotionAction */
/** @typedef PromotionAdd */
/** @typedef PromotionAuthor */
/** @typedef PromotionDateMeta */
/** @typedef PromotionListItem */
/** @typedef PromotionPartialUpdate */
/** @typedef PromotionPaymentModes */
/** @typedef PromotionSchedule */
/** @typedef PromotionsResponse */
/** @typedef PromotionUpdate */
/** @typedef RawBreakup */
/** @typedef Restrictions */
/** @typedef Restrictions1 */
/** @typedef Rule */
/** @typedef RuleDefinition */
/** @typedef SaveAddressResponse */
/** @typedef SharedCart */
/** @typedef SharedCartDetails */
/** @typedef SharedCartResponse */
/** @typedef ShipmentPromise */
/** @typedef ShipmentResponse */
/** @typedef ShippingAddress */
/** @typedef StaffCheckout */
/** @typedef State */
/** @typedef StoreDetailsResponse */
/** @typedef SuccessMessage */
/** @typedef UpdateAddressResponse */
/** @typedef UpdateCartDetailResponse */
/** @typedef UpdateCartPaymentRequest */
/** @typedef UpdateCartRequest */
/** @typedef UpdateCartShipmentItem */
/** @typedef UpdateCartShipmentRequest */
/** @typedef UpdateProductCart */
/** @typedef UpdateUserCartMapping */
/** @typedef UserCartMappingResponse */
/** @typedef UserInfo */
/** @typedef UserRegistered */
/** @typedef UsesRemaining */
/** @typedef UsesRemaining1 */
/** @typedef UsesRestriction */
/** @typedef UsesRestriction1 */
/** @typedef Validation */
/** @typedef Validity */
/** @typedef Visibility */

/** @typedef AppUser */
/** @typedef Asset */
/** @typedef ConfigurationRequest */
/** @typedef ConfigurationRes */
/** @typedef E */
/** @typedef Giveaway */
/** @typedef GiveawayAudience */
/** @typedef GiveawayResponse */
/** @typedef HistoryRes */
/** @typedef Offer */
/** @typedef Page */
/** @typedef Points */
/** @typedef PointsHistory */
/** @typedef Referral */
/** @typedef RewardsAudience */
/** @typedef RewardsRule */
/** @typedef RewardUser */
/** @typedef Schedule */
/** @typedef SetConfigurationRes */
/** @typedef ShareMessages */
/** @typedef UserRes */

/** @typedef AbandonCartDetail */
/** @typedef AbandonCartsDetail */
/** @typedef AbandonCartsList */
/** @typedef ErrorRes */
/** @typedef ExportJobReq */
/** @typedef ExportJobRes */
/** @typedef ExportJobStatusRes */
/** @typedef GetLogsListReq */
/** @typedef GetLogsListRes */
/** @typedef LogInfo */
/** @typedef MkpLogsResp */
/** @typedef Page */
/** @typedef ReceivedAt */
/** @typedef SearchLogReq */
/** @typedef SearchLogRes */
/** @typedef StatGroup */
/** @typedef StatsGroupComponent */
/** @typedef StatsGroupComponents */
/** @typedef StatsGroups */
/** @typedef StatsRes */

/** @typedef AddProxyReq */
/** @typedef AddProxyResponse */
/** @typedef APIError */
/** @typedef RemoveProxyResponse */

/** @typedef Association */
/** @typedef AuthMeta */
/** @typedef EventConfig */
/** @typedef EventConfigBase */
/** @typedef EventConfigList */
/** @typedef EventConfigResponse */
/** @typedef EventPayload */
/** @typedef EventProcessedStatus */
/** @typedef Page */
/** @typedef SubscriberConfig */
/** @typedef SubscriberConfigList */
/** @typedef SubscriberEvent */
/** @typedef SubscriberResponse */

/** @typedef BadRequest */
/** @typedef CreateLogResponse */
/** @typedef DeviceInfo */
/** @typedef EntityObj */
/** @typedef EntityObject */
/** @typedef EntityTypeObj */
/** @typedef EntityTypesResponse */
/** @typedef InternalServerError */
/** @typedef Location */
/** @typedef LogDocs */
/** @typedef LogMetaObj */
/** @typedef LogSchemaResponse */
/** @typedef Modifier */
/** @typedef RequestBodyAuditLog */
/** @typedef ResourceNotFound */

module.exports = PlatformApplicationClient;
