const Lead = require("./Lead/LeadPlatformApplicationClient");

const Theme = require("./Theme/ThemePlatformApplicationClient");

const User = require("./User/UserPlatformApplicationClient");

const Content = require("./Content/ContentPlatformApplicationClient");

const Communication = require("./Communication/CommunicationPlatformApplicationClient");

const Payment = require("./Payment/PaymentPlatformApplicationClient");

const Order = require("./Order/OrderPlatformApplicationClient");

const Catalog = require("./Catalog/CatalogPlatformApplicationClient");

const FileStorage = require("./FileStorage/FileStoragePlatformApplicationClient");

const Share = require("./Share/SharePlatformApplicationClient");

const Configuration = require("./Configuration/ConfigurationPlatformApplicationClient");

const Cart = require("./Cart/CartPlatformApplicationClient");

const Rewards = require("./Rewards/RewardsPlatformApplicationClient");

const Partner = require("./Partner/PartnerPlatformApplicationClient");

const { FDKClientValidationError } = require("../common/FDKError");

class PlatformApplicationClient {
  constructor(applicationId, config) {
    this.config = config;
    this.companyId = config.companyId;
    this.applicationId = applicationId;

    this.lead = new Lead(config, applicationId);

    this.theme = new Theme(config, applicationId);

    this.user = new User(config, applicationId);

    this.content = new Content(config, applicationId);

    this.communication = new Communication(config, applicationId);

    this.payment = new Payment(config, applicationId);

    this.order = new Order(config, applicationId);

    this.catalog = new Catalog(config, applicationId);

    this.fileStorage = new FileStorage(config, applicationId);

    this.share = new Share(config, applicationId);

    this.configuration = new Configuration(config, applicationId);

    this.cart = new Cart(config, applicationId);

    this.rewards = new Rewards(config, applicationId);

    this.partner = new Partner(config, applicationId);
  }

  setExtraHeaders(header) {
    if (typeof header === "object") {
      this.config.extraHeaders.push(header);
    } else {
      throw new FDKClientValidationError("Context value should be an object");
    }
  }
}

/** @typedef Application */
/** @typedef ApplicationAuth */
/** @typedef ApplicationCors */
/** @typedef ApplicationMeta */
/** @typedef ApplicationRedirections */
/** @typedef ApplicationResponse */
/** @typedef ApplicationWebsite */
/** @typedef BadRequest */
/** @typedef Currency */
/** @typedef Domain */
/** @typedef LocationCountry */
/** @typedef LocationDefaultCurrency */
/** @typedef LocationDefaultLanguage */
/** @typedef Locations */
/** @typedef NotFound */
/** @typedef Page */
/** @typedef SecureUrl */

/** @typedef AddTicketPayload */
/** @typedef AgentChangePayload */
/** @typedef CategoryData */
/** @typedef CloseVideoRoomResponse */
/** @typedef CommunicationDetails */
/** @typedef CreateCustomFormPayload */
/** @typedef CreatedOn */
/** @typedef CreateVideoRoomPayload */
/** @typedef CreateVideoRoomResponse */
/** @typedef CustomForm */
/** @typedef CustomFormList */
/** @typedef CustomFormSubmissionPayload */
/** @typedef Debug */
/** @typedef EditCustomFormPayload */
/** @typedef EditTicketPayload */
/** @typedef Email */
/** @typedef FeedbackForm */
/** @typedef FeedbackResponseItem */
/** @typedef Filter */
/** @typedef GetParticipantsInsideVideoRoomResponse */
/** @typedef GetTokenForVideoRoomResponse */
/** @typedef IntegrationConfig */
/** @typedef NotifyUser */
/** @typedef Page */
/** @typedef Participant */
/** @typedef PhoneNumber */
/** @typedef PollForAssignment */
/** @typedef Priority */
/** @typedef Status */
/** @typedef SubmitButton */
/** @typedef SubmitCustomFormResponse */
/** @typedef SupportGeneralConfig */
/** @typedef Ticket */
/** @typedef TicketAsset */
/** @typedef TicketCategory */
/** @typedef TicketContent */
/** @typedef TicketContext */
/** @typedef TicketFeedback */
/** @typedef TicketFeedbackForm */
/** @typedef TicketFeedbackList */
/** @typedef TicketFeedbackPayload */
/** @typedef TicketHistory */
/** @typedef TicketHistoryList */
/** @typedef TicketHistoryPayload */
/** @typedef TicketList */
/** @typedef TicketSubCategory */
/** @typedef UserSchema */

/** @typedef AddThemeRequestSchema */
/** @typedef AllAvailablePageSchema */
/** @typedef AssetsSchema */
/** @typedef AvailablePagePredicate */
/** @typedef AvailablePageRoutePredicate */
/** @typedef AvailablePageSchema */
/** @typedef AvailablePageSchemaSections */
/** @typedef AvailablePageScreenPredicate */
/** @typedef AvailablePageSectionMetaAttributes */
/** @typedef AvailablePageSeo */
/** @typedef AvailablePageUserPredicate */
/** @typedef availableSectionSchema */
/** @typedef BlitzkriegApiErrorSchema */
/** @typedef BlitzkriegInternalServerErrorSchema */
/** @typedef BlitzkriegNotFoundSchema */
/** @typedef Blocks */
/** @typedef BlocksProps */
/** @typedef Bold */
/** @typedef Colors */
/** @typedef CommonJs */
/** @typedef Config */
/** @typedef ConfigPage */
/** @typedef Css */
/** @typedef Custom */
/** @typedef Font */
/** @typedef FontsSchema */
/** @typedef FontsSchemaItems */
/** @typedef FontsSchemaItemsFiles */
/** @typedef GlobalSchema */
/** @typedef GlobalSchemaProps */
/** @typedef Images */
/** @typedef Information */
/** @typedef Light */
/** @typedef ListSchemaItem */
/** @typedef Medium */
/** @typedef PaginationSchema */
/** @typedef Preset */
/** @typedef Regular */
/** @typedef Sections */
/** @typedef SemiBold */
/** @typedef Src */
/** @typedef ThemesListingResponseSchema */
/** @typedef ThemesSchema */
/** @typedef UmdJs */
/** @typedef UpgradableThemeSchema */
/** @typedef Variants */

/** @typedef Accountkit */
/** @typedef ArchiveUserRequestSchema */
/** @typedef ArchiveUserSuccess */
/** @typedef AuthenticationApiErrorSchema */
/** @typedef AuthenticationInternalServerErrorSchema */
/** @typedef AuthSuccess */
/** @typedef AuthSuccessUser */
/** @typedef AuthSuccessUserDebug */
/** @typedef AuthSuccessUserEmails */
/** @typedef BlockUserRequestSchema */
/** @typedef BlockUserSuccess */
/** @typedef CodeRequestBodySchema */
/** @typedef CreateUserGroupSchema */
/** @typedef CreateUserRequestSchema */
/** @typedef CreateUserResponseSchema */
/** @typedef CreateUserSessionRequestSchema */
/** @typedef CreateUserSessionResponseSchema */
/** @typedef CustomerListResponseSchema */
/** @typedef DeleteAccountConsent */
/** @typedef DeleteAccountReasons */
/** @typedef DeleteApplicationUserRequestSchema */
/** @typedef DeleteUserSuccess */
/** @typedef EditEmailRequestSchema */
/** @typedef EditMobileRequestSchema */
/** @typedef EditProfileMobileSchema */
/** @typedef EditProfileRequestSchema */
/** @typedef Email */
/** @typedef EmailOtpSuccess */
/** @typedef Facebook */
/** @typedef FlashCard */
/** @typedef ForgotPasswordRequestSchema */
/** @typedef FormRegisterRequestSchema */
/** @typedef FormRegisterRequestSchemaPhone */
/** @typedef Google */
/** @typedef HasPasswordSuccess */
/** @typedef Login */
/** @typedef LoginSuccess */
/** @typedef LogoutSuccess */
/** @typedef LookAndFeel */
/** @typedef MetaSchema */
/** @typedef NotFoundSchema */
/** @typedef OAuthRequestAppleSchema */
/** @typedef OAuthRequestAppleSchemaOauth */
/** @typedef OAuthRequestAppleSchemaProfile */
/** @typedef OAuthRequestSchema */
/** @typedef OAuthRequestSchemaOauth2 */
/** @typedef OAuthRequestSchemaProfile */
/** @typedef OtpSuccess */
/** @typedef PaginationSchema */
/** @typedef PasswordLoginRequestSchema */
/** @typedef PhoneNumber */
/** @typedef PlatformEmail */
/** @typedef PlatformMobile */
/** @typedef PlatformSchema */
/** @typedef ProfileEditSuccess */
/** @typedef ProfileEditSuccessSchema */
/** @typedef RegisterFormSuccess */
/** @typedef RegisterRequiredFields */
/** @typedef RegisterRequiredFieldsEmail */
/** @typedef RegisterRequiredFieldsMobile */
/** @typedef RequiredFields */
/** @typedef ResetPasswordSuccess */
/** @typedef SendEmailOtpRequestSchema */
/** @typedef SendEmailVerifyLinkSuccess */
/** @typedef SendMobileOtpRequestSchema */
/** @typedef SendMobileVerifyLinkSuccess */
/** @typedef SendOtpRequestSchema */
/** @typedef SendOtpResponse */
/** @typedef SendResetPasswordEmailRequestSchema */
/** @typedef SendResetPasswordMobileRequestSchema */
/** @typedef SendVerificationLinkMobileRequestSchema */
/** @typedef SessionDeleteResponseSchema */
/** @typedef SessionExpiry */
/** @typedef SessionListResponseInfo */
/** @typedef SessionListResponseSchema */
/** @typedef SessionListSuccess */
/** @typedef Social */
/** @typedef SocialTokens */
/** @typedef TokenRequestBodySchema */
/** @typedef UnauthenticatedSchema */
/** @typedef UnauthorizedSchema */
/** @typedef UnDeleteUserRequestSchema */
/** @typedef UnDeleteUserSuccess */
/** @typedef UpdatePasswordRequestSchema */
/** @typedef UpdateUserGroupSchema */
/** @typedef UpdateUserRequestSchema */
/** @typedef UserEmails */
/** @typedef UserGroupListResponseSchema */
/** @typedef UserGroupResponseSchema */
/** @typedef UserObjectSchema */
/** @typedef UserPhoneNumbers */
/** @typedef UserSchema */
/** @typedef UserSearchResponseSchema */
/** @typedef VerifyEmailOtpRequestSchema */
/** @typedef VerifyEmailOTPSuccess */
/** @typedef VerifyEmailSuccess */
/** @typedef VerifyMobileOTPSuccess */
/** @typedef VerifyOtpRequestSchema */
/** @typedef VerifyOtpSuccess */

/** @typedef Action */
/** @typedef ActionPage */
/** @typedef AdminAnnouncementSchema */
/** @typedef AnnouncementAuthorSchema */
/** @typedef AnnouncementPageSchema */
/** @typedef AnnouncementSchema */
/** @typedef AnnouncementsResponseSchema */
/** @typedef ApplicationLegal */
/** @typedef ApplicationLegalFAQ */
/** @typedef Asset */
/** @typedef Author */
/** @typedef BlogGetResponse */
/** @typedef BlogRequest */
/** @typedef BlogSchema */
/** @typedef CategoryRequestSchema */
/** @typedef CategorySchema */
/** @typedef ChildrenSchema */
/** @typedef CommonError */
/** @typedef ConfigurationSchema */
/** @typedef ContactSchema */
/** @typedef ContentAPIError */
/** @typedef ContentSchema */
/** @typedef CreateAnnouncementSchema */
/** @typedef CreatedBySchema */
/** @typedef CreateFaqCategoryRequestSchema */
/** @typedef CreateFaqCategorySchema */
/** @typedef CreateFaqResponseSchema */
/** @typedef CreateFaqSchema */
/** @typedef CreateTagRequestSchema */
/** @typedef CreateTagSchema */
/** @typedef CronSchedule */
/** @typedef CustomMetaTag */
/** @typedef CustomPage */
/** @typedef CustomPageSchema */
/** @typedef DataLoaderResetResponseSchema */
/** @typedef DataLoaderResponseSchema */
/** @typedef DataLoaderSchema */
/** @typedef DataLoaderSourceSchema */
/** @typedef DataLoadersSchema */
/** @typedef DateMeta */
/** @typedef DefaultNavigationResponse */
/** @typedef Detail */
/** @typedef EditorMeta */
/** @typedef EmailProperties */
/** @typedef EmailSchema */
/** @typedef FAQ */
/** @typedef FAQCategorySchema */
/** @typedef FaqResponseSchema */
/** @typedef FaqSchema */
/** @typedef FeatureImage */
/** @typedef GeneratedSEOContent */
/** @typedef GenerateSEOContent */
/** @typedef GetAnnouncementListSchema */
/** @typedef GetFaqCategoriesSchema */
/** @typedef GetFaqCategoryBySlugSchema */
/** @typedef GetFaqSchema */
/** @typedef HandpickedTagSchema */
/** @typedef LandingPage */
/** @typedef LandingPageGetResponse */
/** @typedef LandingPageSchema */
/** @typedef Language */
/** @typedef LocaleLanguage */
/** @typedef Navigation */
/** @typedef NavigationGetResponse */
/** @typedef NavigationReference */
/** @typedef NavigationRequest */
/** @typedef NavigationSchema */
/** @typedef NextSchedule */
/** @typedef Orientation */
/** @typedef Page */
/** @typedef PageContent */
/** @typedef PageGetResponse */
/** @typedef PageMeta */
/** @typedef PageMetaSchema */
/** @typedef PagePublishRequest */
/** @typedef PageRequest */
/** @typedef PageSchema */
/** @typedef PageSpec */
/** @typedef PageSpecItem */
/** @typedef PageSpecParam */
/** @typedef PathMappingSchema */
/** @typedef PathSourceSchema */
/** @typedef PhoneProperties */
/** @typedef PhoneSchema */
/** @typedef RemoveHandpickedSchema */
/** @typedef ResourceContent */
/** @typedef ScheduleSchema */
/** @typedef ScheduleStartSchema */
/** @typedef SEO */
/** @typedef SeoComponent */
/** @typedef SEOImage */
/** @typedef SeoSchema */
/** @typedef Slideshow */
/** @typedef SlideshowGetResponse */
/** @typedef SlideshowMedia */
/** @typedef SlideshowRequest */
/** @typedef SlideshowSchema */
/** @typedef Support */
/** @typedef TagDeleteSuccessResponse */
/** @typedef TagSchema */
/** @typedef TagSourceSchema */
/** @typedef TagsSchema */
/** @typedef UpdateFaqCategoryRequestSchema */
/** @typedef UpdateHandpickedSchema */

/** @typedef BadRequest */
/** @typedef CancelSubscriptionReq */
/** @typedef CancelSubscriptionRes */
/** @typedef ChargeLineItem */
/** @typedef CheckValidityResponse */
/** @typedef CreateOneTimeCharge */
/** @typedef CreateOneTimeChargeResponse */
/** @typedef CreateSubscriptionCharge */
/** @typedef CreateSubscriptionResponse */
/** @typedef CurrentPeriod */
/** @typedef DetailedPlan */
/** @typedef DetailedPlanComponents */
/** @typedef EntityChargePrice */
/** @typedef EntityChargeRecurring */
/** @typedef EntitySubscription */
/** @typedef InternalServerError */
/** @typedef Invoice */
/** @typedef InvoiceDetails */
/** @typedef InvoiceDetailsClient */
/** @typedef InvoiceDetailsPaymentMethods */
/** @typedef InvoiceDetailsPaymentMethodsData */
/** @typedef InvoiceDetailsPaymentMethodsDataChecks */
/** @typedef InvoiceDetailsPaymentMethodsDataNetworks */
/** @typedef InvoiceDetailsPaymentMethodsDataThreeDSecureUsage */
/** @typedef InvoiceDetailsPeriod */
/** @typedef InvoiceDetailsStatusTrail */
/** @typedef InvoiceItems */
/** @typedef InvoiceItemsPeriod */
/** @typedef InvoiceItemsPlan */
/** @typedef InvoiceItemsPlanRecurring */
/** @typedef InvoicePaymentMethod */
/** @typedef Invoices */
/** @typedef InvoicesData */
/** @typedef InvoicesDataClient */
/** @typedef InvoicesDataPaymentMethod */
/** @typedef InvoicesDataPeriod */
/** @typedef OneTimeChargeEntity */
/** @typedef OneTimeChargeItem */
/** @typedef Page */
/** @typedef Phone */
/** @typedef Plan */
/** @typedef PlanRecurring */
/** @typedef ResourceNotFound */
/** @typedef Subscription */
/** @typedef SubscriptionActivateReq */
/** @typedef SubscriptionActivateRes */
/** @typedef SubscriptionBillingAddress */
/** @typedef SubscriptionCharge */
/** @typedef SubscriptionCurrentPeriod */
/** @typedef SubscriptionCustomer */
/** @typedef SubscriptionCustomerCreate */
/** @typedef SubscriptionInvoiceSettings */
/** @typedef SubscriptionLimit */
/** @typedef SubscriptionLimitApplication */
/** @typedef SubscriptionLimitExtensions */
/** @typedef SubscriptionLimitIntegrations */
/** @typedef SubscriptionLimitMarketplace */
/** @typedef SubscriptionLimitOtherPlatform */
/** @typedef SubscriptionLimitProducts */
/** @typedef SubscriptionLimitTeam */
/** @typedef SubscriptionPauseCollection */
/** @typedef SubscriptionStatus */
/** @typedef SubscriptionTrial */
/** @typedef SubscriptionTrialPeriod */
/** @typedef UnauthenticatedApplication */
/** @typedef UnauthenticatedUser */

/** @typedef Audience */
/** @typedef AudienceReq */
/** @typedef Audiences */
/** @typedef BadRequestSchema */
/** @typedef BigqueryHeadersReq */
/** @typedef BigqueryHeadersRes */
/** @typedef BigqueryHeadersResHeaders */
/** @typedef Campaign */
/** @typedef CampaignEmail */
/** @typedef CampaignEmailTemplate */
/** @typedef CampaignReq */
/** @typedef Campaigns */
/** @typedef CampignEmailProvider */
/** @typedef EmailProvider */
/** @typedef EmailProviderReq */
/** @typedef EmailProviderReqFrom */
/** @typedef EmailProviders */
/** @typedef EmailTemplate */
/** @typedef EmailTemplateDeleteFailureRes */
/** @typedef EmailTemplateDeleteSuccessRes */
/** @typedef EmailTemplateHeaders */
/** @typedef EmailTemplateKeys */
/** @typedef EmailTemplateReq */
/** @typedef EmailTemplateRes */
/** @typedef EmailTemplates */
/** @typedef EngineRequest */
/** @typedef EngineResponse */
/** @typedef EventSubscription */
/** @typedef EventSubscriptions */
/** @typedef EventSubscriptionTemplate */
/** @typedef EventSubscriptionTemplateEmail */
/** @typedef EventSubscriptionTemplateSms */
/** @typedef GetNRecordsCsvReq */
/** @typedef GetNRecordsCsvRes */
/** @typedef GetNRecordsCsvResItems */
/** @typedef GetStats */
/** @typedef Job */
/** @typedef JobLog */
/** @typedef JobLogs */
/** @typedef Jobs */
/** @typedef Log */
/** @typedef LogEmail */
/** @typedef LogMeta */
/** @typedef LogPushnotification */
/** @typedef Logs */
/** @typedef MetaStructure */
/** @typedef NotFound */
/** @typedef Notification */
/** @typedef Page */
/** @typedef PayloadEmailProviderStructure */
/** @typedef PayloadEmailStructure */
/** @typedef PayloadEmailTemplateStructure */
/** @typedef PayloadSmsProviderStructure */
/** @typedef PayloadSmsStructure */
/** @typedef PayloadSmsTemplateStructure */
/** @typedef PayloadStructure */
/** @typedef PushtokenReq */
/** @typedef PushtokenRes */
/** @typedef RecipientHeaders */
/** @typedef SendOtpCommsReq */
/** @typedef SendOtpCommsReqData */
/** @typedef SendOtpCommsReqEmail */
/** @typedef SendOtpCommsReqSms */
/** @typedef SendOtpCommsRes */
/** @typedef SendOtpCommsResEmail */
/** @typedef SendOtpCommsResSms */
/** @typedef SendOtpEmailCommsTemplate */
/** @typedef SendOtpSmsCommsProvider */
/** @typedef SendOtpSmsCommsTemplate */
/** @typedef SmsProvider */
/** @typedef SmsProviderReq */
/** @typedef SmsProviders */
/** @typedef SmsTemplate */
/** @typedef SmsTemplateDeleteFailureRes */
/** @typedef SmsTemplateDeleteSuccessRes */
/** @typedef SmsTemplateMessage */
/** @typedef SmsTemplateReq */
/** @typedef SmsTemplateRes */
/** @typedef SmsTemplates */
/** @typedef Stats */
/** @typedef StatsImported */
/** @typedef StatsProcessed */
/** @typedef StatsProcessedEmail */
/** @typedef StatsProcessedSms */
/** @typedef SystemEmailTemplate */
/** @typedef SystemEmailTemplates */
/** @typedef SystemNotification */
/** @typedef SystemNotifications */
/** @typedef SystemNotificationSettings */
/** @typedef SystemNotificationsPage */
/** @typedef SystemNotificationUser */
/** @typedef SystemSmsTemplate */
/** @typedef SystemSmsTemplates */
/** @typedef TemplateAndType */
/** @typedef TriggerJobRequest */
/** @typedef TriggerJobResponse */
/** @typedef VerifyOtpCommsErrorRes */
/** @typedef VerifyOtpCommsReq */
/** @typedef VerifyOtpCommsSuccessRes */

/** @typedef AddBeneficiaryDetailsOTPRequest */
/** @typedef BankDetailsForOTP */
/** @typedef CODdata */
/** @typedef DeletePayoutResponse */
/** @typedef DeleteSubscriptionPaymentMethodResponse */
/** @typedef ErrorCodeAndDescription */
/** @typedef ErrorCodeDescription */
/** @typedef GetOauthUrlResponse */
/** @typedef GetUserCODLimitResponse */
/** @typedef HttpErrorCodeAndResponse */
/** @typedef IfscCodeResponse */
/** @typedef IntentApp */
/** @typedef IntentAppErrorList */
/** @typedef MultiTenderPaymentMeta */
/** @typedef MultiTenderPaymentMethod */
/** @typedef NotFoundResourceError */
/** @typedef OrderBeneficiaryDetails */
/** @typedef OrderBeneficiaryResponse */
/** @typedef PaymentConfirmationRequest */
/** @typedef PaymentConfirmationResponse */
/** @typedef PaymentGatewayConfig */
/** @typedef PaymentGatewayConfigRequest */
/** @typedef PaymentGatewayConfigResponse */
/** @typedef PaymentGatewayToBeReviewed */
/** @typedef PaymentModeList */
/** @typedef PaymentModeLogo */
/** @typedef PaymentOptions */
/** @typedef PaymentOptionsResponse */
/** @typedef PayoutBankDetails */
/** @typedef PayoutRequest */
/** @typedef PayoutResponse */
/** @typedef PayoutsResponse */
/** @typedef RefundAccountResponse */
/** @typedef RevokeOAuthToken */
/** @typedef RootPaymentMode */
/** @typedef SaveSubscriptionSetupIntentRequest */
/** @typedef SaveSubscriptionSetupIntentResponse */
/** @typedef SetCODForUserRequest */
/** @typedef SetCODOptionResponse */
/** @typedef SubscriptionConfigResponse */
/** @typedef SubscriptionPaymentMethodResponse */
/** @typedef UpdatePayoutRequest */
/** @typedef UpdatePayoutResponse */

/** @typedef ActionInfo */
/** @typedef AdvanceFilterInfo */
/** @typedef Affiliate */
/** @typedef AffiliateAppConfig */
/** @typedef AffiliateAppConfigMeta */
/** @typedef AffiliateBag */
/** @typedef AffiliateBagDetails */
/** @typedef AffiliateBagsDetails */
/** @typedef AffiliateConfig */
/** @typedef AffiliateDetails */
/** @typedef AffiliateInventoryArticleAssignmentConfig */
/** @typedef AffiliateInventoryConfig */
/** @typedef AffiliateInventoryLogisticsConfig */
/** @typedef AffiliateInventoryOrderConfig */
/** @typedef AffiliateInventoryPaymentConfig */
/** @typedef AffiliateInventoryStoreConfig */
/** @typedef AffiliateMeta */
/** @typedef AffiliateStoreIdMapping */
/** @typedef AnnouncementResponse */
/** @typedef AnnouncementsResponse */
/** @typedef AppliedPromos */
/** @typedef Article */
/** @typedef ArticleDetails */
/** @typedef ArticleDetails1 */
/** @typedef Attributes */
/** @typedef B2BPODetails */
/** @typedef BagConfigs */
/** @typedef BagDetailsPlatformResponse */
/** @typedef BagGST */
/** @typedef BagGSTDetails */
/** @typedef BagMeta */
/** @typedef BagReturnableCancelableStatus */
/** @typedef BagReturnableCancelableStatus1 */
/** @typedef Bags */
/** @typedef BagsPage */
/** @typedef BagStateMapper */
/** @typedef BagStateTransitionMap */
/** @typedef BagStatusHistory */
/** @typedef BagUnit */
/** @typedef BaseResponse */
/** @typedef BillingInfo */
/** @typedef BillingStaffDetails */
/** @typedef Brand */
/** @typedef BulkActionTemplate */
/** @typedef BulkActionTemplateResponse */
/** @typedef BuyerDetails */
/** @typedef BuyRules */
/** @typedef Charge */
/** @typedef CheckResponse */
/** @typedef Click2CallResponse */
/** @typedef CompanyDetails */
/** @typedef ContactDetails */
/** @typedef CreateChannelConfig */
/** @typedef CreateChannelConfigData */
/** @typedef CreateChannelConfigResponse */
/** @typedef CreateChannelConifgErrorResponse */
/** @typedef CreateChannelPaymentInfo */
/** @typedef CreateOrderAPI */
/** @typedef CreateOrderErrorReponse */
/** @typedef CreateOrderPayload */
/** @typedef CreateOrderResponse */
/** @typedef CurrentStatus */
/** @typedef DataUpdates */
/** @typedef Dates */
/** @typedef DebugInfo */
/** @typedef Dimension */
/** @typedef Dimensions */
/** @typedef DiscountRules */
/** @typedef DispatchManifest */
/** @typedef Document */
/** @typedef DpConfiguration */
/** @typedef DPDetailsData */
/** @typedef EinvoiceInfo */
/** @typedef EInvoicePortalDetails */
/** @typedef Entities */
/** @typedef EntitiesDataUpdates */
/** @typedef EntitiesReasons */
/** @typedef EntityReasonData */
/** @typedef Error */
/** @typedef ErrorDetail */
/** @typedef ErrorResponse */
/** @typedef ErrorResponse1 */
/** @typedef FileResponse */
/** @typedef FilterInfoOption */
/** @typedef FiltersInfo */
/** @typedef FiltersResponse */
/** @typedef FinancialBreakup */
/** @typedef Formatted */
/** @typedef FulfillingStore */
/** @typedef FyndOrderIdList */
/** @typedef GetActionsResponse */
/** @typedef GetBagsPlatformResponse */
/** @typedef GiftCard */
/** @typedef GSTDetailsData */
/** @typedef HistoryDict */
/** @typedef HistoryMeta */
/** @typedef HistoryReason */
/** @typedef Identifier */
/** @typedef InvalidateShipmentCacheNestedResponse */
/** @typedef InvalidateShipmentCachePayload */
/** @typedef InvalidateShipmentCacheResponse */
/** @typedef InvoiceInfo */
/** @typedef Item */
/** @typedef ItemCriterias */
/** @typedef LaneConfigResponse */
/** @typedef LineItem */
/** @typedef LocationDetails */
/** @typedef LockData */
/** @typedef MarketPlacePdf */
/** @typedef Meta */
/** @typedef OrderBagArticle */
/** @typedef OrderBags */
/** @typedef OrderBrandName */
/** @typedef OrderConfig */
/** @typedef OrderData */
/** @typedef OrderDetails */
/** @typedef OrderDetailsData */
/** @typedef OrderDetailsResponse */
/** @typedef OrderInfo */
/** @typedef OrderingStoreDetails */
/** @typedef OrderListingResponse */
/** @typedef OrderMeta */
/** @typedef OrderPriority */
/** @typedef OrderStatus */
/** @typedef OrderStatusData */
/** @typedef OrderStatusResult */
/** @typedef OrderUser */
/** @typedef OriginalFilter */
/** @typedef Page */
/** @typedef PaymentInfo */
/** @typedef PaymentMethod */
/** @typedef PaymentMethods */
/** @typedef PDFLinks */
/** @typedef PhoneDetails */
/** @typedef PlatformArticleAttributes */
/** @typedef PlatformBreakupValues */
/** @typedef PlatformChannel */
/** @typedef PlatformDeliveryAddress */
/** @typedef PlatformItem */
/** @typedef PlatformOrderItems */
/** @typedef PlatformOrderUpdate */
/** @typedef PlatformShipment */
/** @typedef PlatformShipmentReasonsResponse */
/** @typedef PlatformShipmentTrack */
/** @typedef PlatformTrack */
/** @typedef PlatformUserDetails */
/** @typedef PostActivityHistory */
/** @typedef PostHistoryData */
/** @typedef PostHistoryDict */
/** @typedef PostHistoryFilters */
/** @typedef PostShipmentHistory */
/** @typedef Prices */
/** @typedef ProcessingDates */
/** @typedef Products */
/** @typedef ProductsDataUpdates */
/** @typedef ProductsDataUpdatesFilters */
/** @typedef ProductsReasons */
/** @typedef ProductsReasonsData */
/** @typedef ProductsReasonsFilters */
/** @typedef QuestionSet */
/** @typedef Reason */
/** @typedef ReasonsData */
/** @typedef ReplacementDetails */
/** @typedef ResponseDetail */
/** @typedef ReturnConfig */
/** @typedef ReturnConfig1 */
/** @typedef SendSmsPayload */
/** @typedef Shipment */
/** @typedef ShipmentConfig */
/** @typedef ShipmentData */
/** @typedef ShipmentDetail */
/** @typedef ShipmentDetails */
/** @typedef ShipmentDetails1 */
/** @typedef ShipmentHistoryResponse */
/** @typedef ShipmentInfoResponse */
/** @typedef ShipmentInternalPlatformViewResponse */
/** @typedef ShipmentItem */
/** @typedef ShipmentItemFulFillingStore */
/** @typedef ShipmentItemMeta */
/** @typedef ShipmentListingBrand */
/** @typedef ShipmentListingChannel */
/** @typedef ShipmentMeta */
/** @typedef ShipmentPayments */
/** @typedef ShipmentReasonsResponse */
/** @typedef ShipmentResponseReasons */
/** @typedef ShipmentsRequest */
/** @typedef ShipmentsResponse */
/** @typedef ShipmentStatus */
/** @typedef ShipmentStatusData */
/** @typedef ShipmentTags */
/** @typedef ShipmentTimeStamp */
/** @typedef ShippingInfo */
/** @typedef SmsDataPayload */
/** @typedef StatuesRequest */
/** @typedef StatuesResponse */
/** @typedef Store */
/** @typedef StoreAddress */
/** @typedef StoreDocuments */
/** @typedef StoreEinvoice */
/** @typedef StoreEwaybill */
/** @typedef StoreGstCredentials */
/** @typedef StoreMeta */
/** @typedef StoreReassign */
/** @typedef StoreReassignResponse */
/** @typedef SubLane */
/** @typedef SuccessResponse */
/** @typedef SuperLane */
/** @typedef Tax */
/** @typedef TaxDetails */
/** @typedef TaxInfo */
/** @typedef TrackingList */
/** @typedef TransactionData */
/** @typedef UpdatePackagingDimensionsPayload */
/** @typedef UpdatePackagingDimensionsResponse */
/** @typedef UpdateShipmentLockPayload */
/** @typedef UpdateShipmentLockResponse */
/** @typedef UpdateShipmentStatusRequest */
/** @typedef UpdateShipmentStatusResponseBody */
/** @typedef UploadConsent */
/** @typedef URL */
/** @typedef UserData */
/** @typedef UserDataInfo */
/** @typedef UserDetailsData */
/** @typedef Weight */

/** @typedef Action */
/** @typedef ActionPage */
/** @typedef AllowSingleRequest */
/** @typedef AllSizes */
/** @typedef AppCatalogConfiguration */
/** @typedef AppConfiguration */
/** @typedef AppConfigurationDetail */
/** @typedef AppConfigurationsSort */
/** @typedef ApplicationBrandJson */
/** @typedef ApplicationCategoryJson */
/** @typedef ApplicationDepartment */
/** @typedef ApplicationDepartmentJson */
/** @typedef ApplicationDepartmentListingResponse */
/** @typedef ApplicationItemMeta */
/** @typedef ApplicationItemMOQ */
/** @typedef ApplicationItemSEO */
/** @typedef ApplicationProductListingResponse */
/** @typedef ApplicationStoreJson */
/** @typedef ArticleAssignment */
/** @typedef ArticleAssignment1 */
/** @typedef ArticleQuery */
/** @typedef ArticleStoreResponse */
/** @typedef AssignStore */
/** @typedef AssignStoreArticle */
/** @typedef AttributeDetailsGroup */
/** @typedef AttributeMaster */
/** @typedef AttributeMasterDetails */
/** @typedef AttributeMasterFilter */
/** @typedef AttributeMasterMandatoryDetails */
/** @typedef AttributeMasterMeta */
/** @typedef AttributeMasterSerializer */
/** @typedef AttributeSchemaRange */
/** @typedef AutocompleteAction */
/** @typedef AutoCompleteMedia */
/** @typedef AutocompletePageAction */
/** @typedef AutocompleteResult */
/** @typedef BannerImage */
/** @typedef Brand */
/** @typedef BrandItem */
/** @typedef BrandListingResponse */
/** @typedef BrandMeta */
/** @typedef BrandMeta1 */
/** @typedef BulkAssetResponse */
/** @typedef BulkHsnResponse */
/** @typedef BulkHsnUpsert */
/** @typedef BulkInventoryGet */
/** @typedef BulkInventoryGetItems */
/** @typedef BulkJob */
/** @typedef BulkProductRequest */
/** @typedef BulkResponse */
/** @typedef CatalogInsightBrand */
/** @typedef CatalogInsightItem */
/** @typedef CatalogInsightResponse */
/** @typedef CategoriesResponse */
/** @typedef Category */
/** @typedef CategoryCreateResponse */
/** @typedef CategoryItems */
/** @typedef CategoryListingResponse */
/** @typedef CategoryMapping */
/** @typedef CategoryMappingValues */
/** @typedef CategoryRequestBody */
/** @typedef CategoryResponse */
/** @typedef CategoryUpdateResponse */
/** @typedef Child */
/** @typedef CollectionBadge */
/** @typedef CollectionBanner */
/** @typedef CollectionCreateResponse */
/** @typedef CollectionDetailResponse */
/** @typedef CollectionImage */
/** @typedef CollectionItem */
/** @typedef CollectionItemUpdate */
/** @typedef CollectionListingFilter */
/** @typedef CollectionListingFilterTag */
/** @typedef CollectionListingFilterType */
/** @typedef CollectionQuery */
/** @typedef CollectionSchedule */
/** @typedef CompanyBrandDetail */
/** @typedef CompanyMeta */
/** @typedef CompanyMeta1 */
/** @typedef CompanyOptIn */
/** @typedef ConfigErrorResponse */
/** @typedef ConfigSuccessResponse */
/** @typedef ConfigurationBucketPoints */
/** @typedef ConfigurationListing */
/** @typedef ConfigurationListingFilter */
/** @typedef ConfigurationListingFilterConfig */
/** @typedef ConfigurationListingFilterValue */
/** @typedef ConfigurationListingSort */
/** @typedef ConfigurationListingSortConfig */
/** @typedef ConfigurationProduct */
/** @typedef ConfigurationProductConfig */
/** @typedef ConfigurationProductSimilar */
/** @typedef ConfigurationProductVariant */
/** @typedef ConfigurationProductVariantConfig */
/** @typedef CreateAutocompleteKeyword */
/** @typedef CreateAutocompleteWordsResponse */
/** @typedef CreateCollection */
/** @typedef CreateSearchKeyword */
/** @typedef CrossSellingData */
/** @typedef CrossSellingResponse */
/** @typedef CustomOrder */
/** @typedef DateMeta */
/** @typedef DefaultKeyRequest */
/** @typedef DeleteResponse */
/** @typedef Department */
/** @typedef DepartmentCategoryTree */
/** @typedef DepartmentCreateErrorResponse */
/** @typedef DepartmentCreateResponse */
/** @typedef DepartmentCreateUpdate */
/** @typedef DepartmentErrorResponse */
/** @typedef DepartmentIdentifier */
/** @typedef DepartmentModel */
/** @typedef DepartmentResponse */
/** @typedef DepartmentsResponse */
/** @typedef DimensionResponse */
/** @typedef DimensionResponse1 */
/** @typedef Document */
/** @typedef EntityConfiguration */
/** @typedef ErrorResponse */
/** @typedef FilerList */
/** @typedef GenderDetail */
/** @typedef GetAddressSerializer */
/** @typedef GetAllSizes */
/** @typedef GetAppCatalogConfiguration */
/** @typedef GetAppCatalogEntityConfiguration */
/** @typedef GetAutocompleteWordsData */
/** @typedef GetAutocompleteWordsResponse */
/** @typedef GetCatalogConfigurationDetailsProduct */
/** @typedef GetCatalogConfigurationDetailsSchemaListing */
/** @typedef GetCatalogConfigurationMetaData */
/** @typedef GetCollectionDetailNest */
/** @typedef GetCollectionItemsResponse */
/** @typedef GetCollectionListingResponse */
/** @typedef GetCollectionQueryOptionResponse */
/** @typedef GetCompanySerializer */
/** @typedef GetConfigMetadataResponse */
/** @typedef GetConfigResponse */
/** @typedef GetDepartment */
/** @typedef GetInventories */
/** @typedef GetInventoriesResponse */
/** @typedef GetLocationSerializer */
/** @typedef GetOptInPlatform */
/** @typedef GetProductBundleCreateResponse */
/** @typedef GetProductBundleListingResponse */
/** @typedef GetProductBundleResponse */
/** @typedef GetProducts */
/** @typedef GetSearchWordsData */
/** @typedef GetSearchWordsDetailResponse */
/** @typedef GetSearchWordsResponse */
/** @typedef GlobalValidation */
/** @typedef GTIN */
/** @typedef Guide */
/** @typedef Hierarchy */
/** @typedef HsnCode */
/** @typedef HsnCodesListingResponseSchemaV2 */
/** @typedef HsnCodesObject */
/** @typedef HSNCodesResponse */
/** @typedef HSNData */
/** @typedef HSNDataInsertV2 */
/** @typedef HsnUpsert */
/** @typedef Image */
/** @typedef ImageUrls */
/** @typedef InventoryBulkRequest */
/** @typedef InventoryConfig */
/** @typedef InventoryCreateRequest */
/** @typedef InventoryExportAdvanceOption */
/** @typedef InventoryExportFilter */
/** @typedef InventoryExportJob */
/** @typedef InventoryExportJobListResponse */
/** @typedef InventoryExportQuantityFilter */
/** @typedef InventoryExportRequest */
/** @typedef InventoryExportResponse */
/** @typedef InventoryFailedReason */
/** @typedef InventoryJobDetailResponse */
/** @typedef InventoryJobFilters */
/** @typedef InventoryJobPayload */
/** @typedef InventoryPage */
/** @typedef InventoryPayload */
/** @typedef InventoryRequest */
/** @typedef InventoryRequestSchemaV2 */
/** @typedef InventoryResponse */
/** @typedef InventoryResponseItem */
/** @typedef InventoryResponsePaginated */
/** @typedef InventorySellerIdentifierResponsePaginated */
/** @typedef InventorySellerResponse */
/** @typedef InventorySet */
/** @typedef InventoryStockResponse */
/** @typedef InventoryUpdateResponse */
/** @typedef InventoryValidationResponse */
/** @typedef InvoiceCredSerializer */
/** @typedef InvoiceDetailsSerializer */
/** @typedef InvSize */
/** @typedef ItemQuery */
/** @typedef Items */
/** @typedef LimitedProductData */
/** @typedef ListSizeGuide */
/** @typedef LocationDayWiseSerializer */
/** @typedef LocationIntegrationType */
/** @typedef LocationListSerializer */
/** @typedef LocationManagerSerializer */
/** @typedef LocationTimingSerializer */
/** @typedef Logo */
/** @typedef ManufacturerResponse */
/** @typedef ManufacturerResponse1 */
/** @typedef Media */
/** @typedef Media1 */
/** @typedef Media2 */
/** @typedef Meta */
/** @typedef MetaDataListingFilterMetaResponse */
/** @typedef MetaDataListingFilterResponse */
/** @typedef MetaDataListingResponse */
/** @typedef MetaDataListingSortMetaResponse */
/** @typedef MetaDataListingSortResponse */
/** @typedef MetaFields */
/** @typedef MOQData */
/** @typedef NetQuantity */
/** @typedef NetQuantityResponse */
/** @typedef NextSchedule */
/** @typedef OptinCompanyBrandDetailsView */
/** @typedef OptinCompanyDetail */
/** @typedef OptinCompanyMetrics */
/** @typedef OptInPostRequest */
/** @typedef OptinStoreDetails */
/** @typedef OwnerAppItemResponse */
/** @typedef Page */
/** @typedef PageResponse */
/** @typedef PageResponseType */
/** @typedef Price */
/** @typedef Price1 */
/** @typedef PriceArticle */
/** @typedef PriceMeta */
/** @typedef ProdcutTemplateCategoriesResponse */
/** @typedef Product */
/** @typedef ProductAttributesResponse */
/** @typedef ProductBrand */
/** @typedef ProductBulkAssets */
/** @typedef ProductBulkRequest */
/** @typedef ProductBulkRequestList */
/** @typedef ProductBundleItem */
/** @typedef ProductBundleRequest */
/** @typedef ProductBundleUpdateRequest */
/** @typedef ProductConfigurationDownloads */
/** @typedef ProductCreateUpdateSchemaV2 */
/** @typedef ProductDetail */
/** @typedef ProductDetailAttribute */
/** @typedef ProductDetailGroupedAttribute */
/** @typedef ProductDownloadsResponse */
/** @typedef ProductFilters */
/** @typedef ProductFiltersKey */
/** @typedef ProductFiltersValue */
/** @typedef ProductListingDetail */
/** @typedef ProductListingPrice */
/** @typedef ProductListingResponse */
/** @typedef ProductListingResponseV2 */
/** @typedef ProductPublish */
/** @typedef ProductPublish1 */
/** @typedef ProductPublished */
/** @typedef ProductReturnConfigSerializer */
/** @typedef ProductSchemaV2 */
/** @typedef ProductSize */
/** @typedef ProductSizeDeleteDataResponse */
/** @typedef ProductSizeDeleteResponse */
/** @typedef ProductSortOn */
/** @typedef ProductTagsViewResponse */
/** @typedef ProductTemplate */
/** @typedef ProductTemplateDownloadsExport */
/** @typedef ProductTemplateExportFilterRequest */
/** @typedef ProductTemplateExportResponse */
/** @typedef ProductVariants */
/** @typedef ProductVariantsResponse */
/** @typedef Properties */
/** @typedef PTErrorResponse */
/** @typedef Quantities */
/** @typedef QuantitiesArticle */
/** @typedef Quantity */
/** @typedef QuantityBase */
/** @typedef ReturnConfig */
/** @typedef ReturnConfig1 */
/** @typedef ReturnConfig2 */
/** @typedef ReturnConfigResponse */
/** @typedef SearchKeywordResult */
/** @typedef SecondLevelChild */
/** @typedef SellerPhoneNumber */
/** @typedef SEOData */
/** @typedef SeoDetail */
/** @typedef SetSize */
/** @typedef SingleCategoryResponse */
/** @typedef SingleProductResponse */
/** @typedef Size */
/** @typedef SizeDistribution */
/** @typedef SizeGuideResponse */
/** @typedef StoreAssignResponse */
/** @typedef StoreDetail */
/** @typedef StoreMeta */
/** @typedef SuccessResponse */
/** @typedef SuccessResponse1 */
/** @typedef TaxIdentifier */
/** @typedef TaxSlab */
/** @typedef TeaserTag */
/** @typedef TemplateDetails */
/** @typedef TemplatesResponse */
/** @typedef TemplatesValidationResponse */
/** @typedef TemplateValidationData */
/** @typedef ThirdLevelChild */
/** @typedef Trader */
/** @typedef Trader1 */
/** @typedef Trader2 */
/** @typedef UpdateCollection */
/** @typedef UpdatedResponse */
/** @typedef UserCommon */
/** @typedef UserDetail */
/** @typedef UserDetail1 */
/** @typedef UserInfo */
/** @typedef UserInfo1 */
/** @typedef UserSerializer */
/** @typedef UserSerializer1 */
/** @typedef UserSerializer2 */
/** @typedef ValidateIdentifier */
/** @typedef ValidateProduct */
/** @typedef ValidateSizeGuide */
/** @typedef VerifiedBy */
/** @typedef WeightResponse */
/** @typedef WeightResponse1 */

/** @typedef AddressSerializer */
/** @typedef BrandBannerSerializer */
/** @typedef BulkLocationSerializer */
/** @typedef BusinessCountryInfo */
/** @typedef BusinessDetails */
/** @typedef CompanyBrandListSerializer */
/** @typedef CompanyBrandPostRequestSerializer */
/** @typedef CompanyBrandSerializer */
/** @typedef CompanyDetails */
/** @typedef CompanySerializer */
/** @typedef CompanySocialAccounts */
/** @typedef CompanyTaxesSerializer */
/** @typedef CompanyTaxesSerializer1 */
/** @typedef ContactDetails */
/** @typedef CreateUpdateAddressSerializer */
/** @typedef CreateUpdateBrandRequestSerializer */
/** @typedef Document */
/** @typedef DocumentsObj */
/** @typedef ErrorResponse */
/** @typedef GetAddressSerializer */
/** @typedef GetBrandResponseSerializer */
/** @typedef GetCompanyProfileSerializerResponse */
/** @typedef GetCompanySerializer */
/** @typedef GetLocationSerializer */
/** @typedef HolidayDateSerializer */
/** @typedef HolidaySchemaSerializer */
/** @typedef InvoiceCredSerializer */
/** @typedef InvoiceDetailsSerializer */
/** @typedef LocationDayWiseSerializer */
/** @typedef LocationListSerializer */
/** @typedef LocationManagerSerializer */
/** @typedef LocationSerializer */
/** @typedef LocationTimingSerializer */
/** @typedef MetricsSerializer */
/** @typedef Page */
/** @typedef ProductReturnConfigSerializer */
/** @typedef ProfileSuccessResponse */
/** @typedef SellerPhoneNumber */
/** @typedef UpdateCompany */
/** @typedef UserSerializer */
/** @typedef Website */

/** @typedef BrowseResponse */
/** @typedef BulkRequest */
/** @typedef BulkUploadResponse */
/** @typedef CDN */
/** @typedef CompleteResponse */
/** @typedef CopyFileTask */
/** @typedef DbRecord */
/** @typedef Destination */
/** @typedef FailedResponse */
/** @typedef Opts */
/** @typedef Page */
/** @typedef ReqConfiguration */
/** @typedef SignUrlRequest */
/** @typedef SignUrlResponse */
/** @typedef StartRequest */
/** @typedef StartResponse */
/** @typedef Upload */
/** @typedef Urls */

/** @typedef Attribution */
/** @typedef CampaignShortLink */
/** @typedef ClickStatsItem */
/** @typedef ClickStatsResponse */
/** @typedef ErrorRes */
/** @typedef Page */
/** @typedef RedirectDevice */
/** @typedef Redirects */
/** @typedef ShortLinkList */
/** @typedef ShortLinkReq */
/** @typedef ShortLinkRes */
/** @typedef SocialMediaTags */
/** @typedef UrlInfo */
/** @typedef WebRedirect */

/** @typedef ArchiveConfig */
/** @typedef Audit */
/** @typedef AWSS3config */
/** @typedef CatalogMasterConfig */
/** @typedef CompanyConfig */
/** @typedef DataTresholdDTO */
/** @typedef DBConfig */
/** @typedef DBConnectionProfile */
/** @typedef DBParamConfig */
/** @typedef DefaultHeadersDTO */
/** @typedef DocMappingConfig */
/** @typedef EmailConfig */
/** @typedef FileConfig */
/** @typedef FTPConfig */
/** @typedef GCompany */
/** @typedef GenericDTO */
/** @typedef GoogleSpreadSheetConfig */
/** @typedef GStore */
/** @typedef HttpConfig */
/** @typedef JobConfig */
/** @typedef JobConfigDTO */
/** @typedef JobConfigListDTO */
/** @typedef JobConfigRawDTO */
/** @typedef JobHistoryDto */
/** @typedef JobMetricsDto */
/** @typedef JobStepsDTO */
/** @typedef JsonDocConfig */
/** @typedef KafkaMetaModel */
/** @typedef KafkaResponse */
/** @typedef LocalFileConfig */
/** @typedef Metum */
/** @typedef MongoDocConfig */
/** @typedef OAuthConfig */
/** @typedef Page */
/** @typedef ProcessConfig */
/** @typedef PropBeanConfig */
/** @typedef PropBeanDTO */
/** @typedef ResponseEnvelopeJobConfigDTO */
/** @typedef ResponseEnvelopeJobMetricsDto */
/** @typedef ResponseEnvelopeKafkaResponse */
/** @typedef ResponseEnvelopeListJobConfigDTO */
/** @typedef ResponseEnvelopeListJobConfigListDTO */
/** @typedef ResponseEnvelopeListJobConfigRawDTO */
/** @typedef ResponseEnvelopeListJobStepsDTO */
/** @typedef ResponseEnvelopeListSlingshotConfigurationDetail */
/** @typedef ResponseEnvelopeString */
/** @typedef Send */
/** @typedef SFTPConfig */
/** @typedef SlingshotConfigurationDetail */
/** @typedef SlingshotIntegration */
/** @typedef StoreConfig */
/** @typedef StoreData */
/** @typedef StoreFilter */
/** @typedef SuppressStoreModel */
/** @typedef SuppressStorePayload */
/** @typedef TaskConfig */
/** @typedef TaskDTO */
/** @typedef TaskParam */
/** @typedef TaskStepConfig */

/** @typedef Android */
/** @typedef App */
/** @typedef AppCartConfig */
/** @typedef AppCurrencyResponse */
/** @typedef AppDomain */
/** @typedef AppFeature */
/** @typedef AppFeatureRequest */
/** @typedef AppFeatureResponse */
/** @typedef AppInventory */
/** @typedef AppInventoryCompanies */
/** @typedef AppInventoryConfig */
/** @typedef AppInventoryPartialUpdate */
/** @typedef AppInventoryStores */
/** @typedef Application */
/** @typedef ApplicationAuth */
/** @typedef ApplicationCors */
/** @typedef ApplicationDetail */
/** @typedef ApplicationInformation */
/** @typedef ApplicationInventory */
/** @typedef ApplicationMeta */
/** @typedef ApplicationRedirections */
/** @typedef ApplicationsResponse */
/** @typedef ApplicationWebsite */
/** @typedef AppLogisticsConfig */
/** @typedef AppOrderConfig */
/** @typedef AppPaymentConfig */
/** @typedef AppStoreRules */
/** @typedef AppSupportedCurrency */
/** @typedef ArticleAssignmentConfig */
/** @typedef ArticleAssignmentRule */
/** @typedef ArticleAssignmentRules */
/** @typedef AuthenticationConfig */
/** @typedef BlogLink */
/** @typedef BrandCompanyInfo */
/** @typedef BrandsByCompanyResponse */
/** @typedef BrandStoreInfo */
/** @typedef BuildVersion */
/** @typedef BuildVersionHistory */
/** @typedef BusinessHighlights */
/** @typedef CallbackUrl */
/** @typedef CartFeature */
/** @typedef Charges */
/** @typedef CommonFeature */
/** @typedef CommsConfig */
/** @typedef CommunicationConfig */
/** @typedef CommunicationOptinDialogFeature */
/** @typedef CompaniesResponse */
/** @typedef CompanyAboutAddress */
/** @typedef CompanyBrandInfo */
/** @typedef CompanyByBrandsRequest */
/** @typedef CompanyByBrandsResponse */
/** @typedef CompanyValidator */
/** @typedef CompareProductsFeature */
/** @typedef CreateApplicationRequest */
/** @typedef CreateAppResponse */
/** @typedef Credentials */
/** @typedef Credit */
/** @typedef CurrenciesResponse */
/** @typedef Currency */
/** @typedef CurrencyConfig */
/** @typedef CurrencyFeature */
/** @typedef Debit */
/** @typedef DefaultCurrency */
/** @typedef DeliveryCharges */
/** @typedef DeploymentMeta */
/** @typedef DeploymentStoreSelectionFeature */
/** @typedef Domain */
/** @typedef DomainAdd */
/** @typedef DomainAddRequest */
/** @typedef DomainsResponse */
/** @typedef DomainStatus */
/** @typedef DomainStatusRequest */
/** @typedef DomainStatusResponse */
/** @typedef DomainSuggestion */
/** @typedef DomainSuggestionsRequest */
/** @typedef DomainSuggestionsResponse */
/** @typedef FacebookLink */
/** @typedef FeedbackFeature */
/** @typedef FilterOrderingStoreRequest */
/** @typedef Firebase */
/** @typedef Freshchat */
/** @typedef FreshchatCredentials */
/** @typedef FyndRewards */
/** @typedef FyndRewardsCredentials */
/** @typedef GetIntegrationsOptInsResponse */
/** @typedef GoogleMap */
/** @typedef GoogleMapCredentials */
/** @typedef GooglePlusLink */
/** @typedef Gtm */
/** @typedef GtmCredentials */
/** @typedef HomePageFeature */
/** @typedef InformationAddress */
/** @typedef InformationPhone */
/** @typedef InformationSupport */
/** @typedef InstagramLink */
/** @typedef Integration */
/** @typedef IntegrationConfigResponse */
/** @typedef IntegrationLevel */
/** @typedef IntegrationMeta */
/** @typedef IntegrationOptIn */
/** @typedef InvalidPayloadRequest */
/** @typedef InventoryArticleAssignment */
/** @typedef InventoryBrand */
/** @typedef InventoryBrandRule */
/** @typedef InventoryCategory */
/** @typedef InventoryDiscount */
/** @typedef InventoryPaymentConfig */
/** @typedef InventoryPrice */
/** @typedef InventoryStore */
/** @typedef InventoryStoreRule */
/** @typedef InventoryValidator */
/** @typedef Ios */
/** @typedef JsonSchema */
/** @typedef LandingImage */
/** @typedef LandingPageFeature */
/** @typedef LastPatch */
/** @typedef LaunchPage */
/** @typedef LinkedInLink */
/** @typedef Links */
/** @typedef ListingPriceFeature */
/** @typedef LoyaltyPointsConfig */
/** @typedef Methods */
/** @typedef MobileAppConfigRequest */
/** @typedef MobileAppConfiguration */
/** @typedef Moengage */
/** @typedef MoengageCredentials */
/** @typedef NotFound */
/** @typedef OptedApplicationResponse */
/** @typedef OptedCompany */
/** @typedef OptedInventory */
/** @typedef OptedStore */
/** @typedef OptedStoreAddress */
/** @typedef OptedStoreIntegration */
/** @typedef OptOutInventory */
/** @typedef OptType */
/** @typedef OrderFeature */
/** @typedef OrderingStore */
/** @typedef OrderingStoreConfig */
/** @typedef OrderingStores */
/** @typedef OrderingStoresResponse */
/** @typedef OrderValidator */
/** @typedef OtherEntity */
/** @typedef OtherEntityData */
/** @typedef OtherSellerApplication */
/** @typedef OtherSellerApplications */
/** @typedef OtherSellerCompany */
/** @typedef Page */
/** @typedef PaymentModeConfig */
/** @typedef PaymentSelectionLock */
/** @typedef PcrFeature */
/** @typedef PinterestLink */
/** @typedef ProductDetailFeature */
/** @typedef QrFeature */
/** @typedef RegistrationPageFeature */
/** @typedef RevenueEngineFeature */
/** @typedef RewardPointsConfig */
/** @typedef Safetynet */
/** @typedef SafetynetCredentials */
/** @typedef SecureUrl */
/** @typedef Segment */
/** @typedef SegmentCredentials */
/** @typedef SocialLinks */
/** @typedef SplashImage */
/** @typedef StoreByBrandsRequest */
/** @typedef StoreByBrandsResponse */
/** @typedef StoreCriteriaRule */
/** @typedef StoreLatLong */
/** @typedef StorePriority */
/** @typedef StorePriorityRule */
/** @typedef StoresResponse */
/** @typedef StoreValidator */
/** @typedef SuccessMessageResponse */
/** @typedef TokenResponse */
/** @typedef Tokens */
/** @typedef TwitterLink */
/** @typedef UnhandledError */
/** @typedef UpdateDomain */
/** @typedef UpdateDomainTypeRequest */
/** @typedef UpdateIntegrationLevelRequest */
/** @typedef UserEmail */
/** @typedef UserPhoneNumber */
/** @typedef ValidationFailedResponse */
/** @typedef Validators */
/** @typedef VimeoLink */
/** @typedef YoutubeLink */

/** @typedef AbandonedCart */
/** @typedef AbandonedCartResponse */
/** @typedef ActionQuery */
/** @typedef ActivePromosResponse */
/** @typedef AddCartDetailResponse */
/** @typedef AddCartRequest */
/** @typedef AddProductCart */
/** @typedef AppliedFreeArticles */
/** @typedef AppliedPromotion */
/** @typedef ArticlePriceInfo */
/** @typedef BaseInfo */
/** @typedef BasePrice */
/** @typedef BulkBundleRestriction */
/** @typedef BuyRules */
/** @typedef CartBreakup */
/** @typedef CartCurrency */
/** @typedef CartDetailResponse */
/** @typedef CartItem */
/** @typedef CartItemMeta */
/** @typedef CartMetaConfigAdd */
/** @typedef CartMetaConfigUpdate */
/** @typedef CartProduct */
/** @typedef CartProductIdentifer */
/** @typedef CartProductInfo */
/** @typedef CategoryInfo */
/** @typedef Charges */
/** @typedef CompareObject */
/** @typedef CouponAction */
/** @typedef CouponAdd */
/** @typedef CouponAuthor */
/** @typedef CouponBreakup */
/** @typedef CouponDateMeta */
/** @typedef CouponPartialUpdate */
/** @typedef CouponSchedule */
/** @typedef CouponsResponse */
/** @typedef CouponUpdate */
/** @typedef DeliveryCharges */
/** @typedef DiscountOffer */
/** @typedef DiscountRule */
/** @typedef DiscountRulesApp */
/** @typedef DisplayBreakup */
/** @typedef DisplayMeta */
/** @typedef DisplayMeta1 */
/** @typedef DisplayMetaDict */
/** @typedef FreeGiftItem */
/** @typedef Identifier */
/** @typedef ItemCriteria */
/** @typedef LoyaltyPoints */
/** @typedef MultiTenderPaymentMeta */
/** @typedef MultiTenderPaymentMethod */
/** @typedef OpenapiCartDetailsRequest */
/** @typedef OpenapiCartDetailsResponse */
/** @typedef OpenApiCartServiceabilityRequest */
/** @typedef OpenApiCartServiceabilityResponse */
/** @typedef OpenApiCheckoutResponse */
/** @typedef OpenApiErrorResponse */
/** @typedef OpenApiFiles */
/** @typedef OpenApiOrderItem */
/** @typedef OpenApiPlatformCheckoutReq */
/** @typedef OperationErrorResponse */
/** @typedef OverrideCartItem */
/** @typedef OverrideCartItemPromo */
/** @typedef OverrideCheckoutReq */
/** @typedef OverrideCheckoutResponse */
/** @typedef Ownership */
/** @typedef Ownership1 */
/** @typedef Ownership2 */
/** @typedef Page */
/** @typedef PaymentAllowValue */
/** @typedef PaymentAllowValue1 */
/** @typedef PaymentModes */
/** @typedef PaymentSelectionLock */
/** @typedef PostOrder */
/** @typedef PostOrder1 */
/** @typedef PriceRange */
/** @typedef ProductAction */
/** @typedef ProductArticle */
/** @typedef ProductAvailability */
/** @typedef ProductAvailabilitySize */
/** @typedef ProductImage */
/** @typedef ProductPrice */
/** @typedef ProductPriceInfo */
/** @typedef PromiseFormatted */
/** @typedef PromiseTimestamp */
/** @typedef PromoMeta */
/** @typedef PromotionAction */
/** @typedef PromotionAdd */
/** @typedef PromotionAuthor */
/** @typedef PromotionDateMeta */
/** @typedef PromotionListItem */
/** @typedef PromotionPartialUpdate */
/** @typedef PromotionPaymentModes */
/** @typedef PromotionSchedule */
/** @typedef PromotionsResponse */
/** @typedef PromotionUpdate */
/** @typedef RawBreakup */
/** @typedef Restrictions */
/** @typedef Restrictions1 */
/** @typedef Rule */
/** @typedef RuleDefinition */
/** @typedef ShipmentPromise */
/** @typedef ShippingAddress */
/** @typedef State */
/** @typedef SuccessMessage */
/** @typedef UpdateCartDetailResponse */
/** @typedef UpdateCartRequest */
/** @typedef UpdateProductCart */
/** @typedef UserRegistered */
/** @typedef UsesRemaining */
/** @typedef UsesRemaining1 */
/** @typedef UsesRestriction */
/** @typedef UsesRestriction1 */
/** @typedef Validation */
/** @typedef Validity */
/** @typedef Visibility */

/** @typedef AppUser */
/** @typedef Asset */
/** @typedef ConfigurationRequest */
/** @typedef ConfigurationRes */
/** @typedef E */
/** @typedef Giveaway */
/** @typedef GiveawayAudience */
/** @typedef GiveawayResponse */
/** @typedef HistoryRes */
/** @typedef Offer */
/** @typedef Page */
/** @typedef Points */
/** @typedef PointsHistory */
/** @typedef Referral */
/** @typedef RewardsAudience */
/** @typedef RewardsRule */
/** @typedef RewardUser */
/** @typedef Schedule */
/** @typedef SetConfigurationRes */
/** @typedef ShareMessages */
/** @typedef UserRes */

/** @typedef BadRequestObject */
/** @typedef BulkDiscount */
/** @typedef CancelJobResponse */
/** @typedef CreateUpdateDiscount */
/** @typedef DiscountItems */
/** @typedef DiscountJob */
/** @typedef DownloadFileJob */
/** @typedef FileJobRequest */
/** @typedef FileJobResponse */
/** @typedef ListOrCalender */
/** @typedef Page */
/** @typedef UserDetails */
/** @typedef ValidityObject */

/** @typedef AddProxyReq */
/** @typedef AddProxyResponse */
/** @typedef APIError */
/** @typedef RemoveProxyResponse */

/** @typedef Association */
/** @typedef AuthMeta */
/** @typedef EventConfig */
/** @typedef EventConfigBase */
/** @typedef EventConfigList */
/** @typedef EventConfigResponse */
/** @typedef EventPayload */
/** @typedef EventProcessedStatus */
/** @typedef Page */
/** @typedef SubscriberConfig */
/** @typedef SubscriberConfigList */
/** @typedef SubscriberEvent */
/** @typedef SubscriberResponse */

/** @typedef BadRequest */
/** @typedef CreateLogResponse */
/** @typedef DeviceInfo */
/** @typedef EntityObj */
/** @typedef EntityObject */
/** @typedef EntityTypeObj */
/** @typedef EntityTypesResponse */
/** @typedef InternalServerError */
/** @typedef Location */
/** @typedef LogDocs */
/** @typedef LogMetaObj */
/** @typedef LogSchemaResponse */
/** @typedef Modifier */
/** @typedef RequestBodyAuditLog */
/** @typedef ResourceNotFound */

/** @typedef CreditlineDataPlatformPayload */
/** @typedef CreditlineDataPlatformRequest */
/** @typedef CreditlineDataPlatformResponse */
/** @typedef DownloadCreditDebitNote */
/** @typedef DownloadCreditDebitNoteRequest */
/** @typedef DownloadCreditDebitNoteResponse */
/** @typedef DownloadCreditDebitNoteResponseData */
/** @typedef DownloadReport */
/** @typedef DownloadReportItems */
/** @typedef DownloadReportList */
/** @typedef Error */
/** @typedef GenerateReportFilters */
/** @typedef GenerateReportJson */
/** @typedef GenerateReportMeta */
/** @typedef GenerateReportPlatform */
/** @typedef GenerateReportRequest */
/** @typedef GetAffiliate */
/** @typedef GetAffiliateResponse */
/** @typedef GetDocs */
/** @typedef GetEngineData */
/** @typedef GetEngineFilters */
/** @typedef GetEngineRequest */
/** @typedef GetEngineResponse */
/** @typedef GetReason */
/** @typedef GetReasonRequest */
/** @typedef GetReasonResponse */
/** @typedef GetReportListData */
/** @typedef GetReportListRequest */
/** @typedef InoviceListingPayloadDataFilters */
/** @typedef InvoiceListingPayloadData */
/** @typedef InvoiceListingRequest */
/** @typedef InvoiceListingResponse */
/** @typedef InvoiceListingResponseItems */
/** @typedef InvoicePdfPayloadData */
/** @typedef InvoicePdfRequest */
/** @typedef InvoicePdfResponse */
/** @typedef InvoiceTypePayloadData */
/** @typedef InvoiceTypeRequest */
/** @typedef InvoiceTypeResponse */
/** @typedef InvoiceTypeResponseItems */
/** @typedef IsCreditlinePayload */
/** @typedef IsCreditlinePlatformRequest */
/** @typedef IsCreditlinePlatformResponse */
/** @typedef Page */
/** @typedef PaymentProcessPayload */
/** @typedef PaymentProcessRequest */
/** @typedef PaymentProcessResponse */
/** @typedef UnpaidInvoiceDataItems */

module.exports = PlatformApplicationClient;
