const Joi = require("joi");

/**
 * @typedef BuyRules
 * @property {Object} [item_criteria] - Item criteria of promotion
 * @property {Object} [cart_conditions] - Cart conditions details for promotion
 */

/**
 * @typedef DiscountRulesApp
 * @property {string[]} [matched_buy_rules] - Matched buy rules for promotion
 * @property {Object} [raw_offer] - Raw offer details for promotion
 * @property {Object} [offer] - Offer for promotion
 * @property {Object} [item_criteria] - Item criteria of promotion
 */

/**
 * @typedef Ownership
 * @property {string} [payable_category] - Promo amount payable category
 * @property {string} [payable_by] - Promo amount bearable party
 */

/**
 * @typedef AppliedFreeArticles
 * @property {FreeGiftItems} [free_gift_item_details] - Free gift items details
 * @property {string} [parent_item_identifier] - Parent item identifier for free article
 * @property {number} [quantity] - Free article quantity
 * @property {string} [article_id] - Free article id
 */

/**
 * @typedef AppliedPromotion
 * @property {string} [promo_id] - Promotion id
 * @property {BuyRules[]} [buy_rules] - Buy rules for promotions
 * @property {string} [offer_text] - Offer text of current promotion
 * @property {string} [promotion_group] - Promotion group for the promotion
 * @property {boolean} [mrp_promotion] - If applied promotion is applied on
 *   product MRP or ESP
 * @property {string} [promotion_name] - Promotion name of current promotion
 * @property {number} [amount] - Per unit discount amount applied with current promotion
 * @property {DiscountRulesApp[]} [discount_rules] - Discount rules for promotions
 * @property {Ownership} [ownership] - Ownership of promotion
 * @property {number} [article_quantity] - Quantity of article on which
 *   promotion is applicable
 * @property {AppliedFreeArticles[]} [applied_free_articles] - Applied free
 *   article for free gift item promotions
 * @property {string} [promotion_type] - Promotion type of current promotion
 * @property {Object} [meta] - Meta object for extra data
 * @property {string} [code] - Promotion code
 */

/**
 * @typedef PaymentSelectionLock
 * @property {boolean} [enabled]
 * @property {string} [default_options]
 * @property {string} [payment_identifier]
 */

/**
 * @typedef PromiseFormatted
 * @property {string} [max]
 * @property {string} [min]
 */

/**
 * @typedef PromiseISOFormat
 * @property {string} [max] - Max promise in ISO format.
 * @property {string} [min] - Min Promise in ISO format.
 */

/**
 * @typedef PromiseTimestamp
 * @property {number} [max]
 * @property {number} [min]
 */

/**
 * @typedef ShipmentPromise
 * @property {PromiseFormatted} [formatted]
 * @property {PromiseTimestamp} [timestamp]
 * @property {PromiseISOFormat} [iso]
 */

/**
 * @typedef BasePrice
 * @property {number} [effective]
 * @property {string} [currency_symbol]
 * @property {number} [marked]
 * @property {string} [currency_code]
 */

/**
 * @typedef ArticlePriceInfo
 * @property {BasePrice} [base]
 * @property {BasePrice} [converted]
 */

/**
 * @typedef BaseInfo
 * @property {number} [uid]
 * @property {string} [name]
 */

/**
 * @typedef StoreInfo
 * @property {string} [store_code]
 * @property {number} [uid]
 * @property {string} [name]
 */

/**
 * @typedef ProductArticle
 * @property {ArticlePriceInfo} [price]
 * @property {string[]} [product_group_tags]
 * @property {Object} [extra_meta]
 * @property {number} [quantity]
 * @property {Object} [_custom_json]
 * @property {Object} [meta]
 * @property {string} [size]
 * @property {number} [mto_quantity]
 * @property {BaseInfo} [seller]
 * @property {string} [seller_identifier]
 * @property {Object} [parent_item_identifiers]
 * @property {Object} [identifier]
 * @property {StoreInfo} [store]
 * @property {Object} [cart_item_meta]
 * @property {string} [uid]
 * @property {Object} [gift_card]
 * @property {boolean} [is_gift_visible]
 * @property {string} [type]
 * @property {string[]} [tags] - A list of article tags
 */

/**
 * @typedef CartProductIdentifer
 * @property {string} [identifier] - Article idenfier generated by cart
 */

/**
 * @typedef PromoMeta
 * @property {string} [message]
 */

/**
 * @typedef ChargesAmount
 * @property {number} [value] - This is the value of amount added
 * @property {string} [currency] - This is destination currency of value
 */

/**
 * @typedef Charges
 * @property {Object} [meta] - This object contains the meta data realted to
 *   charges price adjustment
 * @property {ChargesAmount} [amount]
 * @property {string} [name] - This is the name of the charge applied
 * @property {boolean} [allow_refund] - This boolean value defines that refund
 *   is allowed or not for the charge
 * @property {string} [code] - This is the code of the charge applied
 * @property {string} [type] - This is the type of the charge applied
 */

/**
 * @typedef ProductPrice
 * @property {string} [currency_symbol]
 * @property {number} [selling]
 * @property {string} [currency_code]
 * @property {number} [add_on]
 * @property {number} [effective]
 * @property {number} [marked]
 */

/**
 * @typedef ProductPriceInfo
 * @property {ProductPrice} [base]
 * @property {ProductPrice} [converted]
 */

/**
 * @typedef ProductPricePerUnit
 * @property {string} [currency_symbol]
 * @property {number} [selling_price]
 * @property {string} [currency_code]
 * @property {number} [add_on]
 * @property {number} [effective]
 * @property {number} [marked]
 */

/**
 * @typedef ProductPricePerUnitInfo
 * @property {ProductPricePerUnit} [base]
 * @property {ProductPricePerUnit} [converted]
 */

/**
 * @typedef ProductAvailabilitySize
 * @property {string} [display]
 * @property {string} [value]
 * @property {boolean} [is_available]
 */

/**
 * @typedef ProductAvailability
 * @property {boolean} [out_of_stock]
 * @property {boolean} [deliverable]
 * @property {ProductAvailabilitySize[]} [available_sizes]
 * @property {boolean} [is_valid]
 * @property {number} [other_store_quantity]
 * @property {string[]} [sizes]
 */

/**
 * @typedef ActionQuery
 * @property {string[]} [product_slug] - Contains list of product slug
 */

/**
 * @typedef ProductAction
 * @property {ActionQuery} [query]
 * @property {string} [url]
 * @property {string} [type]
 */

/**
 * @typedef Tags
 * @property {Object} [tags]
 */

/**
 * @typedef ProductImage
 * @property {string} [secure_url]
 * @property {string} [aspect_ratio]
 * @property {string} [url]
 */

/**
 * @typedef CategoryInfo
 * @property {number} [uid] - Product Category Id
 * @property {string} [name]
 */

/**
 * @typedef CartProduct
 * @property {Object} [_custom_json]
 * @property {BaseInfo} [brand]
 * @property {ProductAction} [action]
 * @property {Tags} [teaser_tag]
 * @property {string} [slug] - Unique product url name generated via product
 *   name and other meta data
 * @property {ProductImage[]} [images]
 * @property {number} [uid]
 * @property {string} [name]
 * @property {string} [item_code]
 * @property {CategoryInfo[]} [categories]
 * @property {string[]} [tags]
 * @property {string} [type]
 * @property {Object} [attributes]
 */

/**
 * @typedef CouponDetails
 * @property {number} [discount_single_quantity]
 * @property {string} [code]
 * @property {number} [discount_total_quantity]
 */

/**
 * @typedef CartProductInfo
 * @property {ProductArticle} [article]
 * @property {Object} [moq]
 * @property {CartProductIdentifer} identifiers
 * @property {PromoMeta} [promo_meta]
 * @property {ProductPriceInfo} [price]
 * @property {number} [quantity]
 * @property {Charges[]} [charges]
 * @property {string} [discount]
 * @property {ProductAvailability} [availability]
 * @property {ShipmentPromise} [delivery_promise]
 * @property {CartProduct} [product]
 * @property {string} [product_ean_id]
 * @property {Object} [bulk_offer]
 * @property {Object} [parent_item_identifiers]
 * @property {CouponDetails} [coupon]
 * @property {Object} [custom_order]
 * @property {string} [coupon_message]
 * @property {string} [key]
 * @property {string} [message]
 * @property {boolean} [is_set]
 * @property {ProductPricePerUnitInfo} [price_per_unit]
 * @property {AppliedPromotion[]} [promotions_applied]
 */

/**
 * @typedef DisplayBreakup
 * @property {string} [currency_symbol]
 * @property {string} [key]
 * @property {string} [display]
 * @property {string[]} [message]
 * @property {string} [currency_code]
 * @property {number} [value]
 * @property {number} [preset]
 */

/**
 * @typedef RawBreakup
 * @property {number} [vog]
 * @property {number} [subtotal]
 * @property {number} [fynd_cash]
 * @property {number} [discount]
 * @property {number} [convenience_fee]
 * @property {number} [delivery_charge]
 * @property {number} [gst_charges]
 * @property {number} [mrp_total]
 * @property {number} [mop_total]
 * @property {number} [total_charge]
 * @property {number} [coupon]
 * @property {number} [total]
 * @property {number} [gift_card]
 * @property {number} [you_saved]
 * @property {number} [cod_charge]
 */

/**
 * @typedef CouponBreakup
 * @property {number} [coupon_value]
 * @property {string} [title]
 * @property {string} [sub_title]
 * @property {number} [minimum_cart_value]
 * @property {string} [message]
 * @property {string} [coupon_type]
 * @property {string} [uid]
 * @property {number} [value]
 * @property {number} [max_discount_value]
 * @property {boolean} [is_applied]
 * @property {string} [description]
 * @property {string} [code]
 * @property {string} [type]
 */

/**
 * @typedef LoyaltyPoints
 * @property {number} [total]
 * @property {string} [description]
 * @property {number} [applicable]
 * @property {boolean} [is_applied]
 */

/**
 * @typedef CartBreakup
 * @property {DisplayBreakup[]} [display]
 * @property {RawBreakup} [raw]
 * @property {CouponBreakup} [coupon]
 * @property {LoyaltyPoints} [loyalty_points]
 */

/**
 * @typedef CartCurrency
 * @property {string} [code] - Currency code defined by ISO 4217:2015
 * @property {string} [symbol]
 */

/**
 * @typedef CartDetailCoupon
 * @property {number} [cashback_amount]
 * @property {string} [cashback_message_primary]
 * @property {string} [cashback_message_secondary]
 * @property {string} [coupon_code]
 * @property {string} [coupon_description]
 * @property {string} [coupon_id]
 * @property {string} [coupon_subtitle]
 * @property {string} [coupon_title]
 * @property {string} [coupon_type]
 * @property {number} [coupon_value]
 * @property {number} [discount]
 * @property {boolean} [is_applied]
 * @property {boolean} [is_valid]
 * @property {number} [maximum_discount_value]
 * @property {string} [message]
 * @property {number} [minimum_cart_value]
 */

/**
 * @typedef ChargesThreshold
 * @property {number} [charges]
 * @property {number} [threshold]
 */

/**
 * @typedef DeliveryChargesConfig
 * @property {boolean} [enabled]
 * @property {ChargesThreshold[]} [charges]
 */

/**
 * @typedef CartCommonConfig
 * @property {DeliveryChargesConfig} [delivery_charges_config]
 */

/**
 * @typedef CartDetailResponse
 * @property {number} [cart_id]
 * @property {string} [uid]
 * @property {AppliedPromotion[]} [applied_promo_details]
 * @property {string} [checkout_mode]
 * @property {string} [pan_no]
 * @property {boolean} [is_valid]
 * @property {string} [id]
 * @property {PaymentSelectionLock} [payment_selection_lock]
 * @property {ShipmentPromise} [delivery_promise]
 * @property {string} [comment]
 * @property {CartProductInfo[]} [items]
 * @property {string} [delivery_charge_info]
 * @property {CartCommonConfig} [common_config]
 * @property {CartDetailCoupon} [coupon]
 * @property {string} [message]
 * @property {Object} [notification]
 * @property {string} [staff_user_id]
 * @property {boolean} [success]
 * @property {string} [gstin]
 * @property {boolean} [restrict_checkout]
 * @property {string} [last_modified]
 * @property {CartBreakup} [breakup_values]
 * @property {CartCurrency} [currency]
 * @property {string} [coupon_text]
 * @property {boolean} [buy_now]
 * @property {Object} [pan_config]
 * @property {Object} [custom_cart_meta]
 */

/**
 * @typedef AddProductCart
 * @property {Object} [article_assignment]
 * @property {string[]} [product_group_tags]
 * @property {Object} [extra_meta]
 * @property {number} [quantity]
 * @property {Object} [_custom_json]
 * @property {string} [item_size]
 * @property {number} [store_id]
 * @property {string} [display]
 * @property {string} [article_id]
 * @property {Object[]} [parent_item_identifiers]
 * @property {number} [seller_id]
 * @property {boolean} [pos]
 * @property {number} [item_id]
 * @property {Object} [meta]
 * @property {string} [seller_identifier] - Add items using seller identifier for store os
 */

/**
 * @typedef AddCartRequest
 * @property {AddProductCart[]} [items]
 * @property {boolean} [new_cart]
 */

/**
 * @typedef AddCartDetailResponse
 * @property {string} [message]
 * @property {boolean} [partial] - When adding multiple items check if all
 *   added. True if only few are added.
 * @property {CartDetailResponse} [cart]
 * @property {boolean} [success] - True if all items are added successfully.
 *   False if partially added or not added.
 */

/**
 * @typedef UpdateProductCart
 * @property {Object} [extra_meta]
 * @property {Object} [_custom_json]
 * @property {number} [quantity]
 * @property {string} [item_size]
 * @property {number} [item_index]
 * @property {CartProductIdentifer} identifiers
 * @property {string} [article_id]
 * @property {Object} [parent_item_identifiers]
 * @property {number} [item_id]
 * @property {Object} [meta]
 */

/**
 * @typedef UpdateCartRequest
 * @property {UpdateProductCart[]} [items]
 * @property {string} operation
 */

/**
 * @typedef UpdateCartDetailResponse
 * @property {string} [message]
 * @property {CartDetailResponse} [cart]
 * @property {boolean} [success] - True if all items are added successfully.
 *   False if partially added or not added.
 */

/**
 * @typedef DeleteCartDetailResponse
 * @property {string} [message]
 * @property {boolean} [success] - True if cart is archived successfully. False
 *   if not archived.
 */

/**
 * @typedef CartItemCountResponse
 * @property {number} [user_cart_items_count] - Item count present in cart
 */

/**
 * @typedef PageCoupon
 * @property {number} [total_item_count]
 * @property {boolean} [has_next]
 * @property {number} [total]
 * @property {number} [current]
 * @property {boolean} [has_previous]
 */

/**
 * @typedef Coupon
 * @property {number} [coupon_amount] - The amount based on cart value
 * @property {number} [coupon_value]
 * @property {string} [title]
 * @property {number} [minimum_cart_value]
 * @property {string} [sub_title]
 * @property {string} [expires_on]
 * @property {string} [message]
 * @property {string} [coupon_type]
 * @property {number} [max_discount_value]
 * @property {string} [coupon_code]
 * @property {boolean} [is_applicable]
 * @property {string} [description]
 * @property {boolean} [is_applied]
 * @property {string} [start_date]
 * @property {string} [end_date]
 * @property {string} [coupon_applicable_message]
 * @property {string} [offer_text]
 * @property {boolean} [is_bank_offer]
 */

/**
 * @typedef GetCouponResponse
 * @property {PageCoupon} [page]
 * @property {Coupon[]} [available_coupon_list]
 */

/**
 * @typedef ApplyCouponRequest
 * @property {string} coupon_code - Coupon code to be applied
 */

/**
 * @typedef OfferPrice
 * @property {string} [currency_symbol] - Currency symbol for currency
 * @property {number} [bulk_effective] - Discounted per unit price for current
 *   offer object
 * @property {string} [currency_code] - Currency code for all amounts
 * @property {number} [effective] - Current per unit price of product after
 *   existing deductions
 * @property {number} [marked] - Original price of product
 */

/**
 * @typedef OfferItem
 * @property {OfferPrice} [price]
 * @property {number} [margin] - Percentage value of discount
 * @property {number} [quantity] - Quantity on which offer is applicable
 * @property {boolean} [best] - Is true for best offer from all offers present
 *   for all sellers
 * @property {number} [total] - Total price of offer quantity with discount
 * @property {boolean} [auto_applied] - Whether offer discount is auto applied in cart
 * @property {string} [type] - Offer type
 */

/**
 * @typedef OfferSeller
 * @property {number} [uid] - Seller id
 * @property {string} [name]
 */

/**
 * @typedef BulkPriceOffer
 * @property {OfferItem[]} [offers]
 * @property {OfferSeller} [seller]
 */

/**
 * @typedef BulkPriceResponse
 * @property {BulkPriceOffer[]} [data] - Consist of offers from multiple seller
 */

/**
 * @typedef RewardPointRequest
 * @property {boolean} points
 */

/**
 * @typedef GeoLocation
 * @property {number} [latitude]
 * @property {number} [longitude]
 */

/**
 * @typedef Address
 * @property {string} [country_iso_code]
 * @property {string} [area]
 * @property {string} [phone]
 * @property {string} [country_phone_code]
 * @property {string} [checkout_mode]
 * @property {string} [address]
 * @property {string} [area_code_slug]
 * @property {GeoLocation} [geo_location]
 * @property {string} [id]
 * @property {Object} [_custom_json]
 * @property {string} [city]
 * @property {string} [sector]
 * @property {string} [state_code] - State code for international address
 * @property {string} [created_by_user_id]
 * @property {string} [landmark]
 * @property {string} [user_id]
 * @property {string} [name]
 * @property {Object} [google_map_point]
 * @property {boolean} [is_active]
 * @property {string[]} [tags]
 * @property {string} [country_code]
 * @property {string} [address_type]
 * @property {string} [country]
 * @property {boolean} [is_default_address]
 * @property {string} [area_code]
 * @property {string} [email]
 * @property {string} [state]
 * @property {Object} [meta]
 */

/**
 * @typedef GetAddressesResponse
 * @property {boolean} [pii_masking]
 * @property {Address[]} [address]
 */

/**
 * @typedef SaveAddressResponse
 * @property {string} [id]
 * @property {boolean} [success]
 * @property {boolean} [is_default_address]
 */

/**
 * @typedef UpdateAddressResponse
 * @property {boolean} [is_updated]
 * @property {string} [id]
 * @property {boolean} [success]
 * @property {boolean} [is_default_address]
 */

/**
 * @typedef DeleteAddressResponse
 * @property {string} [id]
 * @property {boolean} [is_deleted]
 */

/**
 * @typedef SelectCartAddressRequest
 * @property {string} [id]
 * @property {string} [billing_address_id]
 * @property {string} [cart_id]
 */

/**
 * @typedef UpdateCartPaymentRequest
 * @property {string} [id]
 * @property {string} [payment_identifier]
 * @property {string} [address_id]
 * @property {string} [merchant_code]
 * @property {string} [aggregator_name]
 * @property {string} [payment_mode]
 */

/**
 * @typedef CouponValidity
 * @property {string} [title]
 * @property {number} [discount]
 * @property {boolean} [next_validation_required]
 * @property {boolean} [valid]
 * @property {string} [display_message_en]
 * @property {string} [code]
 */

/**
 * @typedef PaymentCouponValidate
 * @property {string} [message]
 * @property {CouponValidity} [coupon_validity]
 * @property {boolean} success
 */

/**
 * @typedef ShipmentResponse
 * @property {number} [shipments]
 * @property {ShipmentPromise} [promise]
 * @property {string} [order_type]
 * @property {string} [box_type]
 * @property {string} [shipment_type]
 * @property {Object} [dp_options]
 * @property {string} [dp_id]
 * @property {CartProductInfo[]} [items]
 * @property {string} [fulfillment_type]
 * @property {number} [fulfillment_id]
 */

/**
 * @typedef CartShipmentsResponse
 * @property {string} [delivery_charge_info]
 * @property {string} [checkout_mode]
 * @property {string} [message]
 * @property {string} [gstin]
 * @property {boolean} [restrict_checkout]
 * @property {string} [last_modified]
 * @property {number} [cart_id]
 * @property {boolean} [is_valid]
 * @property {CartBreakup} [breakup_values]
 * @property {CartCurrency} [currency]
 * @property {string} [id]
 * @property {ShipmentResponse[]} [shipments]
 * @property {PaymentSelectionLock} [payment_selection_lock]
 * @property {string} [coupon_text]
 * @property {ShipmentPromise} [delivery_promise]
 * @property {boolean} [error]
 * @property {string} [comment]
 * @property {boolean} [buy_now]
 * @property {string} [uid]
 * @property {Object} [custom_cart_meta]
 */

/**
 * @typedef CartCheckoutCustomMeta
 * @property {string} key
 * @property {string} value
 */

/**
 * @typedef CustomerDetails
 * @property {string} [email]
 * @property {string} mobile
 * @property {string} [name]
 */

/**
 * @typedef StaffCheckout
 * @property {string} [employee_code]
 * @property {string} user
 * @property {string} last_name
 * @property {string} first_name
 * @property {string} _id
 */

/**
 * @typedef CartCheckoutDetailRequest
 * @property {CartCheckoutCustomMeta[]} [custom_meta]
 * @property {Object} [customer_details] - Customer details
 * @property {string} [merchant_code]
 * @property {string} [id]
 * @property {boolean} [payment_auto_confirm]
 * @property {string} payment_mode
 * @property {string} [aggregator]
 * @property {string} [address_id]
 * @property {string} [callback_url]
 * @property {Object} [delivery_address]
 * @property {StaffCheckout} [staff]
 * @property {string} [order_type]
 * @property {number} [ordering_store]
 * @property {Object} [extra_meta]
 * @property {string} [payment_identifier]
 * @property {Object} [billing_address]
 * @property {Object} [payment_params]
 * @property {string} [billing_address_id]
 * @property {Object} [meta]
 * @property {Object} [payment_extra_identifiers]
 * @property {string} [iin]
 * @property {string} [network]
 * @property {string} [type]
 * @property {string} [card_id]
 */

/**
 * @typedef CheckCart
 * @property {string} [checkout_mode]
 * @property {string} [user_type]
 * @property {string} [cod_message]
 * @property {number} [cart_id]
 * @property {boolean} [is_valid]
 * @property {number} [delivery_charges]
 * @property {string} [id]
 * @property {PaymentSelectionLock} [payment_selection_lock]
 * @property {string} [error_message]
 * @property {ShipmentPromise} [delivery_promise]
 * @property {string} [comment]
 * @property {CartProductInfo[]} [items]
 * @property {string} [uid]
 * @property {number} [delivery_charge_order_value]
 * @property {string} [delivery_charge_info]
 * @property {boolean} [cod_available]
 * @property {boolean} [success]
 * @property {string} [store_code]
 * @property {string} [message]
 * @property {string} [gstin]
 * @property {boolean} [restrict_checkout]
 * @property {string} [last_modified]
 * @property {string} [order_id]
 * @property {CartBreakup} [breakup_values]
 * @property {CartCurrency} [currency]
 * @property {Object[]} [store_emps]
 * @property {string} [coupon_text]
 * @property {boolean} [buy_now]
 * @property {number} [cod_charges]
 * @property {Object} [custom_cart_meta]
 */

/**
 * @typedef CartCheckoutResponse
 * @property {string} [payment_confirm_url]
 * @property {string} [app_intercept_url]
 * @property {boolean} [success]
 * @property {string} [callback_url]
 * @property {string} [message]
 * @property {Object} [data]
 * @property {string} [order_id]
 * @property {CheckCart} [cart]
 */

/**
 * @typedef GiftDetail
 * @property {boolean} [is_gift_applied]
 * @property {string} [gift_message]
 */

/**
 * @typedef ArticleGiftDetail
 * @property {GiftDetail} [article_id]
 */

/**
 * @typedef CartMetaRequest
 * @property {Object} [delivery_slots]
 * @property {ArticleGiftDetail} [gift_details]
 * @property {Object} [pick_up_customer_details] - Customer contact details for
 *   customer pickup at store
 * @property {string} [checkout_mode]
 * @property {string} [comment]
 * @property {string} [gstin]
 * @property {Object} [custom_cart_meta]
 */

/**
 * @typedef CartMetaResponse
 * @property {string} [message]
 * @property {boolean} [is_valid]
 */

/**
 * @typedef CartMetaMissingResponse
 * @property {string[]} [errors]
 */

/**
 * @typedef GetShareCartLinkRequest
 * @property {string} [id] - Cart uid for generating sharing
 * @property {Object} [meta] - Staff, Ordering store or any other data. This
 *   data will be used to generate link as well as sent as shared details.
 */

/**
 * @typedef GetShareCartLinkResponse
 * @property {string} [token] - Short url unique id
 * @property {string} [share_url] - Short shareable final url
 */

/**
 * @typedef SharedCartDetails
 * @property {string} [token] - Short link id
 * @property {Object} [user] - User details of who generated share link
 * @property {string} [created_on]
 * @property {Object} [source] - Share link device and other source information
 * @property {Object} [meta] - Meta data sent while generating share cart link
 */

/**
 * @typedef SharedCart
 * @property {string} [checkout_mode]
 * @property {number} [cart_id]
 * @property {boolean} [is_valid]
 * @property {string} [id]
 * @property {PaymentSelectionLock} [payment_selection_lock]
 * @property {ShipmentPromise} [delivery_promise]
 * @property {string} [comment]
 * @property {CartProductInfo[]} [items]
 * @property {string} [uid]
 * @property {string} [delivery_charge_info]
 * @property {string} [message]
 * @property {string} [gstin]
 * @property {SharedCartDetails} [shared_cart_details]
 * @property {boolean} [restrict_checkout]
 * @property {string} [last_modified]
 * @property {CartBreakup} [breakup_values]
 * @property {CartCurrency} [currency]
 * @property {string} [coupon_text]
 * @property {boolean} [buy_now]
 * @property {Object} [custom_cart_meta]
 */

/**
 * @typedef SharedCartResponse
 * @property {string} [error]
 * @property {SharedCart} [cart]
 */

/**
 * @typedef PriceMinMax
 * @property {number} [min]
 * @property {number} [max]
 */

/**
 * @typedef ItemPriceDetails
 * @property {PriceMinMax} [marked]
 * @property {PriceMinMax} [effective]
 * @property {string} [currency]
 */

/**
 * @typedef FreeGiftItems
 * @property {string} [item_slug] - Item slug
 * @property {string} [item_name] - Item name
 * @property {ItemPriceDetails} [item_price_details]
 * @property {string} [item_brand_name] - Item brand name
 * @property {number} [item_id] - Item id
 * @property {string[]} [item_images_url] - Item images URL
 */

/**
 * @typedef PromotionOffer
 * @property {string} [id] - Promotion id
 * @property {Object} [buy_rules] - Buy rules of promotions
 * @property {string} [offer_text] - Offer title
 * @property {string} [promotion_type] - Promotion type
 * @property {string} [promotion_name] - Name of the promotion
 * @property {string} [promotion_group] - Group of promotion belongs to
 * @property {string} [valid_till] - Datetime ISOString for promotion end date
 * @property {Object[]} [discount_rules] - Discount rules of promotions
 * @property {FreeGiftItems[]} [free_gift_items] - Details of free gift items
 * @property {string} [description] - Offer details including T&C
 */

/**
 * @typedef PromotionOffersResponse
 * @property {PromotionOffer[]} [available_promotions]
 */

/**
 * @typedef PromotionPaymentOffer
 * @property {string} [application_id] - Application id
 * @property {Object[]} [buy_rules] - Buy rules of promotions
 * @property {string} [calculate_on] - Price on which promotion calculated
 * @property {string} [description] - Offer details including T&C
 * @property {Object[]} [discount_rules] - Discount rules of promotions
 * @property {string} [id] - Promotion id
 * @property {string} [offer_text] - Offer title
 * @property {string} [promotion_group] - Group of promotion belongs to
 * @property {string} [promotion_type] - Promotion type
 * @property {string} [promotion_name] - Name of the promotion
 */

/**
 * @typedef PromotionPaymentOffersResponse
 * @property {boolean} [success]
 * @property {PromotionPaymentOffer[]} [promotions]
 */

/**
 * @typedef OperationErrorResponse
 * @property {string} [message]
 * @property {boolean} [success]
 */

/**
 * @typedef LadderPrice
 * @property {string} [currency_symbol] - Currency symbol for currency
 * @property {number} [offer_price] - Discounted per unit price for current offer object
 * @property {string} [currency_code] - Currency code for all amounts
 * @property {number} [effective] - Current per unit price of product after
 *   existing deductions
 * @property {number} [marked] - Original price of product
 */

/**
 * @typedef LadderOfferItem
 * @property {LadderPrice} [price]
 * @property {number} [margin] - Percentage value of discount
 * @property {number} [max_quantity] - Minimum quantity upto which offer is
 *   applicable. If not present that offer is applicable on all quantities
 * @property {number} [min_quantity] - Minimum quantity from which offer is applicable
 * @property {string} [type] - Offer type
 */

/**
 * @typedef LadderPriceOffer
 * @property {string} [id] - Promotion id
 * @property {Object} [buy_rules] - Buy rules of promotions
 * @property {string} [calculate_on] - If this ladder offer is to be calculated
 *   on MRP or ESP price
 * @property {string} [offer_text] - Offer title
 * @property {string} [promotion_group] - Group of promotion belongs to
 * @property {string} [valid_till] - Datetime ISOString for promotion end date
 * @property {Object[]} [discount_rules] - Discount rules of promotions
 * @property {LadderOfferItem[]} [offer_prices]
 * @property {FreeGiftItems[]} [free_gift_items] - Details of free gift items
 * @property {string} [description] - Offer details including T&C
 */

/**
 * @typedef CurrencyInfo
 * @property {string} [code]
 * @property {string} [symbol]
 */

/**
 * @typedef LadderPriceOffers
 * @property {LadderPriceOffer[]} [available_offers]
 * @property {CurrencyInfo} [currency]
 */

/**
 * @typedef PaymentMeta
 * @property {string} [merchant_code]
 * @property {string} [type]
 * @property {string} [payment_gateway]
 * @property {string} [payment_identifier]
 */

/**
 * @typedef PaymentMethod
 * @property {PaymentMeta} payment_meta
 * @property {string} mode
 * @property {string} [payment]
 * @property {number} [amount]
 * @property {string} [name]
 * @property {Object} [payment_extra_identifiers]
 */

/**
 * @typedef CartCheckoutDetailV2Request
 * @property {Object} [custom_meta]
 * @property {Object} [customer_details] - Customer details
 * @property {string} [merchant_code]
 * @property {string} [cart_id]
 * @property {string} [id]
 * @property {boolean} [payment_auto_confirm]
 * @property {PaymentMethod[]} payment_methods
 * @property {string} payment_mode
 * @property {string} [aggregator]
 * @property {string} [address_id]
 * @property {string} [callback_url]
 * @property {Object} [delivery_address]
 * @property {StaffCheckout} [staff]
 * @property {string} [order_type]
 * @property {number} [ordering_store]
 * @property {Object} [extra_meta]
 * @property {string} [payment_identifier]
 * @property {Object} [billing_address]
 * @property {Object} [payment_params]
 * @property {string} [billing_address_id]
 * @property {Object} [meta]
 * @property {string} [iin]
 * @property {string} [network]
 * @property {string} [type]
 * @property {string} [card_id]
 */

class CartApplicationModel {
  /** @returns {BuyRules} */
  static BuyRules() {
    return Joi.object({
      item_criteria: Joi.any(),
      cart_conditions: Joi.any(),
    });
  }

  /** @returns {DiscountRulesApp} */
  static DiscountRulesApp() {
    return Joi.object({
      matched_buy_rules: Joi.array().items(Joi.string().allow("")),
      raw_offer: Joi.any(),
      offer: Joi.any(),
      item_criteria: Joi.any(),
    });
  }

  /** @returns {Ownership} */
  static Ownership() {
    return Joi.object({
      payable_category: Joi.string().allow(""),
      payable_by: Joi.string().allow(""),
    });
  }

  /** @returns {AppliedFreeArticles} */
  static AppliedFreeArticles() {
    return Joi.object({
      free_gift_item_details: CartApplicationModel.FreeGiftItems(),
      parent_item_identifier: Joi.string().allow(""),
      quantity: Joi.number(),
      article_id: Joi.string().allow(""),
    });
  }

  /** @returns {AppliedPromotion} */
  static AppliedPromotion() {
    return Joi.object({
      promo_id: Joi.string().allow(""),
      buy_rules: Joi.array().items(CartApplicationModel.BuyRules()),
      offer_text: Joi.string().allow(""),
      promotion_group: Joi.string().allow(""),
      mrp_promotion: Joi.boolean(),
      promotion_name: Joi.string().allow(""),
      amount: Joi.number(),
      discount_rules: Joi.array().items(
        CartApplicationModel.DiscountRulesApp()
      ),
      ownership: CartApplicationModel.Ownership(),
      article_quantity: Joi.number(),
      applied_free_articles: Joi.array().items(
        CartApplicationModel.AppliedFreeArticles()
      ),
      promotion_type: Joi.string().allow(""),
      meta: Joi.any(),
      code: Joi.string().allow("").allow(null),
    });
  }

  /** @returns {PaymentSelectionLock} */
  static PaymentSelectionLock() {
    return Joi.object({
      enabled: Joi.boolean(),
      default_options: Joi.string().allow(""),
      payment_identifier: Joi.string().allow(""),
    });
  }

  /** @returns {PromiseFormatted} */
  static PromiseFormatted() {
    return Joi.object({
      max: Joi.string().allow(""),
      min: Joi.string().allow(""),
    });
  }

  /** @returns {PromiseISOFormat} */
  static PromiseISOFormat() {
    return Joi.object({
      max: Joi.string().allow(""),
      min: Joi.string().allow(""),
    });
  }

  /** @returns {PromiseTimestamp} */
  static PromiseTimestamp() {
    return Joi.object({
      max: Joi.number(),
      min: Joi.number(),
    });
  }

  /** @returns {ShipmentPromise} */
  static ShipmentPromise() {
    return Joi.object({
      formatted: CartApplicationModel.PromiseFormatted(),
      timestamp: CartApplicationModel.PromiseTimestamp(),
      iso: CartApplicationModel.PromiseISOFormat(),
    });
  }

  /** @returns {BasePrice} */
  static BasePrice() {
    return Joi.object({
      effective: Joi.number(),
      currency_symbol: Joi.string().allow(""),
      marked: Joi.number(),
      currency_code: Joi.string().allow(""),
    });
  }

  /** @returns {ArticlePriceInfo} */
  static ArticlePriceInfo() {
    return Joi.object({
      base: CartApplicationModel.BasePrice(),
      converted: CartApplicationModel.BasePrice(),
    });
  }

  /** @returns {BaseInfo} */
  static BaseInfo() {
    return Joi.object({
      uid: Joi.number(),
      name: Joi.string().allow(""),
    });
  }

  /** @returns {StoreInfo} */
  static StoreInfo() {
    return Joi.object({
      store_code: Joi.string().allow(""),
      uid: Joi.number(),
      name: Joi.string().allow(""),
    });
  }

  /** @returns {ProductArticle} */
  static ProductArticle() {
    return Joi.object({
      price: CartApplicationModel.ArticlePriceInfo(),
      product_group_tags: Joi.array().items(Joi.string().allow("")),
      extra_meta: Joi.any(),
      quantity: Joi.number(),
      _custom_json: Joi.any(),
      meta: Joi.any(),
      size: Joi.string().allow(""),
      mto_quantity: Joi.number(),
      seller: CartApplicationModel.BaseInfo(),
      seller_identifier: Joi.string().allow(""),
      parent_item_identifiers: Joi.any(),
      identifier: Joi.any(),
      store: CartApplicationModel.StoreInfo(),
      cart_item_meta: Joi.any(),
      uid: Joi.string().allow(""),
      gift_card: Joi.any(),
      is_gift_visible: Joi.boolean(),
      type: Joi.string().allow(""),
      tags: Joi.array().items(Joi.string().allow("")),
    });
  }

  /** @returns {CartProductIdentifer} */
  static CartProductIdentifer() {
    return Joi.object({
      identifier: Joi.string().allow(""),
    });
  }

  /** @returns {PromoMeta} */
  static PromoMeta() {
    return Joi.object({
      message: Joi.string().allow(""),
    });
  }

  /** @returns {ChargesAmount} */
  static ChargesAmount() {
    return Joi.object({
      value: Joi.number(),
      currency: Joi.string().allow(""),
    });
  }

  /** @returns {Charges} */
  static Charges() {
    return Joi.object({
      meta: Joi.any(),
      amount: CartApplicationModel.ChargesAmount(),
      name: Joi.string().allow(""),
      allow_refund: Joi.boolean(),
      code: Joi.string().allow(""),
      type: Joi.string().allow(""),
    });
  }

  /** @returns {ProductPrice} */
  static ProductPrice() {
    return Joi.object({
      currency_symbol: Joi.string().allow(""),
      selling: Joi.number(),
      currency_code: Joi.string().allow(""),
      add_on: Joi.number(),
      effective: Joi.number(),
      marked: Joi.number(),
    });
  }

  /** @returns {ProductPriceInfo} */
  static ProductPriceInfo() {
    return Joi.object({
      base: CartApplicationModel.ProductPrice(),
      converted: CartApplicationModel.ProductPrice(),
    });
  }

  /** @returns {ProductPricePerUnit} */
  static ProductPricePerUnit() {
    return Joi.object({
      currency_symbol: Joi.string().allow(""),
      selling_price: Joi.number(),
      currency_code: Joi.string().allow(""),
      add_on: Joi.number(),
      effective: Joi.number(),
      marked: Joi.number(),
    });
  }

  /** @returns {ProductPricePerUnitInfo} */
  static ProductPricePerUnitInfo() {
    return Joi.object({
      base: CartApplicationModel.ProductPricePerUnit(),
      converted: CartApplicationModel.ProductPricePerUnit(),
    });
  }

  /** @returns {ProductAvailabilitySize} */
  static ProductAvailabilitySize() {
    return Joi.object({
      display: Joi.string().allow(""),
      value: Joi.string().allow(""),
      is_available: Joi.boolean(),
    });
  }

  /** @returns {ProductAvailability} */
  static ProductAvailability() {
    return Joi.object({
      out_of_stock: Joi.boolean(),
      deliverable: Joi.boolean(),
      available_sizes: Joi.array().items(
        CartApplicationModel.ProductAvailabilitySize()
      ),
      is_valid: Joi.boolean(),
      other_store_quantity: Joi.number(),
      sizes: Joi.array().items(Joi.string().allow("")),
    });
  }

  /** @returns {ActionQuery} */
  static ActionQuery() {
    return Joi.object({
      product_slug: Joi.array().items(Joi.string().allow("")),
    });
  }

  /** @returns {ProductAction} */
  static ProductAction() {
    return Joi.object({
      query: CartApplicationModel.ActionQuery(),
      url: Joi.string().allow(""),
      type: Joi.string().allow(""),
    });
  }

  /** @returns {Tags} */
  static Tags() {
    return Joi.object({
      tags: Joi.any(),
    });
  }

  /** @returns {ProductImage} */
  static ProductImage() {
    return Joi.object({
      secure_url: Joi.string().allow(""),
      aspect_ratio: Joi.string().allow(""),
      url: Joi.string().allow(""),
    });
  }

  /** @returns {CategoryInfo} */
  static CategoryInfo() {
    return Joi.object({
      uid: Joi.number(),
      name: Joi.string().allow(""),
    });
  }

  /** @returns {CartProduct} */
  static CartProduct() {
    return Joi.object({
      _custom_json: Joi.any(),
      brand: CartApplicationModel.BaseInfo(),
      action: CartApplicationModel.ProductAction(),
      teaser_tag: CartApplicationModel.Tags(),
      slug: Joi.string().allow(""),
      images: Joi.array().items(CartApplicationModel.ProductImage()),
      uid: Joi.number(),
      name: Joi.string().allow(""),
      item_code: Joi.string().allow("").allow(null),
      categories: Joi.array().items(CartApplicationModel.CategoryInfo()),
      tags: Joi.array().items(Joi.string().allow("")),
      type: Joi.string().allow(""),
      attributes: Joi.any(),
    });
  }

  /** @returns {CouponDetails} */
  static CouponDetails() {
    return Joi.object({
      discount_single_quantity: Joi.number(),
      code: Joi.string().allow(""),
      discount_total_quantity: Joi.number(),
    });
  }

  /** @returns {CartProductInfo} */
  static CartProductInfo() {
    return Joi.object({
      article: CartApplicationModel.ProductArticle(),
      moq: Joi.any(),
      identifiers: CartApplicationModel.CartProductIdentifer().required(),
      promo_meta: CartApplicationModel.PromoMeta(),
      price: CartApplicationModel.ProductPriceInfo(),
      quantity: Joi.number(),
      charges: Joi.array().items(CartApplicationModel.Charges()),
      discount: Joi.string().allow(""),
      availability: CartApplicationModel.ProductAvailability(),
      delivery_promise: CartApplicationModel.ShipmentPromise(),
      product: CartApplicationModel.CartProduct(),
      product_ean_id: Joi.string().allow(""),
      bulk_offer: Joi.any(),
      parent_item_identifiers: Joi.any(),
      coupon: CartApplicationModel.CouponDetails(),
      custom_order: Joi.any(),
      coupon_message: Joi.string().allow(""),
      key: Joi.string().allow(""),
      message: Joi.string().allow(""),
      is_set: Joi.boolean(),
      price_per_unit: CartApplicationModel.ProductPricePerUnitInfo(),
      promotions_applied: Joi.array().items(
        CartApplicationModel.AppliedPromotion()
      ),
    });
  }

  /** @returns {DisplayBreakup} */
  static DisplayBreakup() {
    return Joi.object({
      currency_symbol: Joi.string().allow(""),
      key: Joi.string().allow(""),
      display: Joi.string().allow(""),
      message: Joi.array().items(Joi.string().allow("")),
      currency_code: Joi.string().allow(""),
      value: Joi.number(),
      preset: Joi.number(),
    });
  }

  /** @returns {RawBreakup} */
  static RawBreakup() {
    return Joi.object({
      vog: Joi.number(),
      subtotal: Joi.number(),
      fynd_cash: Joi.number(),
      discount: Joi.number(),
      convenience_fee: Joi.number(),
      delivery_charge: Joi.number(),
      gst_charges: Joi.number(),
      mrp_total: Joi.number(),
      mop_total: Joi.number(),
      total_charge: Joi.number(),
      coupon: Joi.number(),
      total: Joi.number(),
      gift_card: Joi.number(),
      you_saved: Joi.number(),
      cod_charge: Joi.number(),
    });
  }

  /** @returns {CouponBreakup} */
  static CouponBreakup() {
    return Joi.object({
      coupon_value: Joi.number(),
      title: Joi.string().allow("").allow(null),
      sub_title: Joi.string().allow("").allow(null),
      minimum_cart_value: Joi.number(),
      message: Joi.string().allow(""),
      coupon_type: Joi.string().allow("").allow(null),
      uid: Joi.string().allow(""),
      value: Joi.number(),
      max_discount_value: Joi.number(),
      is_applied: Joi.boolean(),
      description: Joi.string().allow("").allow(null),
      code: Joi.string().allow(""),
      type: Joi.string().allow(""),
    });
  }

  /** @returns {LoyaltyPoints} */
  static LoyaltyPoints() {
    return Joi.object({
      total: Joi.number(),
      description: Joi.string().allow(""),
      applicable: Joi.number(),
      is_applied: Joi.boolean(),
    });
  }

  /** @returns {CartBreakup} */
  static CartBreakup() {
    return Joi.object({
      display: Joi.array().items(CartApplicationModel.DisplayBreakup()),
      raw: CartApplicationModel.RawBreakup(),
      coupon: CartApplicationModel.CouponBreakup(),
      loyalty_points: CartApplicationModel.LoyaltyPoints(),
    });
  }

  /** @returns {CartCurrency} */
  static CartCurrency() {
    return Joi.object({
      code: Joi.string().allow(""),
      symbol: Joi.string().allow(""),
    });
  }

  /** @returns {CartDetailCoupon} */
  static CartDetailCoupon() {
    return Joi.object({
      cashback_amount: Joi.number(),
      cashback_message_primary: Joi.string().allow(""),
      cashback_message_secondary: Joi.string().allow(""),
      coupon_code: Joi.string().allow(""),
      coupon_description: Joi.string().allow(""),
      coupon_id: Joi.string().allow(""),
      coupon_subtitle: Joi.string().allow(""),
      coupon_title: Joi.string().allow(""),
      coupon_type: Joi.string().allow(""),
      coupon_value: Joi.number(),
      discount: Joi.number(),
      is_applied: Joi.boolean(),
      is_valid: Joi.boolean(),
      maximum_discount_value: Joi.number(),
      message: Joi.string().allow(""),
      minimum_cart_value: Joi.number(),
    });
  }

  /** @returns {ChargesThreshold} */
  static ChargesThreshold() {
    return Joi.object({
      charges: Joi.number(),
      threshold: Joi.number(),
    });
  }

  /** @returns {DeliveryChargesConfig} */
  static DeliveryChargesConfig() {
    return Joi.object({
      enabled: Joi.boolean(),
      charges: Joi.array().items(CartApplicationModel.ChargesThreshold()),
    });
  }

  /** @returns {CartCommonConfig} */
  static CartCommonConfig() {
    return Joi.object({
      delivery_charges_config: CartApplicationModel.DeliveryChargesConfig(),
    });
  }

  /** @returns {CartDetailResponse} */
  static CartDetailResponse() {
    return Joi.object({
      cart_id: Joi.number(),
      uid: Joi.string().allow(""),
      applied_promo_details: Joi.array().items(
        CartApplicationModel.AppliedPromotion()
      ),
      checkout_mode: Joi.string().allow(""),
      pan_no: Joi.string().allow(""),
      is_valid: Joi.boolean(),
      id: Joi.string().allow(""),
      payment_selection_lock: CartApplicationModel.PaymentSelectionLock(),
      delivery_promise: CartApplicationModel.ShipmentPromise(),
      comment: Joi.string().allow(""),
      items: Joi.array().items(CartApplicationModel.CartProductInfo()),
      delivery_charge_info: Joi.string().allow(""),
      common_config: CartApplicationModel.CartCommonConfig(),
      coupon: CartApplicationModel.CartDetailCoupon(),
      message: Joi.string().allow(""),
      notification: Joi.any(),
      staff_user_id: Joi.string().allow(""),
      success: Joi.boolean(),
      gstin: Joi.string().allow(""),
      restrict_checkout: Joi.boolean(),
      last_modified: Joi.string().allow(""),
      breakup_values: CartApplicationModel.CartBreakup(),
      currency: CartApplicationModel.CartCurrency(),
      coupon_text: Joi.string().allow(""),
      buy_now: Joi.boolean(),
      pan_config: Joi.any(),
      custom_cart_meta: Joi.any(),
    });
  }

  /** @returns {AddProductCart} */
  static AddProductCart() {
    return Joi.object({
      article_assignment: Joi.any(),
      product_group_tags: Joi.array().items(Joi.string().allow("").allow(null)),
      extra_meta: Joi.any(),
      quantity: Joi.number(),
      _custom_json: Joi.any(),
      item_size: Joi.string().allow(""),
      store_id: Joi.number(),
      display: Joi.string().allow(""),
      article_id: Joi.string().allow(""),
      parent_item_identifiers: Joi.array().items(
        Joi.object().pattern(/\S/, Joi.string().allow(""))
      ),
      seller_id: Joi.number(),
      pos: Joi.boolean(),
      item_id: Joi.number(),
      meta: Joi.any(),
      seller_identifier: Joi.string().allow(""),
    });
  }

  /** @returns {AddCartRequest} */
  static AddCartRequest() {
    return Joi.object({
      items: Joi.array().items(CartApplicationModel.AddProductCart()),
      new_cart: Joi.boolean(),
    });
  }

  /** @returns {AddCartDetailResponse} */
  static AddCartDetailResponse() {
    return Joi.object({
      message: Joi.string().allow(""),
      partial: Joi.boolean(),
      cart: CartApplicationModel.CartDetailResponse(),
      success: Joi.boolean(),
    });
  }

  /** @returns {UpdateProductCart} */
  static UpdateProductCart() {
    return Joi.object({
      extra_meta: Joi.any(),
      _custom_json: Joi.any(),
      quantity: Joi.number(),
      item_size: Joi.string().allow(""),
      item_index: Joi.number(),
      identifiers: CartApplicationModel.CartProductIdentifer().required(),
      article_id: Joi.string().allow(""),
      parent_item_identifiers: Joi.any(),
      item_id: Joi.number(),
      meta: Joi.any(),
    });
  }

  /** @returns {UpdateCartRequest} */
  static UpdateCartRequest() {
    return Joi.object({
      items: Joi.array().items(CartApplicationModel.UpdateProductCart()),
      operation: Joi.string().allow("").required(),
    });
  }

  /** @returns {UpdateCartDetailResponse} */
  static UpdateCartDetailResponse() {
    return Joi.object({
      message: Joi.string().allow(""),
      cart: CartApplicationModel.CartDetailResponse(),
      success: Joi.boolean(),
    });
  }

  /** @returns {DeleteCartDetailResponse} */
  static DeleteCartDetailResponse() {
    return Joi.object({
      message: Joi.string().allow(""),
      success: Joi.boolean(),
    });
  }

  /** @returns {CartItemCountResponse} */
  static CartItemCountResponse() {
    return Joi.object({
      user_cart_items_count: Joi.number(),
    });
  }

  /** @returns {PageCoupon} */
  static PageCoupon() {
    return Joi.object({
      total_item_count: Joi.number(),
      has_next: Joi.boolean(),
      total: Joi.number(),
      current: Joi.number(),
      has_previous: Joi.boolean(),
    });
  }

  /** @returns {Coupon} */
  static Coupon() {
    return Joi.object({
      coupon_amount: Joi.number(),
      coupon_value: Joi.number(),
      title: Joi.string().allow(""),
      minimum_cart_value: Joi.number(),
      sub_title: Joi.string().allow(""),
      expires_on: Joi.string().allow(""),
      message: Joi.string().allow(""),
      coupon_type: Joi.string().allow("").allow(null),
      max_discount_value: Joi.number(),
      coupon_code: Joi.string().allow(""),
      is_applicable: Joi.boolean(),
      description: Joi.string().allow("").allow(null),
      is_applied: Joi.boolean(),
      start_date: Joi.string().allow("").allow(null),
      end_date: Joi.string().allow("").allow(null),
      coupon_applicable_message: Joi.string().allow(""),
      offer_text: Joi.string().allow(""),
      is_bank_offer: Joi.boolean(),
    });
  }

  /** @returns {GetCouponResponse} */
  static GetCouponResponse() {
    return Joi.object({
      page: CartApplicationModel.PageCoupon(),
      available_coupon_list: Joi.array().items(CartApplicationModel.Coupon()),
    });
  }

  /** @returns {ApplyCouponRequest} */
  static ApplyCouponRequest() {
    return Joi.object({
      coupon_code: Joi.string().allow("").required(),
    });
  }

  /** @returns {OfferPrice} */
  static OfferPrice() {
    return Joi.object({
      currency_symbol: Joi.string().allow(""),
      bulk_effective: Joi.number(),
      currency_code: Joi.string().allow(""),
      effective: Joi.number(),
      marked: Joi.number(),
    });
  }

  /** @returns {OfferItem} */
  static OfferItem() {
    return Joi.object({
      price: CartApplicationModel.OfferPrice(),
      margin: Joi.number(),
      quantity: Joi.number(),
      best: Joi.boolean(),
      total: Joi.number(),
      auto_applied: Joi.boolean(),
      type: Joi.string().allow(""),
    });
  }

  /** @returns {OfferSeller} */
  static OfferSeller() {
    return Joi.object({
      uid: Joi.number(),
      name: Joi.string().allow(""),
    });
  }

  /** @returns {BulkPriceOffer} */
  static BulkPriceOffer() {
    return Joi.object({
      offers: Joi.array().items(CartApplicationModel.OfferItem()),
      seller: CartApplicationModel.OfferSeller(),
    });
  }

  /** @returns {BulkPriceResponse} */
  static BulkPriceResponse() {
    return Joi.object({
      data: Joi.array().items(CartApplicationModel.BulkPriceOffer()),
    });
  }

  /** @returns {RewardPointRequest} */
  static RewardPointRequest() {
    return Joi.object({
      points: Joi.boolean().required(),
    });
  }

  /** @returns {GeoLocation} */
  static GeoLocation() {
    return Joi.object({
      latitude: Joi.number(),
      longitude: Joi.number(),
    });
  }

  /** @returns {Address} */
  static Address() {
    return Joi.object({
      country_iso_code: Joi.string().allow(""),
      area: Joi.string().allow(""),
      phone: Joi.string().allow(""),
      country_phone_code: Joi.string().allow(""),
      checkout_mode: Joi.string().allow(""),
      address: Joi.string().allow(""),
      area_code_slug: Joi.string().allow(""),
      geo_location: CartApplicationModel.GeoLocation(),
      id: Joi.string().allow(""),
      _custom_json: Joi.any(),
      city: Joi.string().allow(""),
      sector: Joi.string().allow(""),
      state_code: Joi.string().allow(""),
      created_by_user_id: Joi.string().allow(""),
      landmark: Joi.string().allow(""),
      user_id: Joi.string().allow(""),
      name: Joi.string().allow(""),
      google_map_point: Joi.any(),
      is_active: Joi.boolean(),
      tags: Joi.array().items(Joi.string().allow("")),
      country_code: Joi.string().allow(""),
      address_type: Joi.string().allow(""),
      country: Joi.string().allow(""),
      is_default_address: Joi.boolean(),
      area_code: Joi.string().allow(""),
      email: Joi.string().allow(""),
      state: Joi.string().allow(""),
      meta: Joi.any(),
    });
  }

  /** @returns {GetAddressesResponse} */
  static GetAddressesResponse() {
    return Joi.object({
      pii_masking: Joi.boolean(),
      address: Joi.array().items(CartApplicationModel.Address()),
    });
  }

  /** @returns {SaveAddressResponse} */
  static SaveAddressResponse() {
    return Joi.object({
      id: Joi.string().allow(""),
      success: Joi.boolean(),
      is_default_address: Joi.boolean(),
    });
  }

  /** @returns {UpdateAddressResponse} */
  static UpdateAddressResponse() {
    return Joi.object({
      is_updated: Joi.boolean(),
      id: Joi.string().allow(""),
      success: Joi.boolean(),
      is_default_address: Joi.boolean(),
    });
  }

  /** @returns {DeleteAddressResponse} */
  static DeleteAddressResponse() {
    return Joi.object({
      id: Joi.string().allow(""),
      is_deleted: Joi.boolean(),
    });
  }

  /** @returns {SelectCartAddressRequest} */
  static SelectCartAddressRequest() {
    return Joi.object({
      id: Joi.string().allow(""),
      billing_address_id: Joi.string().allow(""),
      cart_id: Joi.string().allow(""),
    });
  }

  /** @returns {UpdateCartPaymentRequest} */
  static UpdateCartPaymentRequest() {
    return Joi.object({
      id: Joi.string().allow(""),
      payment_identifier: Joi.string().allow("").allow(null),
      address_id: Joi.string().allow(""),
      merchant_code: Joi.string().allow(""),
      aggregator_name: Joi.string().allow(""),
      payment_mode: Joi.string().allow(""),
    });
  }

  /** @returns {CouponValidity} */
  static CouponValidity() {
    return Joi.object({
      title: Joi.string().allow(""),
      discount: Joi.number(),
      next_validation_required: Joi.boolean().allow(null),
      valid: Joi.boolean(),
      display_message_en: Joi.string().allow("").allow(null),
      code: Joi.string().allow("").allow(null),
    });
  }

  /** @returns {PaymentCouponValidate} */
  static PaymentCouponValidate() {
    return Joi.object({
      message: Joi.string().allow(""),
      coupon_validity: CartApplicationModel.CouponValidity(),
      success: Joi.boolean().required(),
    });
  }

  /** @returns {ShipmentResponse} */
  static ShipmentResponse() {
    return Joi.object({
      shipments: Joi.number(),
      promise: CartApplicationModel.ShipmentPromise(),
      order_type: Joi.string().allow(""),
      box_type: Joi.string().allow("").allow(null),
      shipment_type: Joi.string().allow(""),
      dp_options: Joi.any().allow(null),
      dp_id: Joi.string().allow("").allow(null),
      items: Joi.array().items(CartApplicationModel.CartProductInfo()),
      fulfillment_type: Joi.string().allow(""),
      fulfillment_id: Joi.number(),
    });
  }

  /** @returns {CartShipmentsResponse} */
  static CartShipmentsResponse() {
    return Joi.object({
      delivery_charge_info: Joi.string().allow(""),
      checkout_mode: Joi.string().allow(""),
      message: Joi.string().allow(""),
      gstin: Joi.string().allow(""),
      restrict_checkout: Joi.boolean(),
      last_modified: Joi.string().allow(""),
      cart_id: Joi.number(),
      is_valid: Joi.boolean(),
      breakup_values: CartApplicationModel.CartBreakup(),
      currency: CartApplicationModel.CartCurrency(),
      id: Joi.string().allow(""),
      shipments: Joi.array().items(CartApplicationModel.ShipmentResponse()),
      payment_selection_lock: CartApplicationModel.PaymentSelectionLock(),
      coupon_text: Joi.string().allow(""),
      delivery_promise: CartApplicationModel.ShipmentPromise(),
      error: Joi.boolean(),
      comment: Joi.string().allow(""),
      buy_now: Joi.boolean(),
      uid: Joi.string().allow(""),
      custom_cart_meta: Joi.any(),
    });
  }

  /** @returns {CartCheckoutCustomMeta} */
  static CartCheckoutCustomMeta() {
    return Joi.object({
      key: Joi.string().allow("").required(),
      value: Joi.string().allow("").required(),
    });
  }

  /** @returns {CustomerDetails} */
  static CustomerDetails() {
    return Joi.object({
      email: Joi.string().allow(""),
      mobile: Joi.string().allow("").required(),
      name: Joi.string().allow(""),
    });
  }

  /** @returns {StaffCheckout} */
  static StaffCheckout() {
    return Joi.object({
      employee_code: Joi.string().allow(""),
      user: Joi.string().allow("").required(),
      last_name: Joi.string().allow("").required(),
      first_name: Joi.string().allow("").required(),
      _id: Joi.string().allow("").required(),
    });
  }

  /** @returns {CartCheckoutDetailRequest} */
  static CartCheckoutDetailRequest() {
    return Joi.object({
      custom_meta: Joi.array().items(
        CartApplicationModel.CartCheckoutCustomMeta()
      ),
      customer_details: Joi.any(),
      merchant_code: Joi.string().allow(""),
      id: Joi.string().allow(""),
      payment_auto_confirm: Joi.boolean(),
      payment_mode: Joi.string().allow("").required(),
      aggregator: Joi.string().allow(""),
      address_id: Joi.string().allow(""),
      callback_url: Joi.string().allow(""),
      delivery_address: Joi.any(),
      staff: CartApplicationModel.StaffCheckout(),
      order_type: Joi.string().allow(""),
      ordering_store: Joi.number(),
      extra_meta: Joi.any(),
      payment_identifier: Joi.string().allow(""),
      billing_address: Joi.any(),
      payment_params: Joi.any(),
      billing_address_id: Joi.string().allow(""),
      meta: Joi.any(),
      payment_extra_identifiers: Joi.any(),
      iin: Joi.string().allow(""),
      network: Joi.string().allow(""),
      type: Joi.string().allow(""),
      card_id: Joi.string().allow(""),
    });
  }

  /** @returns {CheckCart} */
  static CheckCart() {
    return Joi.object({
      checkout_mode: Joi.string().allow(""),
      user_type: Joi.string().allow(""),
      cod_message: Joi.string().allow(""),
      cart_id: Joi.number(),
      is_valid: Joi.boolean(),
      delivery_charges: Joi.number(),
      id: Joi.string().allow(""),
      payment_selection_lock: CartApplicationModel.PaymentSelectionLock(),
      error_message: Joi.string().allow(""),
      delivery_promise: CartApplicationModel.ShipmentPromise(),
      comment: Joi.string().allow(""),
      items: Joi.array().items(CartApplicationModel.CartProductInfo()),
      uid: Joi.string().allow(""),
      delivery_charge_order_value: Joi.number(),
      delivery_charge_info: Joi.string().allow(""),
      cod_available: Joi.boolean(),
      success: Joi.boolean(),
      store_code: Joi.string().allow(""),
      message: Joi.string().allow(""),
      gstin: Joi.string().allow(""),
      restrict_checkout: Joi.boolean(),
      last_modified: Joi.string().allow(""),
      order_id: Joi.string().allow(""),
      breakup_values: CartApplicationModel.CartBreakup(),
      currency: CartApplicationModel.CartCurrency(),
      store_emps: Joi.array().items(Joi.any()),
      coupon_text: Joi.string().allow(""),
      buy_now: Joi.boolean(),
      cod_charges: Joi.number(),
      custom_cart_meta: Joi.any(),
    });
  }

  /** @returns {CartCheckoutResponse} */
  static CartCheckoutResponse() {
    return Joi.object({
      payment_confirm_url: Joi.string().allow(""),
      app_intercept_url: Joi.string().allow(""),
      success: Joi.boolean(),
      callback_url: Joi.string().allow(""),
      message: Joi.string().allow(""),
      data: Joi.any(),
      order_id: Joi.string().allow(""),
      cart: CartApplicationModel.CheckCart(),
    });
  }

  /** @returns {GiftDetail} */
  static GiftDetail() {
    return Joi.object({
      is_gift_applied: Joi.boolean(),
      gift_message: Joi.string().allow(""),
    });
  }

  /** @returns {ArticleGiftDetail} */
  static ArticleGiftDetail() {
    return Joi.object({
      article_id: CartApplicationModel.GiftDetail(),
    });
  }

  /** @returns {CartMetaRequest} */
  static CartMetaRequest() {
    return Joi.object({
      delivery_slots: Joi.any(),
      gift_details: CartApplicationModel.ArticleGiftDetail(),
      pick_up_customer_details: Joi.any(),
      checkout_mode: Joi.string().allow(""),
      comment: Joi.string().allow(""),
      gstin: Joi.string().allow(""),
      custom_cart_meta: Joi.any(),
    });
  }

  /** @returns {CartMetaResponse} */
  static CartMetaResponse() {
    return Joi.object({
      message: Joi.string().allow(""),
      is_valid: Joi.boolean(),
    });
  }

  /** @returns {CartMetaMissingResponse} */
  static CartMetaMissingResponse() {
    return Joi.object({
      errors: Joi.array().items(Joi.string().allow("")),
    });
  }

  /** @returns {GetShareCartLinkRequest} */
  static GetShareCartLinkRequest() {
    return Joi.object({
      id: Joi.string().allow(""),
      meta: Joi.any(),
    });
  }

  /** @returns {GetShareCartLinkResponse} */
  static GetShareCartLinkResponse() {
    return Joi.object({
      token: Joi.string().allow(""),
      share_url: Joi.string().allow(""),
    });
  }

  /** @returns {SharedCartDetails} */
  static SharedCartDetails() {
    return Joi.object({
      token: Joi.string().allow(""),
      user: Joi.any(),
      created_on: Joi.string().allow(""),
      source: Joi.any(),
      meta: Joi.any(),
    });
  }

  /** @returns {SharedCart} */
  static SharedCart() {
    return Joi.object({
      checkout_mode: Joi.string().allow(""),
      cart_id: Joi.number(),
      is_valid: Joi.boolean(),
      id: Joi.string().allow(""),
      payment_selection_lock: CartApplicationModel.PaymentSelectionLock(),
      delivery_promise: CartApplicationModel.ShipmentPromise(),
      comment: Joi.string().allow(""),
      items: Joi.array().items(CartApplicationModel.CartProductInfo()),
      uid: Joi.string().allow(""),
      delivery_charge_info: Joi.string().allow(""),
      message: Joi.string().allow(""),
      gstin: Joi.string().allow(""),
      shared_cart_details: CartApplicationModel.SharedCartDetails(),
      restrict_checkout: Joi.boolean(),
      last_modified: Joi.string().allow(""),
      breakup_values: CartApplicationModel.CartBreakup(),
      currency: CartApplicationModel.CartCurrency(),
      coupon_text: Joi.string().allow(""),
      buy_now: Joi.boolean(),
      custom_cart_meta: Joi.any(),
    });
  }

  /** @returns {SharedCartResponse} */
  static SharedCartResponse() {
    return Joi.object({
      error: Joi.string().allow(""),
      cart: CartApplicationModel.SharedCart(),
    });
  }

  /** @returns {PriceMinMax} */
  static PriceMinMax() {
    return Joi.object({
      min: Joi.number(),
      max: Joi.number(),
    });
  }

  /** @returns {ItemPriceDetails} */
  static ItemPriceDetails() {
    return Joi.object({
      marked: CartApplicationModel.PriceMinMax(),
      effective: CartApplicationModel.PriceMinMax(),
      currency: Joi.string().allow(""),
    });
  }

  /** @returns {FreeGiftItems} */
  static FreeGiftItems() {
    return Joi.object({
      item_slug: Joi.string().allow(""),
      item_name: Joi.string().allow(""),
      item_price_details: CartApplicationModel.ItemPriceDetails(),
      item_brand_name: Joi.string().allow(""),
      item_id: Joi.number(),
      item_images_url: Joi.array().items(Joi.string().allow("")),
    });
  }

  /** @returns {PromotionOffer} */
  static PromotionOffer() {
    return Joi.object({
      id: Joi.string().allow(""),
      buy_rules: Joi.any(),
      offer_text: Joi.string().allow(""),
      promotion_type: Joi.string().allow(""),
      promotion_name: Joi.string().allow(""),
      promotion_group: Joi.string().allow(""),
      valid_till: Joi.string().allow(""),
      discount_rules: Joi.array().items(Joi.any()),
      free_gift_items: Joi.array().items(CartApplicationModel.FreeGiftItems()),
      description: Joi.string().allow(""),
    });
  }

  /** @returns {PromotionOffersResponse} */
  static PromotionOffersResponse() {
    return Joi.object({
      available_promotions: Joi.array().items(
        CartApplicationModel.PromotionOffer()
      ),
    });
  }

  /** @returns {PromotionPaymentOffer} */
  static PromotionPaymentOffer() {
    return Joi.object({
      application_id: Joi.string().allow(""),
      buy_rules: Joi.array().items(Joi.any()),
      calculate_on: Joi.string().allow(""),
      description: Joi.string().allow(""),
      discount_rules: Joi.array().items(Joi.any()),
      id: Joi.string().allow(""),
      offer_text: Joi.string().allow(""),
      promotion_group: Joi.string().allow(""),
      promotion_type: Joi.string().allow(""),
      promotion_name: Joi.string().allow(""),
    });
  }

  /** @returns {PromotionPaymentOffersResponse} */
  static PromotionPaymentOffersResponse() {
    return Joi.object({
      success: Joi.boolean(),
      promotions: Joi.array().items(
        CartApplicationModel.PromotionPaymentOffer()
      ),
    });
  }

  /** @returns {OperationErrorResponse} */
  static OperationErrorResponse() {
    return Joi.object({
      message: Joi.string().allow(""),
      success: Joi.boolean(),
    });
  }

  /** @returns {LadderPrice} */
  static LadderPrice() {
    return Joi.object({
      currency_symbol: Joi.string().allow(""),
      offer_price: Joi.number(),
      currency_code: Joi.string().allow(""),
      effective: Joi.number(),
      marked: Joi.number(),
    });
  }

  /** @returns {LadderOfferItem} */
  static LadderOfferItem() {
    return Joi.object({
      price: CartApplicationModel.LadderPrice(),
      margin: Joi.number(),
      max_quantity: Joi.number(),
      min_quantity: Joi.number(),
      type: Joi.string().allow(""),
    });
  }

  /** @returns {LadderPriceOffer} */
  static LadderPriceOffer() {
    return Joi.object({
      id: Joi.string().allow(""),
      buy_rules: Joi.any(),
      calculate_on: Joi.string().allow(""),
      offer_text: Joi.string().allow(""),
      promotion_group: Joi.string().allow(""),
      valid_till: Joi.string().allow(""),
      discount_rules: Joi.array().items(Joi.any()),
      offer_prices: Joi.array().items(CartApplicationModel.LadderOfferItem()),
      free_gift_items: Joi.array().items(CartApplicationModel.FreeGiftItems()),
      description: Joi.string().allow(""),
    });
  }

  /** @returns {CurrencyInfo} */
  static CurrencyInfo() {
    return Joi.object({
      code: Joi.string().allow(""),
      symbol: Joi.string().allow(""),
    });
  }

  /** @returns {LadderPriceOffers} */
  static LadderPriceOffers() {
    return Joi.object({
      available_offers: Joi.array().items(
        CartApplicationModel.LadderPriceOffer()
      ),
      currency: CartApplicationModel.CurrencyInfo(),
    });
  }

  /** @returns {PaymentMeta} */
  static PaymentMeta() {
    return Joi.object({
      merchant_code: Joi.string().allow(""),
      type: Joi.string().allow(""),
      payment_gateway: Joi.string().allow(""),
      payment_identifier: Joi.string().allow("").allow(null),
    });
  }

  /** @returns {PaymentMethod} */
  static PaymentMethod() {
    return Joi.object({
      payment_meta: CartApplicationModel.PaymentMeta().required(),
      mode: Joi.string().allow("").required(),
      payment: Joi.string().allow(""),
      amount: Joi.number().allow(null),
      name: Joi.string().allow(""),
      payment_extra_identifiers: Joi.any(),
    });
  }

  /** @returns {CartCheckoutDetailV2Request} */
  static CartCheckoutDetailV2Request() {
    return Joi.object({
      custom_meta: Joi.any(),
      customer_details: Joi.any().allow(null),
      merchant_code: Joi.string().allow(""),
      cart_id: Joi.string().allow(""),
      id: Joi.string().allow("").allow(null),
      payment_auto_confirm: Joi.boolean(),
      payment_methods: Joi.array()
        .items(CartApplicationModel.PaymentMethod())
        .required(),
      payment_mode: Joi.string().allow("").required(),
      aggregator: Joi.string().allow(""),
      address_id: Joi.string().allow(""),
      callback_url: Joi.string().allow("").allow(null),
      delivery_address: Joi.any(),
      staff: CartApplicationModel.StaffCheckout(),
      order_type: Joi.string().allow(""),
      ordering_store: Joi.number().allow(null),
      extra_meta: Joi.any(),
      payment_identifier: Joi.string().allow("").allow(null),
      billing_address: Joi.any(),
      payment_params: Joi.any().allow(null),
      billing_address_id: Joi.string().allow(""),
      meta: Joi.any(),
      iin: Joi.string().allow(""),
      network: Joi.string().allow(""),
      type: Joi.string().allow(""),
      card_id: Joi.string().allow(""),
    });
  }
}
module.exports = CartApplicationModel;
