export = CartApplicationModel;
/**
 * @typedef BuyRules
 * @property {Object} [item_criteria] - Item criteria of promotion
 * @property {Object} [cart_conditions] - Cart conditions details for promotion
 */
/**
 * @typedef DiscountRulesApp
 * @property {string[]} [matched_buy_rules] - Matched buy rules for promotion
 * @property {Object} [raw_offer] - Raw offer details for promotion
 * @property {Object} [offer] - Offer for promotion
 * @property {Object} [item_criteria] - Item criteria of promotion
 */
/**
 * @typedef Ownership
 * @property {string} [payable_category] - Promo amount payable category
 * @property {string} [payable_by] - Promo amount bearable party
 */
/**
 * @typedef AppliedFreeArticles
 * @property {FreeGiftItems} [free_gift_item_details] - Free gift items details
 * @property {string} [parent_item_identifier] - Parent item identifier for free article
 * @property {number} [quantity] - Free article quantity
 * @property {string} [article_id] - Free article id
 */
/**
 * @typedef AppliedPromotion
 * @property {string} [promo_id] - Promotion id
 * @property {BuyRules[]} [buy_rules] - Buy rules for promotions
 * @property {string} [offer_text] - Offer text of current promotion
 * @property {string} [promotion_group] - Promotion group for the promotion
 * @property {boolean} [mrp_promotion] - If applied promotion is applied on
 *   product MRP or ESP
 * @property {string} [promotion_name] - Promotion name of current promotion
 * @property {number} [amount] - Per unit discount amount applied with current promotion
 * @property {DiscountRulesApp[]} [discount_rules] - Discount rules for promotions
 * @property {Ownership} [ownership] - Ownership of promotion
 * @property {number} [article_quantity] - Quantity of article on which
 *   promotion is applicable
 * @property {AppliedFreeArticles[]} [applied_free_articles] - Applied free
 *   article for free gift item promotions
 * @property {string} [promotion_type] - Promotion type of current promotion
 * @property {Object} [meta] - Meta object for extra data
 * @property {string} [code] - Promotion code
 */
/**
 * @typedef PaymentSelectionLock
 * @property {boolean} [enabled]
 * @property {string} [default_options]
 * @property {string} [payment_identifier]
 */
/**
 * @typedef PromiseFormatted
 * @property {string} [max]
 * @property {string} [min]
 */
/**
 * @typedef PromiseISOFormat
 * @property {string} [max] - Max promise in ISO format.
 * @property {string} [min] - Min Promise in ISO format.
 */
/**
 * @typedef PromiseTimestamp
 * @property {number} [max]
 * @property {number} [min]
 */
/**
 * @typedef ShipmentPromise
 * @property {PromiseFormatted} [formatted]
 * @property {PromiseTimestamp} [timestamp]
 * @property {PromiseISOFormat} [iso]
 */
/**
 * @typedef BasePrice
 * @property {number} [effective]
 * @property {string} [currency_symbol]
 * @property {number} [marked]
 * @property {string} [currency_code]
 */
/**
 * @typedef ArticlePriceInfo
 * @property {BasePrice} [base]
 * @property {BasePrice} [converted]
 */
/**
 * @typedef BaseInfo
 * @property {number} [uid]
 * @property {string} [name]
 */
/**
 * @typedef StoreInfo
 * @property {string} [store_code]
 * @property {number} [uid]
 * @property {string} [name]
 */
/**
 * @typedef ProductArticle
 * @property {ArticlePriceInfo} [price]
 * @property {string[]} [product_group_tags]
 * @property {Object} [extra_meta]
 * @property {number} [quantity]
 * @property {Object} [_custom_json]
 * @property {Object} [meta]
 * @property {string} [size]
 * @property {number} [mto_quantity]
 * @property {BaseInfo} [seller]
 * @property {string} [seller_identifier]
 * @property {Object} [parent_item_identifiers]
 * @property {Object} [identifier]
 * @property {StoreInfo} [store]
 * @property {Object} [cart_item_meta]
 * @property {string} [uid]
 * @property {Object} [gift_card]
 * @property {boolean} [is_gift_visible]
 * @property {string} [type]
 * @property {string[]} [tags] - A list of article tags
 */
/**
 * @typedef CartProductIdentifer
 * @property {string} [identifier] - Article idenfier generated by cart
 */
/**
 * @typedef PromoMeta
 * @property {string} [message]
 */
/**
 * @typedef ChargesAmount
 * @property {number} [value] - This is the value of amount added
 * @property {string} [currency] - This is destination currency of value
 */
/**
 * @typedef Charges
 * @property {Object} [meta] - This object contains the meta data realted to
 *   charges price adjustment
 * @property {ChargesAmount} [amount]
 * @property {string} [name] - This is the name of the charge applied
 * @property {boolean} [allow_refund] - This boolean value defines that refund
 *   is allowed or not for the charge
 * @property {string} [code] - This is the code of the charge applied
 * @property {string} [type] - This is the type of the charge applied
 */
/**
 * @typedef ProductPrice
 * @property {string} [currency_symbol]
 * @property {number} [selling]
 * @property {string} [currency_code]
 * @property {number} [add_on]
 * @property {number} [effective]
 * @property {number} [marked]
 */
/**
 * @typedef ProductPriceInfo
 * @property {ProductPrice} [base]
 * @property {ProductPrice} [converted]
 */
/**
 * @typedef ProductPricePerUnit
 * @property {string} [currency_symbol]
 * @property {number} [selling_price]
 * @property {string} [currency_code]
 * @property {number} [add_on]
 * @property {number} [effective]
 * @property {number} [marked]
 */
/**
 * @typedef ProductPricePerUnitInfo
 * @property {ProductPricePerUnit} [base]
 * @property {ProductPricePerUnit} [converted]
 */
/**
 * @typedef ProductAvailabilitySize
 * @property {string} [display]
 * @property {string} [value]
 * @property {boolean} [is_available]
 */
/**
 * @typedef ProductAvailability
 * @property {boolean} [out_of_stock]
 * @property {boolean} [deliverable]
 * @property {ProductAvailabilitySize[]} [available_sizes]
 * @property {boolean} [is_valid]
 * @property {number} [other_store_quantity]
 * @property {string[]} [sizes]
 */
/**
 * @typedef ActionQuery
 * @property {string[]} [product_slug] - Contains list of product slug
 */
/**
 * @typedef ProductAction
 * @property {ActionQuery} [query]
 * @property {string} [url]
 * @property {string} [type]
 */
/**
 * @typedef Tags
 * @property {Object} [tags]
 */
/**
 * @typedef ProductImage
 * @property {string} [secure_url]
 * @property {string} [aspect_ratio]
 * @property {string} [url]
 */
/**
 * @typedef CategoryInfo
 * @property {number} [uid] - Product Category Id
 * @property {string} [name]
 */
/**
 * @typedef CartProduct
 * @property {Object} [_custom_json]
 * @property {BaseInfo} [brand]
 * @property {ProductAction} [action]
 * @property {Tags} [teaser_tag]
 * @property {string} [slug] - Unique product url name generated via product
 *   name and other meta data
 * @property {ProductImage[]} [images]
 * @property {number} [uid]
 * @property {string} [name]
 * @property {string} [item_code]
 * @property {CategoryInfo[]} [categories]
 * @property {string[]} [tags]
 * @property {string} [type]
 * @property {Object} [attributes]
 */
/**
 * @typedef CouponDetails
 * @property {number} [discount_single_quantity]
 * @property {string} [code]
 * @property {number} [discount_total_quantity]
 */
/**
 * @typedef CartProductInfo
 * @property {ProductArticle} [article]
 * @property {Object} [moq]
 * @property {CartProductIdentifer} identifiers
 * @property {PromoMeta} [promo_meta]
 * @property {ProductPriceInfo} [price]
 * @property {number} [quantity]
 * @property {Charges[]} [charges]
 * @property {string} [discount]
 * @property {ProductAvailability} [availability]
 * @property {ShipmentPromise} [delivery_promise]
 * @property {CartProduct} [product]
 * @property {string} [product_ean_id]
 * @property {Object} [bulk_offer]
 * @property {Object} [parent_item_identifiers]
 * @property {CouponDetails} [coupon]
 * @property {Object} [custom_order]
 * @property {string} [coupon_message]
 * @property {string} [key]
 * @property {string} [message]
 * @property {boolean} [is_set]
 * @property {ProductPricePerUnitInfo} [price_per_unit]
 * @property {AppliedPromotion[]} [promotions_applied]
 */
/**
 * @typedef DisplayBreakup
 * @property {string} [currency_symbol]
 * @property {string} [key]
 * @property {string} [display]
 * @property {string[]} [message]
 * @property {string} [currency_code]
 * @property {number} [value]
 * @property {number} [preset]
 */
/**
 * @typedef RawBreakup
 * @property {number} [vog]
 * @property {number} [subtotal]
 * @property {number} [fynd_cash]
 * @property {number} [discount]
 * @property {number} [convenience_fee]
 * @property {number} [delivery_charge]
 * @property {number} [gst_charges]
 * @property {number} [mrp_total]
 * @property {number} [mop_total]
 * @property {number} [total_charge]
 * @property {number} [coupon]
 * @property {number} [total]
 * @property {number} [gift_card]
 * @property {number} [you_saved]
 * @property {number} [cod_charge]
 */
/**
 * @typedef CouponBreakup
 * @property {number} [coupon_value]
 * @property {string} [title]
 * @property {string} [sub_title]
 * @property {number} [minimum_cart_value]
 * @property {string} [message]
 * @property {string} [coupon_type]
 * @property {string} [uid]
 * @property {number} [value]
 * @property {number} [max_discount_value]
 * @property {boolean} [is_applied]
 * @property {string} [description]
 * @property {string} [code]
 * @property {string} [type]
 */
/**
 * @typedef LoyaltyPoints
 * @property {number} [total]
 * @property {string} [description]
 * @property {number} [applicable]
 * @property {boolean} [is_applied]
 */
/**
 * @typedef CartBreakup
 * @property {DisplayBreakup[]} [display]
 * @property {RawBreakup} [raw]
 * @property {CouponBreakup} [coupon]
 * @property {LoyaltyPoints} [loyalty_points]
 */
/**
 * @typedef CartCurrency
 * @property {string} [code] - Currency code defined by ISO 4217:2015
 * @property {string} [symbol]
 */
/**
 * @typedef CartDetailCoupon
 * @property {number} [cashback_amount]
 * @property {string} [cashback_message_primary]
 * @property {string} [cashback_message_secondary]
 * @property {string} [coupon_code]
 * @property {string} [coupon_description]
 * @property {string} [coupon_id]
 * @property {string} [coupon_subtitle]
 * @property {string} [coupon_title]
 * @property {string} [coupon_type]
 * @property {number} [coupon_value]
 * @property {number} [discount]
 * @property {boolean} [is_applied]
 * @property {boolean} [is_valid]
 * @property {number} [maximum_discount_value]
 * @property {string} [message]
 * @property {number} [minimum_cart_value]
 */
/**
 * @typedef ChargesThreshold
 * @property {number} [charges]
 * @property {number} [threshold]
 */
/**
 * @typedef DeliveryChargesConfig
 * @property {boolean} [enabled]
 * @property {ChargesThreshold[]} [charges]
 */
/**
 * @typedef CartCommonConfig
 * @property {DeliveryChargesConfig} [delivery_charges_config]
 */
/**
 * @typedef CartDetailResponse
 * @property {number} [cart_id]
 * @property {string} [uid]
 * @property {AppliedPromotion[]} [applied_promo_details]
 * @property {string} [checkout_mode]
 * @property {string} [pan_no]
 * @property {boolean} [is_valid]
 * @property {string} [id]
 * @property {PaymentSelectionLock} [payment_selection_lock]
 * @property {ShipmentPromise} [delivery_promise]
 * @property {string} [comment]
 * @property {CartProductInfo[]} [items]
 * @property {string} [delivery_charge_info]
 * @property {CartCommonConfig} [common_config]
 * @property {CartDetailCoupon} [coupon]
 * @property {string} [message]
 * @property {Object} [notification]
 * @property {string} [staff_user_id]
 * @property {boolean} [success]
 * @property {string} [gstin]
 * @property {boolean} [restrict_checkout]
 * @property {string} [last_modified]
 * @property {CartBreakup} [breakup_values]
 * @property {CartCurrency} [currency]
 * @property {string} [coupon_text]
 * @property {boolean} [buy_now]
 * @property {Object} [pan_config]
 * @property {Object} [custom_cart_meta]
 */
/**
 * @typedef AddProductCart
 * @property {Object} [article_assignment]
 * @property {string[]} [product_group_tags]
 * @property {Object} [extra_meta]
 * @property {number} [quantity]
 * @property {Object} [_custom_json]
 * @property {string} [item_size]
 * @property {number} [store_id]
 * @property {string} [display]
 * @property {string} [article_id]
 * @property {Object[]} [parent_item_identifiers]
 * @property {number} [seller_id]
 * @property {boolean} [pos]
 * @property {number} [item_id]
 * @property {Object} [meta]
 * @property {string} [seller_identifier] - Add items using seller identifier for store os
 */
/**
 * @typedef AddCartRequest
 * @property {AddProductCart[]} [items]
 * @property {boolean} [new_cart]
 */
/**
 * @typedef AddCartDetailResponse
 * @property {string} [message]
 * @property {boolean} [partial] - When adding multiple items check if all
 *   added. True if only few are added.
 * @property {CartDetailResponse} [cart]
 * @property {boolean} [success] - True if all items are added successfully.
 *   False if partially added or not added.
 */
/**
 * @typedef UpdateProductCart
 * @property {Object} [extra_meta]
 * @property {Object} [_custom_json]
 * @property {number} [quantity]
 * @property {string} [item_size]
 * @property {number} [item_index]
 * @property {CartProductIdentifer} identifiers
 * @property {string} [article_id]
 * @property {Object} [parent_item_identifiers]
 * @property {number} [item_id]
 * @property {Object} [meta]
 */
/**
 * @typedef UpdateCartRequest
 * @property {UpdateProductCart[]} [items]
 * @property {string} operation
 */
/**
 * @typedef UpdateCartDetailResponse
 * @property {string} [message]
 * @property {CartDetailResponse} [cart]
 * @property {boolean} [success] - True if all items are added successfully.
 *   False if partially added or not added.
 */
/**
 * @typedef DeleteCartDetailResponse
 * @property {string} [message]
 * @property {boolean} [success] - True if cart is archived successfully. False
 *   if not archived.
 */
/**
 * @typedef CartItemCountResponse
 * @property {number} [user_cart_items_count] - Item count present in cart
 */
/**
 * @typedef PageCoupon
 * @property {number} [total_item_count]
 * @property {boolean} [has_next]
 * @property {number} [total]
 * @property {number} [current]
 * @property {boolean} [has_previous]
 */
/**
 * @typedef Coupon
 * @property {number} [coupon_amount] - The amount based on cart value
 * @property {number} [coupon_value]
 * @property {string} [title]
 * @property {number} [minimum_cart_value]
 * @property {string} [sub_title]
 * @property {string} [expires_on]
 * @property {string} [message]
 * @property {string} [coupon_type]
 * @property {number} [max_discount_value]
 * @property {string} [coupon_code]
 * @property {boolean} [is_applicable]
 * @property {string} [description]
 * @property {boolean} [is_applied]
 * @property {string} [start_date]
 * @property {string} [end_date]
 * @property {string} [coupon_applicable_message]
 * @property {string} [offer_text]
 * @property {boolean} [is_bank_offer]
 */
/**
 * @typedef GetCouponResponse
 * @property {PageCoupon} [page]
 * @property {Coupon[]} [available_coupon_list]
 */
/**
 * @typedef ApplyCouponRequest
 * @property {string} coupon_code - Coupon code to be applied
 */
/**
 * @typedef OfferPrice
 * @property {string} [currency_symbol] - Currency symbol for currency
 * @property {number} [bulk_effective] - Discounted per unit price for current
 *   offer object
 * @property {string} [currency_code] - Currency code for all amounts
 * @property {number} [effective] - Current per unit price of product after
 *   existing deductions
 * @property {number} [marked] - Original price of product
 */
/**
 * @typedef OfferItem
 * @property {OfferPrice} [price]
 * @property {number} [margin] - Percentage value of discount
 * @property {number} [quantity] - Quantity on which offer is applicable
 * @property {boolean} [best] - Is true for best offer from all offers present
 *   for all sellers
 * @property {number} [total] - Total price of offer quantity with discount
 * @property {boolean} [auto_applied] - Whether offer discount is auto applied in cart
 * @property {string} [type] - Offer type
 */
/**
 * @typedef OfferSeller
 * @property {number} [uid] - Seller id
 * @property {string} [name]
 */
/**
 * @typedef BulkPriceOffer
 * @property {OfferItem[]} [offers]
 * @property {OfferSeller} [seller]
 */
/**
 * @typedef BulkPriceResponse
 * @property {BulkPriceOffer[]} [data] - Consist of offers from multiple seller
 */
/**
 * @typedef RewardPointRequest
 * @property {boolean} points
 */
/**
 * @typedef GeoLocation
 * @property {number} [latitude]
 * @property {number} [longitude]
 */
/**
 * @typedef Address
 * @property {string} [country_iso_code]
 * @property {string} [area]
 * @property {string} [phone]
 * @property {string} [country_phone_code]
 * @property {string} [checkout_mode]
 * @property {string} [address]
 * @property {string} [area_code_slug]
 * @property {GeoLocation} [geo_location]
 * @property {string} [id]
 * @property {Object} [_custom_json]
 * @property {string} [city]
 * @property {string} [sector]
 * @property {string} [state_code] - State code for international address
 * @property {string} [created_by_user_id]
 * @property {string} [landmark]
 * @property {string} [user_id]
 * @property {string} [name]
 * @property {Object} [google_map_point]
 * @property {boolean} [is_active]
 * @property {string[]} [tags]
 * @property {string} [country_code]
 * @property {string} [address_type]
 * @property {string} [country]
 * @property {boolean} [is_default_address]
 * @property {string} [area_code]
 * @property {string} [email]
 * @property {string} [state]
 * @property {Object} [meta]
 */
/**
 * @typedef GetAddressesResponse
 * @property {boolean} [pii_masking]
 * @property {Address[]} [address]
 */
/**
 * @typedef SaveAddressResponse
 * @property {string} [id]
 * @property {boolean} [success]
 * @property {boolean} [is_default_address]
 */
/**
 * @typedef UpdateAddressResponse
 * @property {boolean} [is_updated]
 * @property {string} [id]
 * @property {boolean} [success]
 * @property {boolean} [is_default_address]
 */
/**
 * @typedef DeleteAddressResponse
 * @property {string} [id]
 * @property {boolean} [is_deleted]
 */
/**
 * @typedef SelectCartAddressRequest
 * @property {string} [id]
 * @property {string} [billing_address_id]
 * @property {string} [cart_id]
 */
/**
 * @typedef UpdateCartPaymentRequest
 * @property {string} [id]
 * @property {string} [payment_identifier]
 * @property {string} [address_id]
 * @property {string} [merchant_code]
 * @property {string} [aggregator_name]
 * @property {string} [payment_mode]
 */
/**
 * @typedef CouponValidity
 * @property {string} [title]
 * @property {number} [discount]
 * @property {boolean} [next_validation_required]
 * @property {boolean} [valid]
 * @property {string} [display_message_en]
 * @property {string} [code]
 */
/**
 * @typedef PaymentCouponValidate
 * @property {string} [message]
 * @property {CouponValidity} [coupon_validity]
 * @property {boolean} success
 */
/**
 * @typedef ShipmentResponse
 * @property {number} [shipments]
 * @property {ShipmentPromise} [promise]
 * @property {string} [order_type]
 * @property {string} [box_type]
 * @property {string} [shipment_type]
 * @property {Object} [dp_options]
 * @property {string} [dp_id]
 * @property {CartProductInfo[]} [items]
 * @property {string} [fulfillment_type]
 * @property {number} [fulfillment_id]
 */
/**
 * @typedef CartShipmentsResponse
 * @property {string} [delivery_charge_info]
 * @property {string} [checkout_mode]
 * @property {string} [message]
 * @property {string} [gstin]
 * @property {boolean} [restrict_checkout]
 * @property {string} [last_modified]
 * @property {number} [cart_id]
 * @property {boolean} [is_valid]
 * @property {CartBreakup} [breakup_values]
 * @property {CartCurrency} [currency]
 * @property {string} [id]
 * @property {ShipmentResponse[]} [shipments]
 * @property {PaymentSelectionLock} [payment_selection_lock]
 * @property {string} [coupon_text]
 * @property {ShipmentPromise} [delivery_promise]
 * @property {boolean} [error]
 * @property {string} [comment]
 * @property {boolean} [buy_now]
 * @property {string} [uid]
 * @property {Object} [custom_cart_meta]
 */
/**
 * @typedef CartCheckoutCustomMeta
 * @property {string} key
 * @property {string} value
 */
/**
 * @typedef CustomerDetails
 * @property {string} [email]
 * @property {string} mobile
 * @property {string} [name]
 */
/**
 * @typedef StaffCheckout
 * @property {string} [employee_code]
 * @property {string} user
 * @property {string} last_name
 * @property {string} first_name
 * @property {string} _id
 */
/**
 * @typedef CartCheckoutDetailRequest
 * @property {CartCheckoutCustomMeta[]} [custom_meta]
 * @property {Object} [customer_details] - Customer details
 * @property {string} [merchant_code]
 * @property {string} [id]
 * @property {boolean} [payment_auto_confirm]
 * @property {string} payment_mode
 * @property {string} [aggregator]
 * @property {string} [address_id]
 * @property {string} [callback_url]
 * @property {Object} [delivery_address]
 * @property {StaffCheckout} [staff]
 * @property {string} [order_type]
 * @property {number} [ordering_store]
 * @property {Object} [extra_meta]
 * @property {string} [payment_identifier]
 * @property {Object} [billing_address]
 * @property {Object} [payment_params]
 * @property {string} [billing_address_id]
 * @property {Object} [meta]
 * @property {Object} [payment_extra_identifiers]
 * @property {string} [iin]
 * @property {string} [network]
 * @property {string} [type]
 * @property {string} [card_id]
 */
/**
 * @typedef CheckCart
 * @property {string} [checkout_mode]
 * @property {string} [user_type]
 * @property {string} [cod_message]
 * @property {number} [cart_id]
 * @property {boolean} [is_valid]
 * @property {number} [delivery_charges]
 * @property {string} [id]
 * @property {PaymentSelectionLock} [payment_selection_lock]
 * @property {string} [error_message]
 * @property {ShipmentPromise} [delivery_promise]
 * @property {string} [comment]
 * @property {CartProductInfo[]} [items]
 * @property {string} [uid]
 * @property {number} [delivery_charge_order_value]
 * @property {string} [delivery_charge_info]
 * @property {boolean} [cod_available]
 * @property {boolean} [success]
 * @property {string} [store_code]
 * @property {string} [message]
 * @property {string} [gstin]
 * @property {boolean} [restrict_checkout]
 * @property {string} [last_modified]
 * @property {string} [order_id]
 * @property {CartBreakup} [breakup_values]
 * @property {CartCurrency} [currency]
 * @property {Object[]} [store_emps]
 * @property {string} [coupon_text]
 * @property {boolean} [buy_now]
 * @property {number} [cod_charges]
 * @property {Object} [custom_cart_meta]
 */
/**
 * @typedef CartCheckoutResponse
 * @property {string} [payment_confirm_url]
 * @property {string} [app_intercept_url]
 * @property {boolean} [success]
 * @property {string} [callback_url]
 * @property {string} [message]
 * @property {Object} [data]
 * @property {string} [order_id]
 * @property {CheckCart} [cart]
 */
/**
 * @typedef GiftDetail
 * @property {boolean} [is_gift_applied]
 * @property {string} [gift_message]
 */
/**
 * @typedef ArticleGiftDetail
 * @property {GiftDetail} [article_id]
 */
/**
 * @typedef CartMetaRequest
 * @property {Object} [delivery_slots]
 * @property {ArticleGiftDetail} [gift_details]
 * @property {Object} [pick_up_customer_details] - Customer contact details for
 *   customer pickup at store
 * @property {string} [checkout_mode]
 * @property {string} [comment]
 * @property {string} [gstin]
 * @property {Object} [custom_cart_meta]
 */
/**
 * @typedef CartMetaResponse
 * @property {string} [message]
 * @property {boolean} [is_valid]
 */
/**
 * @typedef CartMetaMissingResponse
 * @property {string[]} [errors]
 */
/**
 * @typedef GetShareCartLinkRequest
 * @property {string} [id] - Cart uid for generating sharing
 * @property {Object} [meta] - Staff, Ordering store or any other data. This
 *   data will be used to generate link as well as sent as shared details.
 */
/**
 * @typedef GetShareCartLinkResponse
 * @property {string} [token] - Short url unique id
 * @property {string} [share_url] - Short shareable final url
 */
/**
 * @typedef SharedCartDetails
 * @property {string} [token] - Short link id
 * @property {Object} [user] - User details of who generated share link
 * @property {string} [created_on]
 * @property {Object} [source] - Share link device and other source information
 * @property {Object} [meta] - Meta data sent while generating share cart link
 */
/**
 * @typedef SharedCart
 * @property {string} [checkout_mode]
 * @property {number} [cart_id]
 * @property {boolean} [is_valid]
 * @property {string} [id]
 * @property {PaymentSelectionLock} [payment_selection_lock]
 * @property {ShipmentPromise} [delivery_promise]
 * @property {string} [comment]
 * @property {CartProductInfo[]} [items]
 * @property {string} [uid]
 * @property {string} [delivery_charge_info]
 * @property {string} [message]
 * @property {string} [gstin]
 * @property {SharedCartDetails} [shared_cart_details]
 * @property {boolean} [restrict_checkout]
 * @property {string} [last_modified]
 * @property {CartBreakup} [breakup_values]
 * @property {CartCurrency} [currency]
 * @property {string} [coupon_text]
 * @property {boolean} [buy_now]
 * @property {Object} [custom_cart_meta]
 */
/**
 * @typedef SharedCartResponse
 * @property {string} [error]
 * @property {SharedCart} [cart]
 */
/**
 * @typedef PriceMinMax
 * @property {number} [min]
 * @property {number} [max]
 */
/**
 * @typedef ItemPriceDetails
 * @property {PriceMinMax} [marked]
 * @property {PriceMinMax} [effective]
 * @property {string} [currency]
 */
/**
 * @typedef FreeGiftItems
 * @property {string} [item_slug] - Item slug
 * @property {string} [item_name] - Item name
 * @property {ItemPriceDetails} [item_price_details]
 * @property {string} [item_brand_name] - Item brand name
 * @property {number} [item_id] - Item id
 * @property {string[]} [item_images_url] - Item images URL
 */
/**
 * @typedef PromotionOffer
 * @property {string} [id] - Promotion id
 * @property {Object} [buy_rules] - Buy rules of promotions
 * @property {string} [offer_text] - Offer title
 * @property {string} [promotion_type] - Promotion type
 * @property {string} [promotion_name] - Name of the promotion
 * @property {string} [promotion_group] - Group of promotion belongs to
 * @property {string} [valid_till] - Datetime ISOString for promotion end date
 * @property {Object[]} [discount_rules] - Discount rules of promotions
 * @property {FreeGiftItems[]} [free_gift_items] - Details of free gift items
 * @property {string} [description] - Offer details including T&C
 */
/**
 * @typedef PromotionOffersResponse
 * @property {PromotionOffer[]} [available_promotions]
 */
/**
 * @typedef PromotionPaymentOffer
 * @property {string} [application_id] - Application id
 * @property {Object[]} [buy_rules] - Buy rules of promotions
 * @property {string} [calculate_on] - Price on which promotion calculated
 * @property {string} [description] - Offer details including T&C
 * @property {Object[]} [discount_rules] - Discount rules of promotions
 * @property {string} [id] - Promotion id
 * @property {string} [offer_text] - Offer title
 * @property {string} [promotion_group] - Group of promotion belongs to
 * @property {string} [promotion_type] - Promotion type
 * @property {string} [promotion_name] - Name of the promotion
 */
/**
 * @typedef PromotionPaymentOffersResponse
 * @property {boolean} [success]
 * @property {PromotionPaymentOffer[]} [promotions]
 */
/**
 * @typedef OperationErrorResponse
 * @property {string} [message]
 * @property {boolean} [success]
 */
/**
 * @typedef LadderPrice
 * @property {string} [currency_symbol] - Currency symbol for currency
 * @property {number} [offer_price] - Discounted per unit price for current offer object
 * @property {string} [currency_code] - Currency code for all amounts
 * @property {number} [effective] - Current per unit price of product after
 *   existing deductions
 * @property {number} [marked] - Original price of product
 */
/**
 * @typedef LadderOfferItem
 * @property {LadderPrice} [price]
 * @property {number} [margin] - Percentage value of discount
 * @property {number} [max_quantity] - Minimum quantity upto which offer is
 *   applicable. If not present that offer is applicable on all quantities
 * @property {number} [min_quantity] - Minimum quantity from which offer is applicable
 * @property {string} [type] - Offer type
 */
/**
 * @typedef LadderPriceOffer
 * @property {string} [id] - Promotion id
 * @property {Object} [buy_rules] - Buy rules of promotions
 * @property {string} [calculate_on] - If this ladder offer is to be calculated
 *   on MRP or ESP price
 * @property {string} [offer_text] - Offer title
 * @property {string} [promotion_group] - Group of promotion belongs to
 * @property {string} [valid_till] - Datetime ISOString for promotion end date
 * @property {Object[]} [discount_rules] - Discount rules of promotions
 * @property {LadderOfferItem[]} [offer_prices]
 * @property {FreeGiftItems[]} [free_gift_items] - Details of free gift items
 * @property {string} [description] - Offer details including T&C
 */
/**
 * @typedef CurrencyInfo
 * @property {string} [code]
 * @property {string} [symbol]
 */
/**
 * @typedef LadderPriceOffers
 * @property {LadderPriceOffer[]} [available_offers]
 * @property {CurrencyInfo} [currency]
 */
/**
 * @typedef PaymentMeta
 * @property {string} [merchant_code]
 * @property {string} [type]
 * @property {string} [payment_gateway]
 * @property {string} [payment_identifier]
 */
/**
 * @typedef PaymentMethod
 * @property {PaymentMeta} payment_meta
 * @property {string} mode
 * @property {string} [payment]
 * @property {number} [amount]
 * @property {string} [name]
 * @property {Object} [payment_extra_identifiers]
 */
/**
 * @typedef CartCheckoutDetailV2Request
 * @property {Object} [custom_meta]
 * @property {Object} [customer_details] - Customer details
 * @property {string} [merchant_code]
 * @property {string} [cart_id]
 * @property {string} [id]
 * @property {boolean} [payment_auto_confirm]
 * @property {PaymentMethod[]} payment_methods
 * @property {string} payment_mode
 * @property {string} [aggregator]
 * @property {string} [address_id]
 * @property {string} [callback_url]
 * @property {Object} [delivery_address]
 * @property {StaffCheckout} [staff]
 * @property {string} [order_type]
 * @property {number} [ordering_store]
 * @property {Object} [extra_meta]
 * @property {string} [payment_identifier]
 * @property {Object} [billing_address]
 * @property {Object} [payment_params]
 * @property {string} [billing_address_id]
 * @property {Object} [meta]
 * @property {string} [iin]
 * @property {string} [network]
 * @property {string} [type]
 * @property {string} [card_id]
 */
declare class CartApplicationModel {
}
declare namespace CartApplicationModel {
    export { BuyRules, DiscountRulesApp, Ownership, AppliedFreeArticles, AppliedPromotion, PaymentSelectionLock, PromiseFormatted, PromiseISOFormat, PromiseTimestamp, ShipmentPromise, BasePrice, ArticlePriceInfo, BaseInfo, StoreInfo, ProductArticle, CartProductIdentifer, PromoMeta, ChargesAmount, Charges, ProductPrice, ProductPriceInfo, ProductPricePerUnit, ProductPricePerUnitInfo, ProductAvailabilitySize, ProductAvailability, ActionQuery, ProductAction, Tags, ProductImage, CategoryInfo, CartProduct, CouponDetails, CartProductInfo, DisplayBreakup, RawBreakup, CouponBreakup, LoyaltyPoints, CartBreakup, CartCurrency, CartDetailCoupon, ChargesThreshold, DeliveryChargesConfig, CartCommonConfig, CartDetailResponse, AddProductCart, AddCartRequest, AddCartDetailResponse, UpdateProductCart, UpdateCartRequest, UpdateCartDetailResponse, DeleteCartDetailResponse, CartItemCountResponse, PageCoupon, Coupon, GetCouponResponse, ApplyCouponRequest, OfferPrice, OfferItem, OfferSeller, BulkPriceOffer, BulkPriceResponse, RewardPointRequest, GeoLocation, Address, GetAddressesResponse, SaveAddressResponse, UpdateAddressResponse, DeleteAddressResponse, SelectCartAddressRequest, UpdateCartPaymentRequest, CouponValidity, PaymentCouponValidate, ShipmentResponse, CartShipmentsResponse, CartCheckoutCustomMeta, CustomerDetails, StaffCheckout, CartCheckoutDetailRequest, CheckCart, CartCheckoutResponse, GiftDetail, ArticleGiftDetail, CartMetaRequest, CartMetaResponse, CartMetaMissingResponse, GetShareCartLinkRequest, GetShareCartLinkResponse, SharedCartDetails, SharedCart, SharedCartResponse, PriceMinMax, ItemPriceDetails, FreeGiftItems, PromotionOffer, PromotionOffersResponse, PromotionPaymentOffer, PromotionPaymentOffersResponse, OperationErrorResponse, LadderPrice, LadderOfferItem, LadderPriceOffer, CurrencyInfo, LadderPriceOffers, PaymentMeta, PaymentMethod, CartCheckoutDetailV2Request };
}
/** @returns {BuyRules} */
declare function BuyRules(): BuyRules;
type BuyRules = {
    /**
     * - Item criteria of promotion
     */
    item_criteria?: any;
    /**
     * - Cart conditions details for promotion
     */
    cart_conditions?: any;
};
/** @returns {DiscountRulesApp} */
declare function DiscountRulesApp(): DiscountRulesApp;
type DiscountRulesApp = {
    /**
     * - Matched buy rules for promotion
     */
    matched_buy_rules?: string[];
    /**
     * - Raw offer details for promotion
     */
    raw_offer?: any;
    /**
     * - Offer for promotion
     */
    offer?: any;
    /**
     * - Item criteria of promotion
     */
    item_criteria?: any;
};
/** @returns {Ownership} */
declare function Ownership(): Ownership;
type Ownership = {
    /**
     * - Promo amount payable category
     */
    payable_category?: string;
    /**
     * - Promo amount bearable party
     */
    payable_by?: string;
};
/** @returns {AppliedFreeArticles} */
declare function AppliedFreeArticles(): AppliedFreeArticles;
type AppliedFreeArticles = {
    /**
     * - Free gift items details
     */
    free_gift_item_details?: FreeGiftItems;
    /**
     * - Parent item identifier for free article
     */
    parent_item_identifier?: string;
    /**
     * - Free article quantity
     */
    quantity?: number;
    /**
     * - Free article id
     */
    article_id?: string;
};
/** @returns {AppliedPromotion} */
declare function AppliedPromotion(): AppliedPromotion;
type AppliedPromotion = {
    /**
     * - Promotion id
     */
    promo_id?: string;
    /**
     * - Buy rules for promotions
     */
    buy_rules?: BuyRules[];
    /**
     * - Offer text of current promotion
     */
    offer_text?: string;
    /**
     * - Promotion group for the promotion
     */
    promotion_group?: string;
    /**
     * - If applied promotion is applied on
     * product MRP or ESP
     */
    mrp_promotion?: boolean;
    /**
     * - Promotion name of current promotion
     */
    promotion_name?: string;
    /**
     * - Per unit discount amount applied with current promotion
     */
    amount?: number;
    /**
     * - Discount rules for promotions
     */
    discount_rules?: DiscountRulesApp[];
    /**
     * - Ownership of promotion
     */
    ownership?: Ownership;
    /**
     * - Quantity of article on which
     * promotion is applicable
     */
    article_quantity?: number;
    /**
     * - Applied free
     * article for free gift item promotions
     */
    applied_free_articles?: AppliedFreeArticles[];
    /**
     * - Promotion type of current promotion
     */
    promotion_type?: string;
    /**
     * - Meta object for extra data
     */
    meta?: any;
    /**
     * - Promotion code
     */
    code?: string;
};
/** @returns {PaymentSelectionLock} */
declare function PaymentSelectionLock(): PaymentSelectionLock;
type PaymentSelectionLock = {
    enabled?: boolean;
    default_options?: string;
    payment_identifier?: string;
};
/** @returns {PromiseFormatted} */
declare function PromiseFormatted(): PromiseFormatted;
type PromiseFormatted = {
    max?: string;
    min?: string;
};
/** @returns {PromiseISOFormat} */
declare function PromiseISOFormat(): PromiseISOFormat;
type PromiseISOFormat = {
    /**
     * - Max promise in ISO format.
     */
    max?: string;
    /**
     * - Min Promise in ISO format.
     */
    min?: string;
};
/** @returns {PromiseTimestamp} */
declare function PromiseTimestamp(): PromiseTimestamp;
type PromiseTimestamp = {
    max?: number;
    min?: number;
};
/** @returns {ShipmentPromise} */
declare function ShipmentPromise(): ShipmentPromise;
type ShipmentPromise = {
    formatted?: PromiseFormatted;
    timestamp?: PromiseTimestamp;
    iso?: PromiseISOFormat;
};
/** @returns {BasePrice} */
declare function BasePrice(): BasePrice;
type BasePrice = {
    effective?: number;
    currency_symbol?: string;
    marked?: number;
    currency_code?: string;
};
/** @returns {ArticlePriceInfo} */
declare function ArticlePriceInfo(): ArticlePriceInfo;
type ArticlePriceInfo = {
    base?: BasePrice;
    converted?: BasePrice;
};
/** @returns {BaseInfo} */
declare function BaseInfo(): BaseInfo;
type BaseInfo = {
    uid?: number;
    name?: string;
};
/** @returns {StoreInfo} */
declare function StoreInfo(): StoreInfo;
type StoreInfo = {
    store_code?: string;
    uid?: number;
    name?: string;
};
/** @returns {ProductArticle} */
declare function ProductArticle(): ProductArticle;
type ProductArticle = {
    price?: ArticlePriceInfo;
    product_group_tags?: string[];
    extra_meta?: any;
    quantity?: number;
    _custom_json?: any;
    meta?: any;
    size?: string;
    mto_quantity?: number;
    seller?: BaseInfo;
    seller_identifier?: string;
    parent_item_identifiers?: any;
    identifier?: any;
    store?: StoreInfo;
    cart_item_meta?: any;
    uid?: string;
    gift_card?: any;
    is_gift_visible?: boolean;
    type?: string;
    /**
     * - A list of article tags
     */
    tags?: string[];
};
/** @returns {CartProductIdentifer} */
declare function CartProductIdentifer(): CartProductIdentifer;
type CartProductIdentifer = {
    /**
     * - Article idenfier generated by cart
     */
    identifier?: string;
};
/** @returns {PromoMeta} */
declare function PromoMeta(): PromoMeta;
type PromoMeta = {
    message?: string;
};
/** @returns {ChargesAmount} */
declare function ChargesAmount(): ChargesAmount;
type ChargesAmount = {
    /**
     * - This is the value of amount added
     */
    value?: number;
    /**
     * - This is destination currency of value
     */
    currency?: string;
};
/** @returns {Charges} */
declare function Charges(): Charges;
type Charges = {
    /**
     * - This object contains the meta data realted to
     * charges price adjustment
     */
    meta?: any;
    amount?: ChargesAmount;
    /**
     * - This is the name of the charge applied
     */
    name?: string;
    /**
     * - This boolean value defines that refund
     * is allowed or not for the charge
     */
    allow_refund?: boolean;
    /**
     * - This is the code of the charge applied
     */
    code?: string;
    /**
     * - This is the type of the charge applied
     */
    type?: string;
};
/** @returns {ProductPrice} */
declare function ProductPrice(): ProductPrice;
type ProductPrice = {
    currency_symbol?: string;
    selling?: number;
    currency_code?: string;
    add_on?: number;
    effective?: number;
    marked?: number;
};
/** @returns {ProductPriceInfo} */
declare function ProductPriceInfo(): ProductPriceInfo;
type ProductPriceInfo = {
    base?: ProductPrice;
    converted?: ProductPrice;
};
/** @returns {ProductPricePerUnit} */
declare function ProductPricePerUnit(): ProductPricePerUnit;
type ProductPricePerUnit = {
    currency_symbol?: string;
    selling_price?: number;
    currency_code?: string;
    add_on?: number;
    effective?: number;
    marked?: number;
};
/** @returns {ProductPricePerUnitInfo} */
declare function ProductPricePerUnitInfo(): ProductPricePerUnitInfo;
type ProductPricePerUnitInfo = {
    base?: ProductPricePerUnit;
    converted?: ProductPricePerUnit;
};
/** @returns {ProductAvailabilitySize} */
declare function ProductAvailabilitySize(): ProductAvailabilitySize;
type ProductAvailabilitySize = {
    display?: string;
    value?: string;
    is_available?: boolean;
};
/** @returns {ProductAvailability} */
declare function ProductAvailability(): ProductAvailability;
type ProductAvailability = {
    out_of_stock?: boolean;
    deliverable?: boolean;
    available_sizes?: ProductAvailabilitySize[];
    is_valid?: boolean;
    other_store_quantity?: number;
    sizes?: string[];
};
/** @returns {ActionQuery} */
declare function ActionQuery(): ActionQuery;
type ActionQuery = {
    /**
     * - Contains list of product slug
     */
    product_slug?: string[];
};
/** @returns {ProductAction} */
declare function ProductAction(): ProductAction;
type ProductAction = {
    query?: ActionQuery;
    url?: string;
    type?: string;
};
/** @returns {Tags} */
declare function Tags(): Tags;
type Tags = {
    tags?: any;
};
/** @returns {ProductImage} */
declare function ProductImage(): ProductImage;
type ProductImage = {
    secure_url?: string;
    aspect_ratio?: string;
    url?: string;
};
/** @returns {CategoryInfo} */
declare function CategoryInfo(): CategoryInfo;
type CategoryInfo = {
    /**
     * - Product Category Id
     */
    uid?: number;
    name?: string;
};
/** @returns {CartProduct} */
declare function CartProduct(): CartProduct;
type CartProduct = {
    _custom_json?: any;
    brand?: BaseInfo;
    action?: ProductAction;
    teaser_tag?: Tags;
    /**
     * - Unique product url name generated via product
     * name and other meta data
     */
    slug?: string;
    images?: ProductImage[];
    uid?: number;
    name?: string;
    item_code?: string;
    categories?: CategoryInfo[];
    tags?: string[];
    type?: string;
    attributes?: any;
};
/** @returns {CouponDetails} */
declare function CouponDetails(): CouponDetails;
type CouponDetails = {
    discount_single_quantity?: number;
    code?: string;
    discount_total_quantity?: number;
};
/** @returns {CartProductInfo} */
declare function CartProductInfo(): CartProductInfo;
type CartProductInfo = {
    article?: ProductArticle;
    moq?: any;
    identifiers: CartProductIdentifer;
    promo_meta?: PromoMeta;
    price?: ProductPriceInfo;
    quantity?: number;
    charges?: Charges[];
    discount?: string;
    availability?: ProductAvailability;
    delivery_promise?: ShipmentPromise;
    product?: CartProduct;
    product_ean_id?: string;
    bulk_offer?: any;
    parent_item_identifiers?: any;
    coupon?: CouponDetails;
    custom_order?: any;
    coupon_message?: string;
    key?: string;
    message?: string;
    is_set?: boolean;
    price_per_unit?: ProductPricePerUnitInfo;
    promotions_applied?: AppliedPromotion[];
};
/** @returns {DisplayBreakup} */
declare function DisplayBreakup(): DisplayBreakup;
type DisplayBreakup = {
    currency_symbol?: string;
    key?: string;
    display?: string;
    message?: string[];
    currency_code?: string;
    value?: number;
    preset?: number;
};
/** @returns {RawBreakup} */
declare function RawBreakup(): RawBreakup;
type RawBreakup = {
    vog?: number;
    subtotal?: number;
    fynd_cash?: number;
    discount?: number;
    convenience_fee?: number;
    delivery_charge?: number;
    gst_charges?: number;
    mrp_total?: number;
    mop_total?: number;
    total_charge?: number;
    coupon?: number;
    total?: number;
    gift_card?: number;
    you_saved?: number;
    cod_charge?: number;
};
/** @returns {CouponBreakup} */
declare function CouponBreakup(): CouponBreakup;
type CouponBreakup = {
    coupon_value?: number;
    title?: string;
    sub_title?: string;
    minimum_cart_value?: number;
    message?: string;
    coupon_type?: string;
    uid?: string;
    value?: number;
    max_discount_value?: number;
    is_applied?: boolean;
    description?: string;
    code?: string;
    type?: string;
};
/** @returns {LoyaltyPoints} */
declare function LoyaltyPoints(): LoyaltyPoints;
type LoyaltyPoints = {
    total?: number;
    description?: string;
    applicable?: number;
    is_applied?: boolean;
};
/** @returns {CartBreakup} */
declare function CartBreakup(): CartBreakup;
type CartBreakup = {
    display?: DisplayBreakup[];
    raw?: RawBreakup;
    coupon?: CouponBreakup;
    loyalty_points?: LoyaltyPoints;
};
/** @returns {CartCurrency} */
declare function CartCurrency(): CartCurrency;
type CartCurrency = {
    /**
     * - Currency code defined by ISO 4217:2015
     */
    code?: string;
    symbol?: string;
};
/** @returns {CartDetailCoupon} */
declare function CartDetailCoupon(): CartDetailCoupon;
type CartDetailCoupon = {
    cashback_amount?: number;
    cashback_message_primary?: string;
    cashback_message_secondary?: string;
    coupon_code?: string;
    coupon_description?: string;
    coupon_id?: string;
    coupon_subtitle?: string;
    coupon_title?: string;
    coupon_type?: string;
    coupon_value?: number;
    discount?: number;
    is_applied?: boolean;
    is_valid?: boolean;
    maximum_discount_value?: number;
    message?: string;
    minimum_cart_value?: number;
};
/** @returns {ChargesThreshold} */
declare function ChargesThreshold(): ChargesThreshold;
type ChargesThreshold = {
    charges?: number;
    threshold?: number;
};
/** @returns {DeliveryChargesConfig} */
declare function DeliveryChargesConfig(): DeliveryChargesConfig;
type DeliveryChargesConfig = {
    enabled?: boolean;
    charges?: ChargesThreshold[];
};
/** @returns {CartCommonConfig} */
declare function CartCommonConfig(): CartCommonConfig;
type CartCommonConfig = {
    delivery_charges_config?: DeliveryChargesConfig;
};
/** @returns {CartDetailResponse} */
declare function CartDetailResponse(): CartDetailResponse;
type CartDetailResponse = {
    cart_id?: number;
    uid?: string;
    applied_promo_details?: AppliedPromotion[];
    checkout_mode?: string;
    pan_no?: string;
    is_valid?: boolean;
    id?: string;
    payment_selection_lock?: PaymentSelectionLock;
    delivery_promise?: ShipmentPromise;
    comment?: string;
    items?: CartProductInfo[];
    delivery_charge_info?: string;
    common_config?: CartCommonConfig;
    coupon?: CartDetailCoupon;
    message?: string;
    notification?: any;
    staff_user_id?: string;
    success?: boolean;
    gstin?: string;
    restrict_checkout?: boolean;
    last_modified?: string;
    breakup_values?: CartBreakup;
    currency?: CartCurrency;
    coupon_text?: string;
    buy_now?: boolean;
    pan_config?: any;
    custom_cart_meta?: any;
};
/** @returns {AddProductCart} */
declare function AddProductCart(): AddProductCart;
type AddProductCart = {
    article_assignment?: any;
    product_group_tags?: string[];
    extra_meta?: any;
    quantity?: number;
    _custom_json?: any;
    item_size?: string;
    store_id?: number;
    display?: string;
    article_id?: string;
    parent_item_identifiers?: any[];
    seller_id?: number;
    pos?: boolean;
    item_id?: number;
    meta?: any;
    /**
     * - Add items using seller identifier for store os
     */
    seller_identifier?: string;
};
/** @returns {AddCartRequest} */
declare function AddCartRequest(): AddCartRequest;
type AddCartRequest = {
    items?: AddProductCart[];
    new_cart?: boolean;
};
/** @returns {AddCartDetailResponse} */
declare function AddCartDetailResponse(): AddCartDetailResponse;
type AddCartDetailResponse = {
    message?: string;
    /**
     * - When adding multiple items check if all
     * added. True if only few are added.
     */
    partial?: boolean;
    cart?: CartDetailResponse;
    /**
     * - True if all items are added successfully.
     * False if partially added or not added.
     */
    success?: boolean;
};
/** @returns {UpdateProductCart} */
declare function UpdateProductCart(): UpdateProductCart;
type UpdateProductCart = {
    extra_meta?: any;
    _custom_json?: any;
    quantity?: number;
    item_size?: string;
    item_index?: number;
    identifiers: CartProductIdentifer;
    article_id?: string;
    parent_item_identifiers?: any;
    item_id?: number;
    meta?: any;
};
/** @returns {UpdateCartRequest} */
declare function UpdateCartRequest(): UpdateCartRequest;
type UpdateCartRequest = {
    items?: UpdateProductCart[];
    operation: string;
};
/** @returns {UpdateCartDetailResponse} */
declare function UpdateCartDetailResponse(): UpdateCartDetailResponse;
type UpdateCartDetailResponse = {
    message?: string;
    cart?: CartDetailResponse;
    /**
     * - True if all items are added successfully.
     * False if partially added or not added.
     */
    success?: boolean;
};
/** @returns {DeleteCartDetailResponse} */
declare function DeleteCartDetailResponse(): DeleteCartDetailResponse;
type DeleteCartDetailResponse = {
    message?: string;
    /**
     * - True if cart is archived successfully. False
     * if not archived.
     */
    success?: boolean;
};
/** @returns {CartItemCountResponse} */
declare function CartItemCountResponse(): CartItemCountResponse;
type CartItemCountResponse = {
    /**
     * - Item count present in cart
     */
    user_cart_items_count?: number;
};
/** @returns {PageCoupon} */
declare function PageCoupon(): PageCoupon;
type PageCoupon = {
    total_item_count?: number;
    has_next?: boolean;
    total?: number;
    current?: number;
    has_previous?: boolean;
};
/** @returns {Coupon} */
declare function Coupon(): Coupon;
type Coupon = {
    /**
     * - The amount based on cart value
     */
    coupon_amount?: number;
    coupon_value?: number;
    title?: string;
    minimum_cart_value?: number;
    sub_title?: string;
    expires_on?: string;
    message?: string;
    coupon_type?: string;
    max_discount_value?: number;
    coupon_code?: string;
    is_applicable?: boolean;
    description?: string;
    is_applied?: boolean;
    start_date?: string;
    end_date?: string;
    coupon_applicable_message?: string;
    offer_text?: string;
    is_bank_offer?: boolean;
};
/** @returns {GetCouponResponse} */
declare function GetCouponResponse(): GetCouponResponse;
type GetCouponResponse = {
    page?: PageCoupon;
    available_coupon_list?: Coupon[];
};
/** @returns {ApplyCouponRequest} */
declare function ApplyCouponRequest(): ApplyCouponRequest;
type ApplyCouponRequest = {
    /**
     * - Coupon code to be applied
     */
    coupon_code: string;
};
/** @returns {OfferPrice} */
declare function OfferPrice(): OfferPrice;
type OfferPrice = {
    /**
     * - Currency symbol for currency
     */
    currency_symbol?: string;
    /**
     * - Discounted per unit price for current
     * offer object
     */
    bulk_effective?: number;
    /**
     * - Currency code for all amounts
     */
    currency_code?: string;
    /**
     * - Current per unit price of product after
     * existing deductions
     */
    effective?: number;
    /**
     * - Original price of product
     */
    marked?: number;
};
/** @returns {OfferItem} */
declare function OfferItem(): OfferItem;
type OfferItem = {
    price?: OfferPrice;
    /**
     * - Percentage value of discount
     */
    margin?: number;
    /**
     * - Quantity on which offer is applicable
     */
    quantity?: number;
    /**
     * - Is true for best offer from all offers present
     * for all sellers
     */
    best?: boolean;
    /**
     * - Total price of offer quantity with discount
     */
    total?: number;
    /**
     * - Whether offer discount is auto applied in cart
     */
    auto_applied?: boolean;
    /**
     * - Offer type
     */
    type?: string;
};
/** @returns {OfferSeller} */
declare function OfferSeller(): OfferSeller;
type OfferSeller = {
    /**
     * - Seller id
     */
    uid?: number;
    name?: string;
};
/** @returns {BulkPriceOffer} */
declare function BulkPriceOffer(): BulkPriceOffer;
type BulkPriceOffer = {
    offers?: OfferItem[];
    seller?: OfferSeller;
};
/** @returns {BulkPriceResponse} */
declare function BulkPriceResponse(): BulkPriceResponse;
type BulkPriceResponse = {
    /**
     * - Consist of offers from multiple seller
     */
    data?: BulkPriceOffer[];
};
/** @returns {RewardPointRequest} */
declare function RewardPointRequest(): RewardPointRequest;
type RewardPointRequest = {
    points: boolean;
};
/** @returns {GeoLocation} */
declare function GeoLocation(): GeoLocation;
type GeoLocation = {
    latitude?: number;
    longitude?: number;
};
/** @returns {Address} */
declare function Address(): Address;
type Address = {
    country_iso_code?: string;
    area?: string;
    phone?: string;
    country_phone_code?: string;
    checkout_mode?: string;
    address?: string;
    area_code_slug?: string;
    geo_location?: GeoLocation;
    id?: string;
    _custom_json?: any;
    city?: string;
    sector?: string;
    /**
     * - State code for international address
     */
    state_code?: string;
    created_by_user_id?: string;
    landmark?: string;
    user_id?: string;
    name?: string;
    google_map_point?: any;
    is_active?: boolean;
    tags?: string[];
    country_code?: string;
    address_type?: string;
    country?: string;
    is_default_address?: boolean;
    area_code?: string;
    email?: string;
    state?: string;
    meta?: any;
};
/** @returns {GetAddressesResponse} */
declare function GetAddressesResponse(): GetAddressesResponse;
type GetAddressesResponse = {
    pii_masking?: boolean;
    address?: Address[];
};
/** @returns {SaveAddressResponse} */
declare function SaveAddressResponse(): SaveAddressResponse;
type SaveAddressResponse = {
    id?: string;
    success?: boolean;
    is_default_address?: boolean;
};
/** @returns {UpdateAddressResponse} */
declare function UpdateAddressResponse(): UpdateAddressResponse;
type UpdateAddressResponse = {
    is_updated?: boolean;
    id?: string;
    success?: boolean;
    is_default_address?: boolean;
};
/** @returns {DeleteAddressResponse} */
declare function DeleteAddressResponse(): DeleteAddressResponse;
type DeleteAddressResponse = {
    id?: string;
    is_deleted?: boolean;
};
/** @returns {SelectCartAddressRequest} */
declare function SelectCartAddressRequest(): SelectCartAddressRequest;
type SelectCartAddressRequest = {
    id?: string;
    billing_address_id?: string;
    cart_id?: string;
};
/** @returns {UpdateCartPaymentRequest} */
declare function UpdateCartPaymentRequest(): UpdateCartPaymentRequest;
type UpdateCartPaymentRequest = {
    id?: string;
    payment_identifier?: string;
    address_id?: string;
    merchant_code?: string;
    aggregator_name?: string;
    payment_mode?: string;
};
/** @returns {CouponValidity} */
declare function CouponValidity(): CouponValidity;
type CouponValidity = {
    title?: string;
    discount?: number;
    next_validation_required?: boolean;
    valid?: boolean;
    display_message_en?: string;
    code?: string;
};
/** @returns {PaymentCouponValidate} */
declare function PaymentCouponValidate(): PaymentCouponValidate;
type PaymentCouponValidate = {
    message?: string;
    coupon_validity?: CouponValidity;
    success: boolean;
};
/** @returns {ShipmentResponse} */
declare function ShipmentResponse(): ShipmentResponse;
type ShipmentResponse = {
    shipments?: number;
    promise?: ShipmentPromise;
    order_type?: string;
    box_type?: string;
    shipment_type?: string;
    dp_options?: any;
    dp_id?: string;
    items?: CartProductInfo[];
    fulfillment_type?: string;
    fulfillment_id?: number;
};
/** @returns {CartShipmentsResponse} */
declare function CartShipmentsResponse(): CartShipmentsResponse;
type CartShipmentsResponse = {
    delivery_charge_info?: string;
    checkout_mode?: string;
    message?: string;
    gstin?: string;
    restrict_checkout?: boolean;
    last_modified?: string;
    cart_id?: number;
    is_valid?: boolean;
    breakup_values?: CartBreakup;
    currency?: CartCurrency;
    id?: string;
    shipments?: ShipmentResponse[];
    payment_selection_lock?: PaymentSelectionLock;
    coupon_text?: string;
    delivery_promise?: ShipmentPromise;
    error?: boolean;
    comment?: string;
    buy_now?: boolean;
    uid?: string;
    custom_cart_meta?: any;
};
/** @returns {CartCheckoutCustomMeta} */
declare function CartCheckoutCustomMeta(): CartCheckoutCustomMeta;
type CartCheckoutCustomMeta = {
    key: string;
    value: string;
};
/** @returns {CustomerDetails} */
declare function CustomerDetails(): CustomerDetails;
type CustomerDetails = {
    email?: string;
    mobile: string;
    name?: string;
};
/** @returns {StaffCheckout} */
declare function StaffCheckout(): StaffCheckout;
type StaffCheckout = {
    employee_code?: string;
    user: string;
    last_name: string;
    first_name: string;
    _id: string;
};
/** @returns {CartCheckoutDetailRequest} */
declare function CartCheckoutDetailRequest(): CartCheckoutDetailRequest;
type CartCheckoutDetailRequest = {
    custom_meta?: CartCheckoutCustomMeta[];
    /**
     * - Customer details
     */
    customer_details?: any;
    merchant_code?: string;
    id?: string;
    payment_auto_confirm?: boolean;
    payment_mode: string;
    aggregator?: string;
    address_id?: string;
    callback_url?: string;
    delivery_address?: any;
    staff?: StaffCheckout;
    order_type?: string;
    ordering_store?: number;
    extra_meta?: any;
    payment_identifier?: string;
    billing_address?: any;
    payment_params?: any;
    billing_address_id?: string;
    meta?: any;
    payment_extra_identifiers?: any;
    iin?: string;
    network?: string;
    type?: string;
    card_id?: string;
};
/** @returns {CheckCart} */
declare function CheckCart(): CheckCart;
type CheckCart = {
    checkout_mode?: string;
    user_type?: string;
    cod_message?: string;
    cart_id?: number;
    is_valid?: boolean;
    delivery_charges?: number;
    id?: string;
    payment_selection_lock?: PaymentSelectionLock;
    error_message?: string;
    delivery_promise?: ShipmentPromise;
    comment?: string;
    items?: CartProductInfo[];
    uid?: string;
    delivery_charge_order_value?: number;
    delivery_charge_info?: string;
    cod_available?: boolean;
    success?: boolean;
    store_code?: string;
    message?: string;
    gstin?: string;
    restrict_checkout?: boolean;
    last_modified?: string;
    order_id?: string;
    breakup_values?: CartBreakup;
    currency?: CartCurrency;
    store_emps?: any[];
    coupon_text?: string;
    buy_now?: boolean;
    cod_charges?: number;
    custom_cart_meta?: any;
};
/** @returns {CartCheckoutResponse} */
declare function CartCheckoutResponse(): CartCheckoutResponse;
type CartCheckoutResponse = {
    payment_confirm_url?: string;
    app_intercept_url?: string;
    success?: boolean;
    callback_url?: string;
    message?: string;
    data?: any;
    order_id?: string;
    cart?: CheckCart;
};
/** @returns {GiftDetail} */
declare function GiftDetail(): GiftDetail;
type GiftDetail = {
    is_gift_applied?: boolean;
    gift_message?: string;
};
/** @returns {ArticleGiftDetail} */
declare function ArticleGiftDetail(): ArticleGiftDetail;
type ArticleGiftDetail = {
    article_id?: GiftDetail;
};
/** @returns {CartMetaRequest} */
declare function CartMetaRequest(): CartMetaRequest;
type CartMetaRequest = {
    delivery_slots?: any;
    gift_details?: ArticleGiftDetail;
    /**
     * - Customer contact details for
     * customer pickup at store
     */
    pick_up_customer_details?: any;
    checkout_mode?: string;
    comment?: string;
    gstin?: string;
    custom_cart_meta?: any;
};
/** @returns {CartMetaResponse} */
declare function CartMetaResponse(): CartMetaResponse;
type CartMetaResponse = {
    message?: string;
    is_valid?: boolean;
};
/** @returns {CartMetaMissingResponse} */
declare function CartMetaMissingResponse(): CartMetaMissingResponse;
type CartMetaMissingResponse = {
    errors?: string[];
};
/** @returns {GetShareCartLinkRequest} */
declare function GetShareCartLinkRequest(): GetShareCartLinkRequest;
type GetShareCartLinkRequest = {
    /**
     * - Cart uid for generating sharing
     */
    id?: string;
    /**
     * - Staff, Ordering store or any other data. This
     * data will be used to generate link as well as sent as shared details.
     */
    meta?: any;
};
/** @returns {GetShareCartLinkResponse} */
declare function GetShareCartLinkResponse(): GetShareCartLinkResponse;
type GetShareCartLinkResponse = {
    /**
     * - Short url unique id
     */
    token?: string;
    /**
     * - Short shareable final url
     */
    share_url?: string;
};
/** @returns {SharedCartDetails} */
declare function SharedCartDetails(): SharedCartDetails;
type SharedCartDetails = {
    /**
     * - Short link id
     */
    token?: string;
    /**
     * - User details of who generated share link
     */
    user?: any;
    created_on?: string;
    /**
     * - Share link device and other source information
     */
    source?: any;
    /**
     * - Meta data sent while generating share cart link
     */
    meta?: any;
};
/** @returns {SharedCart} */
declare function SharedCart(): SharedCart;
type SharedCart = {
    checkout_mode?: string;
    cart_id?: number;
    is_valid?: boolean;
    id?: string;
    payment_selection_lock?: PaymentSelectionLock;
    delivery_promise?: ShipmentPromise;
    comment?: string;
    items?: CartProductInfo[];
    uid?: string;
    delivery_charge_info?: string;
    message?: string;
    gstin?: string;
    shared_cart_details?: SharedCartDetails;
    restrict_checkout?: boolean;
    last_modified?: string;
    breakup_values?: CartBreakup;
    currency?: CartCurrency;
    coupon_text?: string;
    buy_now?: boolean;
    custom_cart_meta?: any;
};
/** @returns {SharedCartResponse} */
declare function SharedCartResponse(): SharedCartResponse;
type SharedCartResponse = {
    error?: string;
    cart?: SharedCart;
};
/** @returns {PriceMinMax} */
declare function PriceMinMax(): PriceMinMax;
type PriceMinMax = {
    min?: number;
    max?: number;
};
/** @returns {ItemPriceDetails} */
declare function ItemPriceDetails(): ItemPriceDetails;
type ItemPriceDetails = {
    marked?: PriceMinMax;
    effective?: PriceMinMax;
    currency?: string;
};
/** @returns {FreeGiftItems} */
declare function FreeGiftItems(): FreeGiftItems;
type FreeGiftItems = {
    /**
     * - Item slug
     */
    item_slug?: string;
    /**
     * - Item name
     */
    item_name?: string;
    item_price_details?: ItemPriceDetails;
    /**
     * - Item brand name
     */
    item_brand_name?: string;
    /**
     * - Item id
     */
    item_id?: number;
    /**
     * - Item images URL
     */
    item_images_url?: string[];
};
/** @returns {PromotionOffer} */
declare function PromotionOffer(): PromotionOffer;
type PromotionOffer = {
    /**
     * - Promotion id
     */
    id?: string;
    /**
     * - Buy rules of promotions
     */
    buy_rules?: any;
    /**
     * - Offer title
     */
    offer_text?: string;
    /**
     * - Promotion type
     */
    promotion_type?: string;
    /**
     * - Name of the promotion
     */
    promotion_name?: string;
    /**
     * - Group of promotion belongs to
     */
    promotion_group?: string;
    /**
     * - Datetime ISOString for promotion end date
     */
    valid_till?: string;
    /**
     * - Discount rules of promotions
     */
    discount_rules?: any[];
    /**
     * - Details of free gift items
     */
    free_gift_items?: FreeGiftItems[];
    /**
     * - Offer details including T&C
     */
    description?: string;
};
/** @returns {PromotionOffersResponse} */
declare function PromotionOffersResponse(): PromotionOffersResponse;
type PromotionOffersResponse = {
    available_promotions?: PromotionOffer[];
};
/** @returns {PromotionPaymentOffer} */
declare function PromotionPaymentOffer(): PromotionPaymentOffer;
type PromotionPaymentOffer = {
    /**
     * - Application id
     */
    application_id?: string;
    /**
     * - Buy rules of promotions
     */
    buy_rules?: any[];
    /**
     * - Price on which promotion calculated
     */
    calculate_on?: string;
    /**
     * - Offer details including T&C
     */
    description?: string;
    /**
     * - Discount rules of promotions
     */
    discount_rules?: any[];
    /**
     * - Promotion id
     */
    id?: string;
    /**
     * - Offer title
     */
    offer_text?: string;
    /**
     * - Group of promotion belongs to
     */
    promotion_group?: string;
    /**
     * - Promotion type
     */
    promotion_type?: string;
    /**
     * - Name of the promotion
     */
    promotion_name?: string;
};
/** @returns {PromotionPaymentOffersResponse} */
declare function PromotionPaymentOffersResponse(): PromotionPaymentOffersResponse;
type PromotionPaymentOffersResponse = {
    success?: boolean;
    promotions?: PromotionPaymentOffer[];
};
/** @returns {OperationErrorResponse} */
declare function OperationErrorResponse(): OperationErrorResponse;
type OperationErrorResponse = {
    message?: string;
    success?: boolean;
};
/** @returns {LadderPrice} */
declare function LadderPrice(): LadderPrice;
type LadderPrice = {
    /**
     * - Currency symbol for currency
     */
    currency_symbol?: string;
    /**
     * - Discounted per unit price for current offer object
     */
    offer_price?: number;
    /**
     * - Currency code for all amounts
     */
    currency_code?: string;
    /**
     * - Current per unit price of product after
     * existing deductions
     */
    effective?: number;
    /**
     * - Original price of product
     */
    marked?: number;
};
/** @returns {LadderOfferItem} */
declare function LadderOfferItem(): LadderOfferItem;
type LadderOfferItem = {
    price?: LadderPrice;
    /**
     * - Percentage value of discount
     */
    margin?: number;
    /**
     * - Minimum quantity upto which offer is
     * applicable. If not present that offer is applicable on all quantities
     */
    max_quantity?: number;
    /**
     * - Minimum quantity from which offer is applicable
     */
    min_quantity?: number;
    /**
     * - Offer type
     */
    type?: string;
};
/** @returns {LadderPriceOffer} */
declare function LadderPriceOffer(): LadderPriceOffer;
type LadderPriceOffer = {
    /**
     * - Promotion id
     */
    id?: string;
    /**
     * - Buy rules of promotions
     */
    buy_rules?: any;
    /**
     * - If this ladder offer is to be calculated
     * on MRP or ESP price
     */
    calculate_on?: string;
    /**
     * - Offer title
     */
    offer_text?: string;
    /**
     * - Group of promotion belongs to
     */
    promotion_group?: string;
    /**
     * - Datetime ISOString for promotion end date
     */
    valid_till?: string;
    /**
     * - Discount rules of promotions
     */
    discount_rules?: any[];
    offer_prices?: LadderOfferItem[];
    /**
     * - Details of free gift items
     */
    free_gift_items?: FreeGiftItems[];
    /**
     * - Offer details including T&C
     */
    description?: string;
};
/** @returns {CurrencyInfo} */
declare function CurrencyInfo(): CurrencyInfo;
type CurrencyInfo = {
    code?: string;
    symbol?: string;
};
/** @returns {LadderPriceOffers} */
declare function LadderPriceOffers(): LadderPriceOffers;
type LadderPriceOffers = {
    available_offers?: LadderPriceOffer[];
    currency?: CurrencyInfo;
};
/** @returns {PaymentMeta} */
declare function PaymentMeta(): PaymentMeta;
type PaymentMeta = {
    merchant_code?: string;
    type?: string;
    payment_gateway?: string;
    payment_identifier?: string;
};
/** @returns {PaymentMethod} */
declare function PaymentMethod(): PaymentMethod;
type PaymentMethod = {
    payment_meta: PaymentMeta;
    mode: string;
    payment?: string;
    amount?: number;
    name?: string;
    payment_extra_identifiers?: any;
};
/** @returns {CartCheckoutDetailV2Request} */
declare function CartCheckoutDetailV2Request(): CartCheckoutDetailV2Request;
type CartCheckoutDetailV2Request = {
    custom_meta?: any;
    /**
     * - Customer details
     */
    customer_details?: any;
    merchant_code?: string;
    cart_id?: string;
    id?: string;
    payment_auto_confirm?: boolean;
    payment_methods: PaymentMethod[];
    payment_mode: string;
    aggregator?: string;
    address_id?: string;
    callback_url?: string;
    delivery_address?: any;
    staff?: StaffCheckout;
    order_type?: string;
    ordering_store?: number;
    extra_meta?: any;
    payment_identifier?: string;
    billing_address?: any;
    payment_params?: any;
    billing_address_id?: string;
    meta?: any;
    iin?: string;
    network?: string;
    type?: string;
    card_id?: string;
};
