export = PaymentPlatformApplicationValidator;
/**
 * @typedef AddEdcDeviceParam
 * @property {string} terminalUniqueIdentifier - Terminal unique identifier
 * @property {PaymentPlatformModel.EdcUpdate} body
 */
/**
 * @typedef AddRefundBankAccountUsingOTPParam
 * @property {PaymentPlatformModel.AddBeneficiaryDetailsOTPCreation} body
 */
/**
 * @typedef CancelPaymentLinkParam
 * @property {PaymentPlatformModel.CancelOrResendPaymentLinkCreation} body
 */
/**
 * @typedef CheckAndUpdatePaymentStatusParam
 * @property {PaymentPlatformModel.PaymentStatusUpdateCreation} body
 */
/**
 * @typedef ConfirmPaymentParam
 * @property {PaymentPlatformModel.PaymentConfirmationCreation} body
 */
/**
 * @typedef CreateMerchantRefundPriorityParam
 * @property {string} configType - Configuration for merchant or customer
 * @property {PaymentPlatformModel.RefundPriorityCreation} body
 */
/**
 * @typedef CreatePaymentLinkParam
 * @property {PaymentPlatformModel.CreatePaymentLinkCreation} body
 */
/**
 * @typedef CreatePaymentOrderParam
 * @property {PaymentPlatformModel.PaymentOrderCreation} body
 */
/** @typedef EdcAggregatorsAndModelListParam */
/**
 * @typedef EdcDeviceListParam
 * @property {number} [pageNo]
 * @property {number} [pageSize]
 * @property {boolean} [isActive]
 * @property {number} [storeId]
 * @property {string} [deviceTag]
 */
/** @typedef EdcDeviceStatsParam */
/**
 * @typedef GetBankAccountDetailsOpenAPIParam
 * @property {string} orderId
 * @property {string} [requestHash]
 */
/**
 * @typedef GetBrandPaymentGatewayConfigParam
 * @property {string} aggregator - Aggregator slug
 * @property {string} [configType]
 */
/**
 * @typedef GetEdcDeviceParam
 * @property {string} terminalUniqueIdentifier - Terminal unique identifier
 */
/**
 * @typedef GetMerchantAggregatorAppVersionParam
 * @property {number} aggregatorId - Aggregators Id
 * @property {string} businessUnit
 * @property {string} device
 * @property {number} [paymentModeId]
 * @property {string} [subPaymentMode]
 */
/**
 * @typedef GetMerchantAggregatorPaymentModeDetailsParam
 * @property {number} aggregatorId - Aggregators Id
 * @property {string} businessUnit
 * @property {string} device
 */
/** @typedef GetMerchantPaymentOptionParam */
/**
 * @typedef GetMerchantRefundPriorityParam
 * @property {string} configType - Configuration for merchant or customer
 */
/** @typedef GetPGConfigAggregatorsParam */
/** @typedef GetPaymentCodeOptionParam */
/**
 * @typedef GetPaymentLinkParam
 * @property {string} paymentLinkId
 */
/**
 * @typedef GetPaymentModeControlRoutesParam
 * @property {string} mode - Offline / advance modes to get the payment modes
 */
/**
 * @typedef GetPaymentModeCustomConfigParam
 * @property {string} mode - Offline / advance mode
 */
/**
 * @typedef GetPaymentModeRoutesParam
 * @property {boolean} [refresh] - Flag to refresh the cache and retrieve the
 *   updated payment option
 * @property {string} [requestType] - Type of payment request, i.e. self
 * @property {string} [orderId] - Order id for the payment
 * @property {string} [shipmentId] - Shipment id for the payment
 * @property {number} [amount] - Amount for the payment
 */
/**
 * @typedef GetPaymentSessionParam
 * @property {string} gid - Global identifier of the entity (e.g. order, cart
 *   etc.) against which payment session was initiated. This is generated by
 *   Fynd payments platform and is unique.
 * @property {boolean} [lineItem] - A boolean flag to include detailed cart and
 *   line item information in the response. When set to true, the response will
 *   contain comprehensive details about the cart, including each line item's
 *   product or service descriptions, quantities, unit prices, applicable taxes,
 *   discounts, total cart value, and total quantity. This provides a clear
 *   breakdown of charges to the customer, helping to understand the total
 *   amount billed in a more granular way.
 */
/**
 * @typedef GetPosPaymentModeRoutesParam
 * @property {number} amount - Payable amount.
 * @property {string} [cartId] - Identifier of the cart.
 * @property {string} pincode - The PIN Code of the destination address, e.g. 400059
 * @property {string} [checkoutMode] - Option to checkout for self or for others.
 * @property {boolean} [refresh] - This is a boolean value. Select `true` to
 *   remove temporary cache files on payment gateway and replace with the latest one.
 * @property {string} [orderId]
 * @property {string} [cardReference] - Card reference id of user's debit or credit card.
 * @property {string} orderType - The order type of shipment * HomeDelivery - If
 *   the customer wants the order home-delivered * PickAtStore - If the customer
 *   wants the handover of an order at the store itself.
 * @property {string} [userDetails] - URIencoded JSON containing details of an
 *   anonymous user.
 * @property {boolean} [displaySplit] - Display Split Payment Option or not
 * @property {boolean} [advancePayment] - Display Advance Payment Options or Normal
 * @property {string} [shipmentId]
 */
/**
 * @typedef GetUserBeneficiariesParam
 * @property {string} orderId
 */
/**
 * @typedef GetUserCODlimitRoutesParam
 * @property {string} merchantUserId
 * @property {string} mobileNo
 */
/**
 * @typedef GetUserOrderBeneficiariesParam
 * @property {string} orderId
 */
/**
 * @typedef InitialisePaymentParam
 * @property {PaymentPlatformModel.PaymentInitializationCreation} body
 */
/**
 * @typedef MerchantOnBoardingParam
 * @property {PaymentPlatformModel.MerchantOnBoardingCreation} body
 */
/**
 * @typedef OauthGetUrlParam
 * @property {string} aggregator - Aggregator
 * @property {string} [successRedirectUrl]
 * @property {string} [failureRedirectUrl]
 */
/**
 * @typedef PatchMerchantAggregatorPaymentModeDetailsParam
 * @property {number} aggregatorId - Aggregators Id
 * @property {PaymentPlatformModel.PlatformPaymentModeDetails} body
 */
/**
 * @typedef PatchMerchantPaymentOptionParam
 * @property {PaymentPlatformModel.MerchnatPaymentModeCreation} body
 */
/**
 * @typedef PatchMerchantPaymentOptionVersionParam
 * @property {number} aggregatorId - Aggregators Id
 * @property {PaymentPlatformModel.PatchAggregatorControl} body
 */
/**
 * @typedef PaymentStatusBulkParam
 * @property {PaymentPlatformModel.PaymentStatusBulkHandlerCreation} body
 */
/**
 * @typedef PollingPaymentLinkParam
 * @property {string} paymentLinkId
 */
/**
 * @typedef RepaymentDetailsParam
 * @property {PaymentPlatformModel.RepaymentDetailsSerialiserPayAll} body
 */
/**
 * @typedef ResendOrCancelPaymentParam
 * @property {PaymentPlatformModel.ResendOrCancelPaymentCreation} body
 */
/**
 * @typedef ResendPaymentLinkParam
 * @property {PaymentPlatformModel.CancelOrResendPaymentLinkCreation} body
 */
/**
 * @typedef RevokeOauthTokenParam
 * @property {string} aggregator - Aggregator_slug
 */
/**
 * @typedef SaveBrandPaymentGatewayConfigParam
 * @property {PaymentPlatformModel.PaymentGatewayConfigCreation} body
 */
/**
 * @typedef SetMerchantModeControlRoutesParam
 * @property {string} mode - Offline / advance payment mode
 * @property {PaymentPlatformModel.MerchantPaymentModeCreation} body
 */
/**
 * @typedef SetPaymentModeCustomConfigParam
 * @property {string} mode - Offline / advance payment mode
 * @property {PaymentPlatformModel.PaymentCustomConfigRequestSchema} body
 */
/**
 * @typedef SetUserCODlimitRoutesParam
 * @property {PaymentPlatformModel.SetCODForUserCreation} body
 */
/**
 * @typedef UpdateEdcDeviceParam
 * @property {PaymentPlatformModel.EdcAddCreation} body
 */
/**
 * @typedef UpdateMerchantRefundPriorityParam
 * @property {string} configType - Configuration for merchant or customer
 * @property {PaymentPlatformModel.RefundPriorityCreation} body
 */
/**
 * @typedef UpdatePaymentSessionParam
 * @property {string} gid - Global identifier of the entity (e.g. order, cart
 *   etc.) against which payment_session was initiated. This is generated by
 *   Fynd payments platform and is unique.
 * @property {PaymentPlatformModel.PaymentSessionCreation} body
 */
/**
 * @typedef UpdateRefundSessionParam
 * @property {string} gid - Global identifier of the entity (e.g. order, cart
 *   etc.) against which payment_session was initiated. This is generated by
 *   Fynd payments platform and is unique.
 * @property {string} requestId - A unique id that was used to initiate a refund
 *   session. This is generated by Fynd platform and is usually shipment_id.
 * @property {PaymentPlatformModel.RefundSessionCreation} body
 */
/**
 * @typedef ValidateCustomerAndCreditSummaryParam
 * @property {PaymentPlatformModel.CustomerValidationSchema} body
 */
/**
 * @typedef VerifyCustomerForPaymentParam
 * @property {PaymentPlatformModel.ValidateCustomerCreation} body
 */
declare class PaymentPlatformApplicationValidator {
    /** @returns {AddEdcDeviceParam} */
    static addEdcDevice(): AddEdcDeviceParam;
    /** @returns {AddRefundBankAccountUsingOTPParam} */
    static addRefundBankAccountUsingOTP(): AddRefundBankAccountUsingOTPParam;
    /** @returns {CancelPaymentLinkParam} */
    static cancelPaymentLink(): CancelPaymentLinkParam;
    /** @returns {CheckAndUpdatePaymentStatusParam} */
    static checkAndUpdatePaymentStatus(): CheckAndUpdatePaymentStatusParam;
    /** @returns {ConfirmPaymentParam} */
    static confirmPayment(): ConfirmPaymentParam;
    /** @returns {CreateMerchantRefundPriorityParam} */
    static createMerchantRefundPriority(): CreateMerchantRefundPriorityParam;
    /** @returns {CreatePaymentLinkParam} */
    static createPaymentLink(): CreatePaymentLinkParam;
    /** @returns {CreatePaymentOrderParam} */
    static createPaymentOrder(): CreatePaymentOrderParam;
    /** @returns {EdcAggregatorsAndModelListParam} */
    static edcAggregatorsAndModelList(): any;
    /** @returns {EdcDeviceListParam} */
    static edcDeviceList(): EdcDeviceListParam;
    /** @returns {EdcDeviceStatsParam} */
    static edcDeviceStats(): any;
    /** @returns {GetBankAccountDetailsOpenAPIParam} */
    static getBankAccountDetailsOpenAPI(): GetBankAccountDetailsOpenAPIParam;
    /** @returns {GetBrandPaymentGatewayConfigParam} */
    static getBrandPaymentGatewayConfig(): GetBrandPaymentGatewayConfigParam;
    /** @returns {GetEdcDeviceParam} */
    static getEdcDevice(): GetEdcDeviceParam;
    /** @returns {GetMerchantAggregatorAppVersionParam} */
    static getMerchantAggregatorAppVersion(): GetMerchantAggregatorAppVersionParam;
    /** @returns {GetMerchantAggregatorPaymentModeDetailsParam} */
    static getMerchantAggregatorPaymentModeDetails(): GetMerchantAggregatorPaymentModeDetailsParam;
    /** @returns {GetMerchantPaymentOptionParam} */
    static getMerchantPaymentOption(): any;
    /** @returns {GetMerchantRefundPriorityParam} */
    static getMerchantRefundPriority(): GetMerchantRefundPriorityParam;
    /** @returns {GetPGConfigAggregatorsParam} */
    static getPGConfigAggregators(): any;
    /** @returns {GetPaymentCodeOptionParam} */
    static getPaymentCodeOption(): any;
    /** @returns {GetPaymentLinkParam} */
    static getPaymentLink(): GetPaymentLinkParam;
    /** @returns {GetPaymentModeControlRoutesParam} */
    static getPaymentModeControlRoutes(): GetPaymentModeControlRoutesParam;
    /** @returns {GetPaymentModeCustomConfigParam} */
    static getPaymentModeCustomConfig(): GetPaymentModeCustomConfigParam;
    /** @returns {GetPaymentModeRoutesParam} */
    static getPaymentModeRoutes(): GetPaymentModeRoutesParam;
    /** @returns {GetPaymentSessionParam} */
    static getPaymentSession(): GetPaymentSessionParam;
    /** @returns {GetPosPaymentModeRoutesParam} */
    static getPosPaymentModeRoutes(): GetPosPaymentModeRoutesParam;
    /** @returns {GetUserBeneficiariesParam} */
    static getUserBeneficiaries(): GetUserBeneficiariesParam;
    /** @returns {GetUserCODlimitRoutesParam} */
    static getUserCODlimitRoutes(): GetUserCODlimitRoutesParam;
    /** @returns {GetUserOrderBeneficiariesParam} */
    static getUserOrderBeneficiaries(): GetUserOrderBeneficiariesParam;
    /** @returns {InitialisePaymentParam} */
    static initialisePayment(): InitialisePaymentParam;
    /** @returns {MerchantOnBoardingParam} */
    static merchantOnBoarding(): MerchantOnBoardingParam;
    /** @returns {OauthGetUrlParam} */
    static oauthGetUrl(): OauthGetUrlParam;
    /** @returns {PatchMerchantAggregatorPaymentModeDetailsParam} */
    static patchMerchantAggregatorPaymentModeDetails(): PatchMerchantAggregatorPaymentModeDetailsParam;
    /** @returns {PatchMerchantPaymentOptionParam} */
    static patchMerchantPaymentOption(): PatchMerchantPaymentOptionParam;
    /** @returns {PatchMerchantPaymentOptionVersionParam} */
    static patchMerchantPaymentOptionVersion(): PatchMerchantPaymentOptionVersionParam;
    /** @returns {PaymentStatusBulkParam} */
    static paymentStatusBulk(): PaymentStatusBulkParam;
    /** @returns {PollingPaymentLinkParam} */
    static pollingPaymentLink(): PollingPaymentLinkParam;
    /** @returns {RepaymentDetailsParam} */
    static repaymentDetails(): RepaymentDetailsParam;
    /** @returns {ResendOrCancelPaymentParam} */
    static resendOrCancelPayment(): ResendOrCancelPaymentParam;
    /** @returns {ResendPaymentLinkParam} */
    static resendPaymentLink(): ResendPaymentLinkParam;
    /** @returns {RevokeOauthTokenParam} */
    static revokeOauthToken(): RevokeOauthTokenParam;
    /** @returns {SaveBrandPaymentGatewayConfigParam} */
    static saveBrandPaymentGatewayConfig(): SaveBrandPaymentGatewayConfigParam;
    /** @returns {SetMerchantModeControlRoutesParam} */
    static setMerchantModeControlRoutes(): SetMerchantModeControlRoutesParam;
    /** @returns {SetPaymentModeCustomConfigParam} */
    static setPaymentModeCustomConfig(): SetPaymentModeCustomConfigParam;
    /** @returns {SetUserCODlimitRoutesParam} */
    static setUserCODlimitRoutes(): SetUserCODlimitRoutesParam;
    /** @returns {UpdateEdcDeviceParam} */
    static updateEdcDevice(): UpdateEdcDeviceParam;
    /** @returns {UpdateMerchantRefundPriorityParam} */
    static updateMerchantRefundPriority(): UpdateMerchantRefundPriorityParam;
    /** @returns {UpdatePaymentSessionParam} */
    static updatePaymentSession(): UpdatePaymentSessionParam;
    /** @returns {UpdateRefundSessionParam} */
    static updateRefundSession(): UpdateRefundSessionParam;
    /** @returns {ValidateCustomerAndCreditSummaryParam} */
    static validateCustomerAndCreditSummary(): ValidateCustomerAndCreditSummaryParam;
    /** @returns {VerifyCustomerForPaymentParam} */
    static verifyCustomerForPayment(): VerifyCustomerForPaymentParam;
}
declare namespace PaymentPlatformApplicationValidator {
    export { AddEdcDeviceParam, AddRefundBankAccountUsingOTPParam, CancelPaymentLinkParam, CheckAndUpdatePaymentStatusParam, ConfirmPaymentParam, CreateMerchantRefundPriorityParam, CreatePaymentLinkParam, CreatePaymentOrderParam, EdcAggregatorsAndModelListParam, EdcDeviceListParam, EdcDeviceStatsParam, GetBankAccountDetailsOpenAPIParam, GetBrandPaymentGatewayConfigParam, GetEdcDeviceParam, GetMerchantAggregatorAppVersionParam, GetMerchantAggregatorPaymentModeDetailsParam, GetMerchantPaymentOptionParam, GetMerchantRefundPriorityParam, GetPGConfigAggregatorsParam, GetPaymentCodeOptionParam, GetPaymentLinkParam, GetPaymentModeControlRoutesParam, GetPaymentModeCustomConfigParam, GetPaymentModeRoutesParam, GetPaymentSessionParam, GetPosPaymentModeRoutesParam, GetUserBeneficiariesParam, GetUserCODlimitRoutesParam, GetUserOrderBeneficiariesParam, InitialisePaymentParam, MerchantOnBoardingParam, OauthGetUrlParam, PatchMerchantAggregatorPaymentModeDetailsParam, PatchMerchantPaymentOptionParam, PatchMerchantPaymentOptionVersionParam, PaymentStatusBulkParam, PollingPaymentLinkParam, RepaymentDetailsParam, ResendOrCancelPaymentParam, ResendPaymentLinkParam, RevokeOauthTokenParam, SaveBrandPaymentGatewayConfigParam, SetMerchantModeControlRoutesParam, SetPaymentModeCustomConfigParam, SetUserCODlimitRoutesParam, UpdateEdcDeviceParam, UpdateMerchantRefundPriorityParam, UpdatePaymentSessionParam, UpdateRefundSessionParam, ValidateCustomerAndCreditSummaryParam, VerifyCustomerForPaymentParam };
}
type AddEdcDeviceParam = {
    /**
     * - Terminal unique identifier
     */
    terminalUniqueIdentifier: string;
    body: PaymentPlatformModel.EdcUpdate;
};
type AddRefundBankAccountUsingOTPParam = {
    body: PaymentPlatformModel.AddBeneficiaryDetailsOTPCreation;
};
type CancelPaymentLinkParam = {
    body: PaymentPlatformModel.CancelOrResendPaymentLinkCreation;
};
type CheckAndUpdatePaymentStatusParam = {
    body: PaymentPlatformModel.PaymentStatusUpdateCreation;
};
type ConfirmPaymentParam = {
    body: PaymentPlatformModel.PaymentConfirmationCreation;
};
type CreateMerchantRefundPriorityParam = {
    /**
     * - Configuration for merchant or customer
     */
    configType: string;
    body: PaymentPlatformModel.RefundPriorityCreation;
};
type CreatePaymentLinkParam = {
    body: PaymentPlatformModel.CreatePaymentLinkCreation;
};
type CreatePaymentOrderParam = {
    body: PaymentPlatformModel.PaymentOrderCreation;
};
type EdcDeviceListParam = {
    pageNo?: number;
    pageSize?: number;
    isActive?: boolean;
    storeId?: number;
    deviceTag?: string;
};
type GetBankAccountDetailsOpenAPIParam = {
    orderId: string;
    requestHash?: string;
};
type GetBrandPaymentGatewayConfigParam = {
    /**
     * - Aggregator slug
     */
    aggregator: string;
    configType?: string;
};
type GetEdcDeviceParam = {
    /**
     * - Terminal unique identifier
     */
    terminalUniqueIdentifier: string;
};
type GetMerchantAggregatorAppVersionParam = {
    /**
     * - Aggregators Id
     */
    aggregatorId: number;
    businessUnit: string;
    device: string;
    paymentModeId?: number;
    subPaymentMode?: string;
};
type GetMerchantAggregatorPaymentModeDetailsParam = {
    /**
     * - Aggregators Id
     */
    aggregatorId: number;
    businessUnit: string;
    device: string;
};
type GetMerchantRefundPriorityParam = {
    /**
     * - Configuration for merchant or customer
     */
    configType: string;
};
type GetPaymentLinkParam = {
    paymentLinkId: string;
};
type GetPaymentModeControlRoutesParam = {
    /**
     * - Offline / advance modes to get the payment modes
     */
    mode: string;
};
type GetPaymentModeCustomConfigParam = {
    /**
     * - Offline / advance mode
     */
    mode: string;
};
type GetPaymentModeRoutesParam = {
    /**
     * - Flag to refresh the cache and retrieve the
     * updated payment option
     */
    refresh?: boolean;
    /**
     * - Type of payment request, i.e. self
     */
    requestType?: string;
    /**
     * - Order id for the payment
     */
    orderId?: string;
    /**
     * - Shipment id for the payment
     */
    shipmentId?: string;
    /**
     * - Amount for the payment
     */
    amount?: number;
};
type GetPaymentSessionParam = {
    /**
     * - Global identifier of the entity (e.g. order, cart
     * etc.) against which payment session was initiated. This is generated by
     * Fynd payments platform and is unique.
     */
    gid: string;
    /**
     * - A boolean flag to include detailed cart and
     * line item information in the response. When set to true, the response will
     * contain comprehensive details about the cart, including each line item's
     * product or service descriptions, quantities, unit prices, applicable taxes,
     * discounts, total cart value, and total quantity. This provides a clear
     * breakdown of charges to the customer, helping to understand the total
     * amount billed in a more granular way.
     */
    lineItem?: boolean;
};
type GetPosPaymentModeRoutesParam = {
    /**
     * - Payable amount.
     */
    amount: number;
    /**
     * - Identifier of the cart.
     */
    cartId?: string;
    /**
     * - The PIN Code of the destination address, e.g. 400059
     */
    pincode: string;
    /**
     * - Option to checkout for self or for others.
     */
    checkoutMode?: string;
    /**
     * - This is a boolean value. Select `true` to
     * remove temporary cache files on payment gateway and replace with the latest one.
     */
    refresh?: boolean;
    orderId?: string;
    /**
     * - Card reference id of user's debit or credit card.
     */
    cardReference?: string;
    /**
     * - The order type of shipment * HomeDelivery - If
     * the customer wants the order home-delivered * PickAtStore - If the customer
     * wants the handover of an order at the store itself.
     */
    orderType: string;
    /**
     * - URIencoded JSON containing details of an
     * anonymous user.
     */
    userDetails?: string;
    /**
     * - Display Split Payment Option or not
     */
    displaySplit?: boolean;
    /**
     * - Display Advance Payment Options or Normal
     */
    advancePayment?: boolean;
    shipmentId?: string;
};
type GetUserBeneficiariesParam = {
    orderId: string;
};
type GetUserCODlimitRoutesParam = {
    merchantUserId: string;
    mobileNo: string;
};
type GetUserOrderBeneficiariesParam = {
    orderId: string;
};
type InitialisePaymentParam = {
    body: PaymentPlatformModel.PaymentInitializationCreation;
};
type MerchantOnBoardingParam = {
    body: PaymentPlatformModel.MerchantOnBoardingCreation;
};
type OauthGetUrlParam = {
    /**
     * - Aggregator
     */
    aggregator: string;
    successRedirectUrl?: string;
    failureRedirectUrl?: string;
};
type PatchMerchantAggregatorPaymentModeDetailsParam = {
    /**
     * - Aggregators Id
     */
    aggregatorId: number;
    body: PaymentPlatformModel.PlatformPaymentModeDetails;
};
type PatchMerchantPaymentOptionParam = {
    body: PaymentPlatformModel.MerchnatPaymentModeCreation;
};
type PatchMerchantPaymentOptionVersionParam = {
    /**
     * - Aggregators Id
     */
    aggregatorId: number;
    body: PaymentPlatformModel.PatchAggregatorControl;
};
type PaymentStatusBulkParam = {
    body: PaymentPlatformModel.PaymentStatusBulkHandlerCreation;
};
type PollingPaymentLinkParam = {
    paymentLinkId: string;
};
type RepaymentDetailsParam = {
    body: PaymentPlatformModel.RepaymentDetailsSerialiserPayAll;
};
type ResendOrCancelPaymentParam = {
    body: PaymentPlatformModel.ResendOrCancelPaymentCreation;
};
type ResendPaymentLinkParam = {
    body: PaymentPlatformModel.CancelOrResendPaymentLinkCreation;
};
type RevokeOauthTokenParam = {
    /**
     * - Aggregator_slug
     */
    aggregator: string;
};
type SaveBrandPaymentGatewayConfigParam = {
    body: PaymentPlatformModel.PaymentGatewayConfigCreation;
};
type SetMerchantModeControlRoutesParam = {
    /**
     * - Offline / advance payment mode
     */
    mode: string;
    body: PaymentPlatformModel.MerchantPaymentModeCreation;
};
type SetPaymentModeCustomConfigParam = {
    /**
     * - Offline / advance payment mode
     */
    mode: string;
    body: PaymentPlatformModel.PaymentCustomConfigRequestSchema;
};
type SetUserCODlimitRoutesParam = {
    body: PaymentPlatformModel.SetCODForUserCreation;
};
type UpdateEdcDeviceParam = {
    body: PaymentPlatformModel.EdcAddCreation;
};
type UpdateMerchantRefundPriorityParam = {
    /**
     * - Configuration for merchant or customer
     */
    configType: string;
    body: PaymentPlatformModel.RefundPriorityCreation;
};
type UpdatePaymentSessionParam = {
    /**
     * - Global identifier of the entity (e.g. order, cart
     * etc.) against which payment_session was initiated. This is generated by
     * Fynd payments platform and is unique.
     */
    gid: string;
    body: PaymentPlatformModel.PaymentSessionCreation;
};
type UpdateRefundSessionParam = {
    /**
     * - Global identifier of the entity (e.g. order, cart
     * etc.) against which payment_session was initiated. This is generated by
     * Fynd payments platform and is unique.
     */
    gid: string;
    /**
     * - A unique id that was used to initiate a refund
     * session. This is generated by Fynd platform and is usually shipment_id.
     */
    requestId: string;
    body: PaymentPlatformModel.RefundSessionCreation;
};
type ValidateCustomerAndCreditSummaryParam = {
    body: PaymentPlatformModel.CustomerValidationSchema;
};
type VerifyCustomerForPaymentParam = {
    body: PaymentPlatformModel.ValidateCustomerCreation;
};
type EdcAggregatorsAndModelListParam = any;
type EdcDeviceStatsParam = any;
type GetMerchantPaymentOptionParam = any;
type GetPGConfigAggregatorsParam = any;
type GetPaymentCodeOptionParam = any;
import PaymentPlatformModel = require("./PaymentPlatformModel");
