const Joi = require("joi");

const PaymentPlatformModel = require("./PaymentPlatformModel");

/**
 * @typedef AddRefundBankAccountUsingOTPParam
 * @property {PaymentPlatformModel.AddBeneficiaryDetailsOTPCreation} body
 */

/**
 * @typedef CancelPaymentLinkParam
 * @property {PaymentPlatformModel.CancelOrResendPaymentLinkCreation} body
 */

/**
 * @typedef CheckAndUpdatePaymentStatusParam
 * @property {PaymentPlatformModel.PaymentStatusUpdateCreation} body
 */

/**
 * @typedef ConfirmPaymentParam
 * @property {PaymentPlatformModel.PaymentConfirmationCreation} body
 */

/**
 * @typedef CreateMerchantRefundPriorityParam
 * @property {string} configType - Configuration for merchant or customer
 * @property {PaymentPlatformModel.RefundPriorityCreation} body
 */

/**
 * @typedef CreatePaymentLinkParam
 * @property {PaymentPlatformModel.CreatePaymentLinkCreation} body
 */

/**
 * @typedef CreatePaymentOrderParam
 * @property {PaymentPlatformModel.PaymentOrderCreation} body
 */

/**
 * @typedef GetBankAccountDetailsOpenAPIParam
 * @property {string} orderId
 * @property {string} [requestHash]
 */

/**
 * @typedef GetBrandPaymentGatewayConfigParam
 * @property {string} aggregator - Aggregator slug
 * @property {string} [configType]
 */

/**
 * @typedef GetMerchantAggregatorAppVersionParam
 * @property {number} aggregatorId - Aggregators Id
 * @property {string} businessUnit
 * @property {string} device
 * @property {number} [paymentModeId]
 * @property {string} [subPaymentMode]
 */

/**
 * @typedef GetMerchantAggregatorPaymentModeDetailsParam
 * @property {number} aggregatorId - Aggregators Id
 * @property {string} businessUnit
 * @property {string} device
 */

/** @typedef GetMerchantPaymentOptionParam */

/**
 * @typedef GetMerchantRefundPriorityParam
 * @property {string} configType - Configuration for merchant or customer
 */

/** @typedef GetPGConfigAggregatorsParam */

/** @typedef GetPaymentCodeOptionParam */

/**
 * @typedef GetPaymentLinkParam
 * @property {string} paymentLinkId
 */

/**
 * @typedef GetPaymentModeControlRoutesParam
 * @property {string} mode - Offline / advance modes to get the payment modes
 */

/**
 * @typedef GetPaymentModeCustomConfigParam
 * @property {string} mode - Offline / advance mode
 */

/**
 * @typedef GetPaymentModeRoutesParam
 * @property {boolean} [refresh] - Flag to refresh the cache and retrieve the
 *   updated payment option
 * @property {string} [requestType] - Type of payment request, i.e. self
 * @property {string} [orderId] - Order id for the payment
 * @property {string} [shipmentId] - Shipment id for the payment
 * @property {number} [amount] - Amount for the payment
 */

/**
 * @typedef GetPaymentSessionParam
 * @property {string} gid - Global identifier of the entity (e.g. order, cart
 *   etc.) against which payment session was initiated. This is generated by
 *   Fynd payments platform and is unique.
 * @property {boolean} [lineItem] - A boolean flag to include detailed cart and
 *   line item information in the response. When set to true, the response will
 *   contain comprehensive details about the cart, including each line item's
 *   product or service descriptions, quantities, unit prices, applicable taxes,
 *   discounts, total cart value, and total quantity. This provides a clear
 *   breakdown of charges to the customer, helping to understand the total
 *   amount billed in a more granular way.
 */

/**
 * @typedef GetPosPaymentModeRoutesParam
 * @property {string} [xOrderingSource] - Optional header to identify the
 *   ordering source used to determine\ applicable payment options for business unit.
 * @property {number} amount - Payable amount.
 * @property {string} [cartId] - Identifier of the cart.
 * @property {string} pincode - The PIN Code of the destination address, e.g. 400059
 * @property {string} [checkoutMode] - Option to checkout for self or for others.
 * @property {boolean} [refresh] - This is a boolean value. Select `true` to
 *   remove temporary cache files on payment gateway and replace with the latest one.
 * @property {string} [orderId]
 * @property {string} [cardReference] - Card reference id of user's debit or credit card.
 * @property {string} orderType - The order type of shipment * HomeDelivery - If
 *   the customer wants the order home-delivered * PickAtStore - If the customer
 *   wants the handover of an order at the store itself.
 * @property {string} [userDetails] - URIencoded JSON containing details of an
 *   anonymous user.
 * @property {boolean} [displaySplit] - Display Split Payment Option or not
 * @property {boolean} [advancePayment] - Display Advance Payment Options or Normal
 * @property {string} [shipmentId]
 * @property {string} [customerId]
 */

/**
 * @typedef GetUserBeneficiariesParam
 * @property {string} orderId
 */

/**
 * @typedef GetUserCODlimitRoutesParam
 * @property {string} merchantUserId
 * @property {string} mobileNo
 */

/**
 * @typedef GetUserOrderBeneficiariesParam
 * @property {string} orderId
 */

/**
 * @typedef InitialisePaymentParam
 * @property {PaymentPlatformModel.PaymentInitializationCreation} body
 */

/**
 * @typedef MerchantOnBoardingParam
 * @property {PaymentPlatformModel.MerchantOnBoardingCreation} body
 */

/**
 * @typedef OauthGetUrlParam
 * @property {string} aggregator - Aggregator
 * @property {string} [successRedirectUrl]
 * @property {string} [failureRedirectUrl]
 */

/**
 * @typedef PatchMerchantAggregatorPaymentModeDetailsParam
 * @property {number} aggregatorId - Aggregators Id
 * @property {PaymentPlatformModel.PlatformPaymentModeDetails} body
 */

/**
 * @typedef PatchMerchantPaymentOptionParam
 * @property {PaymentPlatformModel.MerchnatPaymentModeCreation} body
 */

/**
 * @typedef PatchMerchantPaymentOptionVersionParam
 * @property {number} aggregatorId - Aggregators Id
 * @property {PaymentPlatformModel.PatchAggregatorControl} body
 */

/**
 * @typedef PaymentStatusBulkParam
 * @property {PaymentPlatformModel.PaymentStatusBulkHandlerCreation} body
 */

/**
 * @typedef PollingPaymentLinkParam
 * @property {string} paymentLinkId
 */

/**
 * @typedef RepaymentDetailsParam
 * @property {PaymentPlatformModel.RepaymentDetailsSerialiserPayAll} body
 */

/**
 * @typedef ResendOrCancelPaymentParam
 * @property {PaymentPlatformModel.ResendOrCancelPaymentCreation} body
 */

/**
 * @typedef ResendPaymentLinkParam
 * @property {PaymentPlatformModel.CancelOrResendPaymentLinkCreation} body
 */

/**
 * @typedef RevokeOauthTokenParam
 * @property {string} aggregator - Aggregator_slug
 */

/**
 * @typedef SaveBrandPaymentGatewayConfigParam
 * @property {PaymentPlatformModel.PaymentGatewayConfigCreation} body
 */

/**
 * @typedef SetMerchantModeControlRoutesParam
 * @property {string} mode - Offline / advance payment mode
 * @property {PaymentPlatformModel.MerchantPaymentModeCreation} body
 */

/**
 * @typedef SetPaymentModeCustomConfigParam
 * @property {string} mode - Offline / advance payment mode
 * @property {PaymentPlatformModel.PaymentCustomConfigRequestSchema} body
 */

/**
 * @typedef SetUserCODlimitRoutesParam
 * @property {PaymentPlatformModel.SetCODForUserCreation} body
 */

/**
 * @typedef UpdateMerchantRefundPriorityParam
 * @property {string} configType - Configuration for merchant or customer
 * @property {PaymentPlatformModel.RefundPriorityCreation} body
 */

/**
 * @typedef UpdatePaymentSessionParam
 * @property {string} gid - Global identifier of the entity (e.g. order, cart
 *   etc.) against which payment_session was initiated. This is generated by
 *   Fynd payments platform and is unique.
 * @property {PaymentPlatformModel.PaymentSessionCreation} body
 */

/**
 * @typedef UpdateRefundSessionParam
 * @property {string} gid - Global identifier of the entity (e.g. order, cart
 *   etc.) against which payment_session was initiated. This is generated by
 *   Fynd payments platform and is unique.
 * @property {string} requestId - A unique id that was used to initiate a refund
 *   session. This is generated by Fynd platform and is usually shipment_id.
 * @property {PaymentPlatformModel.RefundSessionCreation} body
 */

/**
 * @typedef ValidateCustomerAndCreditSummaryParam
 * @property {PaymentPlatformModel.CustomerValidationSchema} body
 */

/**
 * @typedef VerifyCustomerForPaymentParam
 * @property {PaymentPlatformModel.ValidateCustomerCreation} body
 */

class PaymentPlatformApplicationValidator {
  /** @returns {AddRefundBankAccountUsingOTPParam} */
  static addRefundBankAccountUsingOTP() {
    return Joi.object({
      body: PaymentPlatformModel.AddBeneficiaryDetailsOTPCreation().required(),
    }).required();
  }

  /** @returns {CancelPaymentLinkParam} */
  static cancelPaymentLink() {
    return Joi.object({
      body: PaymentPlatformModel.CancelOrResendPaymentLinkCreation().required(),
    }).required();
  }

  /** @returns {CheckAndUpdatePaymentStatusParam} */
  static checkAndUpdatePaymentStatus() {
    return Joi.object({
      body: PaymentPlatformModel.PaymentStatusUpdateCreation().required(),
    }).required();
  }

  /** @returns {ConfirmPaymentParam} */
  static confirmPayment() {
    return Joi.object({
      body: PaymentPlatformModel.PaymentConfirmationCreation().required(),
    }).required();
  }

  /** @returns {CreateMerchantRefundPriorityParam} */
  static createMerchantRefundPriority() {
    return Joi.object({
      configType: Joi.string().allow("").required(),
      body: PaymentPlatformModel.RefundPriorityCreation().required(),
    }).required();
  }

  /** @returns {CreatePaymentLinkParam} */
  static createPaymentLink() {
    return Joi.object({
      body: PaymentPlatformModel.CreatePaymentLinkCreation().required(),
    }).required();
  }

  /** @returns {CreatePaymentOrderParam} */
  static createPaymentOrder() {
    return Joi.object({
      body: PaymentPlatformModel.PaymentOrderCreation().required(),
    }).required();
  }

  /** @returns {GetBankAccountDetailsOpenAPIParam} */
  static getBankAccountDetailsOpenAPI() {
    return Joi.object({
      orderId: Joi.string().allow("").required(),
      requestHash: Joi.string().allow(""),
    }).required();
  }

  /** @returns {GetBrandPaymentGatewayConfigParam} */
  static getBrandPaymentGatewayConfig() {
    return Joi.object({
      aggregator: Joi.string().allow("").required(),
      configType: Joi.string().allow(""),
    }).required();
  }

  /** @returns {GetMerchantAggregatorAppVersionParam} */
  static getMerchantAggregatorAppVersion() {
    return Joi.object({
      aggregatorId: Joi.number().required(),
      businessUnit: Joi.string().allow("").required(),
      device: Joi.string().allow("").required(),
      paymentModeId: Joi.number(),
      subPaymentMode: Joi.string().allow(""),
    }).required();
  }

  /** @returns {GetMerchantAggregatorPaymentModeDetailsParam} */
  static getMerchantAggregatorPaymentModeDetails() {
    return Joi.object({
      aggregatorId: Joi.number().required(),
      businessUnit: Joi.string().allow("").required(),
      device: Joi.string().allow("").required(),
    }).required();
  }

  /** @returns {GetMerchantPaymentOptionParam} */
  static getMerchantPaymentOption() {
    return Joi.object({}).required();
  }

  /** @returns {GetMerchantRefundPriorityParam} */
  static getMerchantRefundPriority() {
    return Joi.object({
      configType: Joi.string().allow("").required(),
    }).required();
  }

  /** @returns {GetPGConfigAggregatorsParam} */
  static getPGConfigAggregators() {
    return Joi.object({}).required();
  }

  /** @returns {GetPaymentCodeOptionParam} */
  static getPaymentCodeOption() {
    return Joi.object({}).required();
  }

  /** @returns {GetPaymentLinkParam} */
  static getPaymentLink() {
    return Joi.object({
      paymentLinkId: Joi.string().allow("").required(),
    }).required();
  }

  /** @returns {GetPaymentModeControlRoutesParam} */
  static getPaymentModeControlRoutes() {
    return Joi.object({
      mode: Joi.string().allow("").required(),
    }).required();
  }

  /** @returns {GetPaymentModeCustomConfigParam} */
  static getPaymentModeCustomConfig() {
    return Joi.object({
      mode: Joi.string().allow("").required(),
    }).required();
  }

  /** @returns {GetPaymentModeRoutesParam} */
  static getPaymentModeRoutes() {
    return Joi.object({
      refresh: Joi.boolean(),
      requestType: Joi.string().allow(""),
      orderId: Joi.string().allow(""),
      shipmentId: Joi.string().allow(""),
      amount: Joi.number(),
    }).required();
  }

  /** @returns {GetPaymentSessionParam} */
  static getPaymentSession() {
    return Joi.object({
      gid: Joi.string().allow("").required(),
      lineItem: Joi.boolean(),
    }).required();
  }

  /** @returns {GetPosPaymentModeRoutesParam} */
  static getPosPaymentModeRoutes() {
    return Joi.object({
      xOrderingSource: Joi.string().allow(""),

      amount: Joi.number().required(),
      cartId: Joi.string().allow(""),
      pincode: Joi.string().allow("").required(),
      checkoutMode: Joi.string().allow(""),
      refresh: Joi.boolean(),
      orderId: Joi.string().allow(""),
      cardReference: Joi.string().allow(""),
      orderType: Joi.string().allow("").required(),
      userDetails: Joi.string().allow(""),
      displaySplit: Joi.boolean(),
      advancePayment: Joi.boolean(),
      shipmentId: Joi.string().allow(""),
      customerId: Joi.string().allow(""),
    }).required();
  }

  /** @returns {GetUserBeneficiariesParam} */
  static getUserBeneficiaries() {
    return Joi.object({
      orderId: Joi.string().allow("").required(),
    }).required();
  }

  /** @returns {GetUserCODlimitRoutesParam} */
  static getUserCODlimitRoutes() {
    return Joi.object({
      merchantUserId: Joi.string().allow("").required(),
      mobileNo: Joi.string().allow("").required(),
    }).required();
  }

  /** @returns {GetUserOrderBeneficiariesParam} */
  static getUserOrderBeneficiaries() {
    return Joi.object({
      orderId: Joi.string().allow("").required(),
    }).required();
  }

  /** @returns {InitialisePaymentParam} */
  static initialisePayment() {
    return Joi.object({
      body: PaymentPlatformModel.PaymentInitializationCreation().required(),
    }).required();
  }

  /** @returns {MerchantOnBoardingParam} */
  static merchantOnBoarding() {
    return Joi.object({
      body: PaymentPlatformModel.MerchantOnBoardingCreation().required(),
    }).required();
  }

  /** @returns {OauthGetUrlParam} */
  static oauthGetUrl() {
    return Joi.object({
      aggregator: Joi.string().allow("").required(),
      successRedirectUrl: Joi.string().allow(""),
      failureRedirectUrl: Joi.string().allow(""),
    }).required();
  }

  /** @returns {PatchMerchantAggregatorPaymentModeDetailsParam} */
  static patchMerchantAggregatorPaymentModeDetails() {
    return Joi.object({
      aggregatorId: Joi.number().required(),
      body: PaymentPlatformModel.PlatformPaymentModeDetails().required(),
    }).required();
  }

  /** @returns {PatchMerchantPaymentOptionParam} */
  static patchMerchantPaymentOption() {
    return Joi.object({
      body: PaymentPlatformModel.MerchnatPaymentModeCreation().required(),
    }).required();
  }

  /** @returns {PatchMerchantPaymentOptionVersionParam} */
  static patchMerchantPaymentOptionVersion() {
    return Joi.object({
      aggregatorId: Joi.number().required(),
      body: PaymentPlatformModel.PatchAggregatorControl().required(),
    }).required();
  }

  /** @returns {PaymentStatusBulkParam} */
  static paymentStatusBulk() {
    return Joi.object({
      body: PaymentPlatformModel.PaymentStatusBulkHandlerCreation().required(),
    }).required();
  }

  /** @returns {PollingPaymentLinkParam} */
  static pollingPaymentLink() {
    return Joi.object({
      paymentLinkId: Joi.string().allow("").required(),
    }).required();
  }

  /** @returns {RepaymentDetailsParam} */
  static repaymentDetails() {
    return Joi.object({
      body: PaymentPlatformModel.RepaymentDetailsSerialiserPayAll().required(),
    }).required();
  }

  /** @returns {ResendOrCancelPaymentParam} */
  static resendOrCancelPayment() {
    return Joi.object({
      body: PaymentPlatformModel.ResendOrCancelPaymentCreation().required(),
    }).required();
  }

  /** @returns {ResendPaymentLinkParam} */
  static resendPaymentLink() {
    return Joi.object({
      body: PaymentPlatformModel.CancelOrResendPaymentLinkCreation().required(),
    }).required();
  }

  /** @returns {RevokeOauthTokenParam} */
  static revokeOauthToken() {
    return Joi.object({
      aggregator: Joi.string().allow("").required(),
    }).required();
  }

  /** @returns {SaveBrandPaymentGatewayConfigParam} */
  static saveBrandPaymentGatewayConfig() {
    return Joi.object({
      body: PaymentPlatformModel.PaymentGatewayConfigCreation().required(),
    }).required();
  }

  /** @returns {SetMerchantModeControlRoutesParam} */
  static setMerchantModeControlRoutes() {
    return Joi.object({
      mode: Joi.string().allow("").required(),
      body: PaymentPlatformModel.MerchantPaymentModeCreation().required(),
    }).required();
  }

  /** @returns {SetPaymentModeCustomConfigParam} */
  static setPaymentModeCustomConfig() {
    return Joi.object({
      mode: Joi.string().allow("").required(),
      body: PaymentPlatformModel.PaymentCustomConfigRequestSchema().required(),
    }).required();
  }

  /** @returns {SetUserCODlimitRoutesParam} */
  static setUserCODlimitRoutes() {
    return Joi.object({
      body: PaymentPlatformModel.SetCODForUserCreation().required(),
    }).required();
  }

  /** @returns {UpdateMerchantRefundPriorityParam} */
  static updateMerchantRefundPriority() {
    return Joi.object({
      configType: Joi.string().allow("").required(),
      body: PaymentPlatformModel.RefundPriorityCreation().required(),
    }).required();
  }

  /** @returns {UpdatePaymentSessionParam} */
  static updatePaymentSession() {
    return Joi.object({
      gid: Joi.string().allow("").required(),
      body: PaymentPlatformModel.PaymentSessionCreation().required(),
    }).required();
  }

  /** @returns {UpdateRefundSessionParam} */
  static updateRefundSession() {
    return Joi.object({
      gid: Joi.string().allow("").required(),
      requestId: Joi.string().allow("").required(),
      body: PaymentPlatformModel.RefundSessionCreation().required(),
    }).required();
  }

  /** @returns {ValidateCustomerAndCreditSummaryParam} */
  static validateCustomerAndCreditSummary() {
    return Joi.object({
      body: PaymentPlatformModel.CustomerValidationSchema().required(),
    }).required();
  }

  /** @returns {VerifyCustomerForPaymentParam} */
  static verifyCustomerForPayment() {
    return Joi.object({
      body: PaymentPlatformModel.ValidateCustomerCreation().required(),
    }).required();
  }
}

module.exports = PaymentPlatformApplicationValidator;
