export = LogisticModel;
declare class LogisticModel {
    static PincodeErrorSchemaResponse(): any;
    static CountryMetaResponse(): any;
    static PincodeLatLongData(): any;
    static PincodeMetaResponse(): any;
    static PincodeParentsResponse(): any;
    static PincodeDataResponse(): any;
    static PincodeApiResponse(): any;
    static TATCategoryRequest(): any;
    static TATArticlesRequest(): any;
    static TATLocationDetailsRequest(): any;
    static TATViewRequest(): any;
    static TATFormattedResponse(): any;
    static TATTimestampResponse(): any;
    static TATPromiseResponse(): any;
    static TATErrorSchemaResponse(): any;
    static TATArticlesResponse(): any;
    static TATLocationDetailsResponse(): any;
    static TATViewResponse(): any;
    static DP(): any;
    static LogisticsResponse(): any;
    static CountryEntityResponse(): any;
    static CountryListResponse(): any;
    static GetZoneFromPincodeViewRequest(): any;
    static GetZoneFromPincodeViewResponse(): any;
    static ReAssignStoreRequest(): any;
    static ReAssignStoreResponse(): any;
}
