export = ApplicationClient;
declare class ApplicationClient {
    constructor(config: any);
    config: any;
    cart: Cart;
    catalog: Catalog;
    common: Common;
    communication: Communication;
    configuration: Configuration;
    content: Content;
    fileStorage: FileStorage;
    lead: Lead;
    logistic: Logistic;
    order: Order;
    payment: Payment;
    posCart: PosCart;
    rewards: Rewards;
    share: Share;
    theme: Theme;
    user: User;
    setCookie(cookie: any): void;
    setLocationDetails(locationDetails: any): void;
    setCurrencyCode(currencyCode: any): void;
    setExtraHeaders(header: any): void;
}
import Cart = require("./Cart/CartApplicationClient");
import Catalog = require("./Catalog/CatalogApplicationClient");
import Common = require("./Common/CommonApplicationClient");
import Communication = require("./Communication/CommunicationApplicationClient");
import Configuration = require("./Configuration/ConfigurationApplicationClient");
import Content = require("./Content/ContentApplicationClient");
import FileStorage = require("./FileStorage/FileStorageApplicationClient");
import Lead = require("./Lead/LeadApplicationClient");
import Logistic = require("./Logistic/LogisticApplicationClient");
import Order = require("./Order/OrderApplicationClient");
import Payment = require("./Payment/PaymentApplicationClient");
import PosCart = require("./PosCart/PosCartApplicationClient");
import Rewards = require("./Rewards/RewardsApplicationClient");
import Share = require("./Share/ShareApplicationClient");
import Theme = require("./Theme/ThemeApplicationClient");
import User = require("./User/UserApplicationClient");
