export = ApplicationClient;
declare class ApplicationClient {
    constructor(config: any);
    catalog: Catalog;
    cart: Cart;
    lead: Lead;
    theme: Theme;
    content: Content;
    communication: Communication;
    share: Share;
    fileStorage: FileStorage;
    configuration: Configuration;
    payment: Payment;
    order: Order;
    rewards: Rewards;
    feedback: Feedback;
    posCart: PosCart;
    logistic: Logistic;
}
import { Catalog } from "./ApplicationModels";
import { Cart } from "./ApplicationModels";
import { Lead } from "./ApplicationModels";
import { Theme } from "./ApplicationModels";
import { Content } from "./ApplicationModels";
import { Communication } from "./ApplicationModels";
import { Share } from "./ApplicationModels";
import { FileStorage } from "./ApplicationModels";
import { Configuration } from "./ApplicationModels";
import { Payment } from "./ApplicationModels";
import { Order } from "./ApplicationModels";
import { Rewards } from "./ApplicationModels";
import { Feedback } from "./ApplicationModels";
import { PosCart } from "./ApplicationModels";
import { Logistic } from "./ApplicationModels";
