export = FeedbackValidator;
declare class FeedbackValidator {
    static createAbuseReport(): any;
    static updateAbuseReport(): any;
    static getAbuseReports(): any;
    static getAttributes(): any;
    static createAttribute(): any;
    static getAttribute(): any;
    static updateAttribute(): any;
    static createComment(): any;
    static updateComment(): any;
    static getComments(): any;
    static checkEligibility(): any;
    static deleteMedia(): any;
    static createMedia(): any;
    static updateMedia(): any;
    static getMedias(): any;
    static getReviewSummaries(): any;
    static createReview(): any;
    static updateReview(): any;
    static getReviews(): any;
    static getTemplates(): any;
    static createQuestion(): any;
    static updateQuestion(): any;
    static getQuestionAndAnswers(): any;
    static getVotes(): any;
    static createVote(): any;
    static updateVote(): any;
}
