on:
  release:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:

  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org
      - uses: jaywcjlove/github-action-package@main
        with:
          version: ${{ github.ref_name }}
          rename: "@gofynd/fdk-client-javascript"
      - run: npm ci
      - name: Publish package
        run: |
          VERSION=$(node -p "require('./package.json').version")

          if [[ "$VERSION" =~ -([A-Za-z]+) ]]; then
            TAG="${BASH_REMATCH[1]}"
            echo "Publishing prerelease with tag $TAG"
            npm publish --access public --tag "$TAG"
          else
            npm publish --access public
          fi